import type { L } from "@/lib/i18n";

/**
 * Answer-first content for search and AI engines (AEO / GEO): short, factual answers to the
 * questions people ask about SURMAT, shown on the page and mirrored in FAQPage JSON-LD.
 * Placeholders are filled from edition data so answers never go stale:
 * {edition} {venue} {dates} {districts} {families} {list} {exhibitors} {visitors}
 */
export type FaqId = "what" | "when" | "scope" | "visit" | "exhibit" | "scale";

export const faq: { id: FaqId; q: L; a: L }[] = [
  {
    id: "what",
    q: {
      en: "What is SURMAT?",
      fr: "Qu’est-ce que le SURMAT ?",
      ar: "ما هو سورمات؟",
      es: "¿Qué es SURMAT?",
      pt: "O que é o SURMAT?",
      it: "Che cos’è SURMAT?",
      tr: "SURMAT nedir?",
      zh: "什么是 SURMAT？",
      hi: "SURMAT क्या है?",
    },
    a: {
      en: "SURMAT is the international trade exhibition for surface materials and building finishing products. It brings manufacturers, distributors and technology suppliers together with architects, developers, contractors and buyers, in two editions: SURMAT Algeria in Oran and SURMAT Senegal in Dakar.",
      fr: "Le SURMAT est le salon professionnel international des matériaux de surface et des produits de finition du bâtiment. Il réunit fabricants, distributeurs et fournisseurs de technologies avec architectes, promoteurs, entreprises et acheteurs, en deux éditions : SURMAT Algérie à Oran et SURMAT Sénégal à Dakar.",
      ar: "سورمات هو المعرض التجاري الدولي لمواد الأسطح ومنتجات التشطيب في البناء. يجمع المصنّعين والموزعين وموردي التقنيات مع المهندسين المعماريين والمطورين والمقاولين والمشترين، في دورتين: سورمات الجزائر في وهران وسورمات السنغال في داكار.",
      es: "SURMAT es la feria comercial internacional de materiales de superficie y productos de acabado para la construcción. Reúne a fabricantes, distribuidores y proveedores de tecnología con arquitectos, promotores, constructoras y compradores, en dos ediciones: SURMAT Argelia en Orán y SURMAT Senegal en Dakar.",
      pt: "O SURMAT é a feira comercial internacional de materiais de superfície e produtos de acabamento para a construção. Reúne fabricantes, distribuidores e fornecedores de tecnologia com arquitetos, promotores, empreiteiros e compradores, em duas edições: SURMAT Argélia em Orão e SURMAT Senegal em Dacar.",
      it: "SURMAT è la fiera internazionale dei materiali di superficie e dei prodotti di finitura per l’edilizia. Riunisce produttori, distributori e fornitori di tecnologie con architetti, sviluppatori, imprese e buyer, in due edizioni: SURMAT Algeria a Orano e SURMAT Senegal a Dakar.",
      tr: "SURMAT, yüzey malzemeleri ve bina bitirme ürünleri için uluslararası ticaret fuarıdır. Üreticileri, distribütörleri ve teknoloji tedarikçilerini mimarlar, geliştiriciler, yükleniciler ve alıcılarla iki fuarda buluşturur: Oran’da SURMAT Cezayir ve Dakar’da SURMAT Senegal.",
      zh: "SURMAT 是表面材料与建筑装饰产品国际贸易展览会。它将制造商、经销商和技术供应商与建筑师、开发商、承包商和采购商汇聚在一起，共有两届展会：在奥兰举办的 SURMAT 阿尔及利亚和在达喀尔举办的 SURMAT 塞内加尔。",
      hi: "SURMAT सतह सामग्री और भवन फ़िनिशिंग उत्पादों की अंतरराष्ट्रीय व्यापार प्रदर्शनी है। यह निर्माताओं, वितरकों और तकनीक आपूर्तिकर्ताओं को आर्किटेक्ट, डेवलपर, ठेकेदारों और खरीदारों से दो संस्करणों में मिलाती है: ओरान में SURMAT अल्जीरिया और डकार में SURMAT सेनेगल।",
    },
  },
  {
    id: "when",
    q: {
      en: "When and where does {edition} take place?",
      fr: "Quand et où se tient {edition} ?",
      ar: "متى وأين يُقام {edition}؟",
      es: "¿Cuándo y dónde se celebra {edition}?",
      pt: "Quando e onde se realiza o {edition}?",
      it: "Quando e dove si svolge {edition}?",
      tr: "{edition} ne zaman ve nerede düzenleniyor?",
      zh: "{edition} 何时何地举办？",
      hi: "{edition} कब और कहाँ आयोजित होता है?",
    },
    a: {
      en: "{edition} takes place at {venue}. Dates: {dates}.",
      fr: "{edition} se tient au {venue}. Dates : {dates}.",
      ar: "يُقام {edition} في {venue}. المواعيد: {dates}.",
      es: "{edition} se celebra en {venue}. Fechas: {dates}.",
      pt: "O {edition} realiza-se em {venue}. Datas: {dates}.",
      it: "{edition} si svolge presso {venue}. Date: {dates}.",
      tr: "{edition}, {venue} adresinde düzenleniyor. Tarihler: {dates}.",
      zh: "{edition} 在 {venue} 举办。日期：{dates}。",
      hi: "{edition} {venue} में आयोजित होता है। तारीखें: {dates}।",
    },
  },
  {
    id: "scope",
    q: {
      en: "What products are exhibited at SURMAT?",
      fr: "Quels produits sont exposés au SURMAT ?",
      ar: "ما المنتجات المعروضة في سورمات؟",
      es: "¿Qué productos se exponen en SURMAT?",
      pt: "Que produtos são expostos no SURMAT?",
      it: "Quali prodotti sono esposti a SURMAT?",
      tr: "SURMAT’ta hangi ürünler sergileniyor?",
      zh: "SURMAT 展出哪些产品？",
      hi: "SURMAT में कौन-से उत्पाद प्रदर्शित होते हैं?",
    },
    a: {
      en: "{families} product families organised in {districts} districts: {list}.",
      fr: "{families} familles de produits réparties en {districts} districts : {list}.",
      ar: "{families} عائلة منتجات موزعة على {districts} أحياء: {list}.",
      es: "{families} familias de productos organizadas en {districts} distritos: {list}.",
      pt: "{families} famílias de produtos organizadas em {districts} distritos: {list}.",
      it: "{families} famiglie di prodotti organizzate in {districts} distretti: {list}.",
      tr: "{districts} bölgede düzenlenmiş {families} ürün ailesi: {list}.",
      zh: "{families} 个产品系列，分布在 {districts} 个展区：{list}。",
      hi: "{districts} ज़िलों में व्यवस्थित {families} उत्पाद परिवार: {list}।",
    },
  },
  {
    id: "visit",
    q: {
      en: "Who can visit SURMAT, and is it free?",
      fr: "Qui peut visiter le SURMAT, et l’entrée est-elle gratuite ?",
      ar: "من يمكنه زيارة سورمات، وهل الدخول مجاني؟",
      es: "¿Quién puede visitar SURMAT y es gratis?",
      pt: "Quem pode visitar o SURMAT e é gratuito?",
      it: "Chi può visitare SURMAT, ed è gratuito?",
      tr: "SURMAT’ı kimler ziyaret edebilir, giriş ücretsiz mi?",
      zh: "谁可以参观 SURMAT？是否免费？",
      hi: "SURMAT कौन देख सकता है, और क्या यह मुफ़्त है?",
    },
    a: {
      en: "Entry is free for professionals who register online: architects, interior designers, developers, contractors, installers, distributors and buyers. Your badge is sent by email before the exhibition opens.",
      fr: "L’entrée est gratuite pour les professionnels inscrits en ligne : architectes, architectes d’intérieur, promoteurs, entreprises, poseurs, distributeurs et acheteurs. Votre badge vous est envoyé par e-mail avant l’ouverture du salon.",
      ar: "الدخول مجاني للمهنيين المسجلين عبر الإنترنت: المهندسون المعماريون والمصممون الداخليون والمطورون والمقاولون والمركّبون والموزعون والمشترون. تُرسل شارتك بالبريد الإلكتروني قبل افتتاح المعرض.",
      es: "La entrada es gratuita para los profesionales que se registran en línea: arquitectos, interioristas, promotores, constructoras, instaladores, distribuidores y compradores. Su acreditación se envía por correo antes de la apertura.",
      pt: "A entrada é gratuita para profissionais que se registam online: arquitetos, designers de interiores, promotores, empreiteiros, instaladores, distribuidores e compradores. A sua credencial é enviada por e-mail antes da abertura.",
      it: "L’ingresso è gratuito per i professionisti che si registrano online: architetti, interior designer, sviluppatori, imprese, installatori, distributori e buyer. Il badge viene inviato via email prima dell’apertura.",
      tr: "Çevrimiçi kayıt olan profesyoneller için giriş ücretsizdir: mimarlar, iç mimarlar, geliştiriciler, yükleniciler, uygulayıcılar, distribütörler ve alıcılar. Yaka kartınız fuar açılmadan önce e-postayla gönderilir.",
      zh: "在线注册的专业人士免费入场：建筑师、室内设计师、开发商、承包商、安装商、经销商和采购商。胸卡会在展会开幕前通过电子邮件发送。",
      hi: "ऑनलाइन पंजीकरण करने वाले पेशेवरों के लिए प्रवेश मुफ़्त है: आर्किटेक्ट, इंटीरियर डिज़ाइनर, डेवलपर, ठेकेदार, इंस्टॉलर, वितरक और खरीदार। आपका बैज प्रदर्शनी शुरू होने से पहले ईमेल से भेजा जाता है।",
    },
  },
  {
    id: "exhibit",
    q: {
      en: "How can my company exhibit at SURMAT?",
      fr: "Comment mon entreprise peut-elle exposer au SURMAT ?",
      ar: "كيف يمكن لشركتي العرض في سورمات؟",
      es: "¿Cómo puede mi empresa exponer en SURMAT?",
      pt: "Como pode a minha empresa expor no SURMAT?",
      it: "Come può la mia azienda esporre a SURMAT?",
      tr: "Şirketim SURMAT’ta nasıl stant açabilir?",
      zh: "我的公司如何在 SURMAT 参展？",
      hi: "मेरी कंपनी SURMAT में प्रदर्शन कैसे कर सकती है?",
    },
    a: {
      en: "Apply online in five steps: choose your products, describe your company and portfolio, and SURMAT recommends a stand size. A sales manager then contacts you with stand options in the district of your products.",
      fr: "Candidatez en ligne en cinq étapes : choisissez vos produits, décrivez votre entreprise et votre portefeuille, et le SURMAT vous recommande une surface de stand. Un chargé commercial vous contacte ensuite avec des options dans le district de vos produits.",
      ar: "قدّم طلبك عبر الإنترنت في خمس خطوات: اختر منتجاتك، وعرّف بشركتك ومنتجاتها، ويوصي سورمات بمساحة الجناح. بعدها يتواصل معك مسؤول مبيعات بخيارات الأجنحة في حي منتجاتك.",
      es: "Solicítelo en línea en cinco pasos: elija sus productos, describa su empresa y su catálogo, y SURMAT le recomienda una superficie de stand. Después, un responsable comercial le contacta con opciones en el distrito de sus productos.",
      pt: "Candidate-se online em cinco passos: escolha os seus produtos, descreva a sua empresa e portefólio, e o SURMAT recomenda uma área de stand. Depois, um gestor comercial contacta-o com opções no distrito dos seus produtos.",
      it: "Candidati online in cinque passaggi: scegli i prodotti, descrivi azienda e portafoglio, e SURMAT consiglia una superficie di stand. Un responsabile commerciale ti contatta poi con le opzioni nel distretto dei tuoi prodotti.",
      tr: "Beş adımda çevrimiçi başvurun: ürünlerinizi seçin, şirketinizi ve portföyünüzü tanıtın; SURMAT size stant büyüklüğü önerir. Ardından bir satış yöneticisi, ürünlerinizin bölgesindeki stant seçenekleriyle sizinle iletişime geçer.",
      zh: "通过五个步骤在线申请：选择产品、介绍公司和产品组合，SURMAT 会推荐展位面积。随后，销售经理会联系您，提供您产品所在展区的展位方案。",
      hi: "पाँच चरणों में ऑनलाइन आवेदन करें: अपने उत्पाद चुनें, अपनी कंपनी और पोर्टफ़ोलियो बताएं, और SURMAT स्टैंड का आकार सुझाता है। फिर एक सेल्स मैनेजर आपके उत्पादों के ज़िले में स्टैंड विकल्पों के साथ संपर्क करता है।",
    },
  },
  {
    id: "scale",
    q: {
      en: "How many exhibitors and visitors does {edition} expect?",
      fr: "Combien d’exposants et de visiteurs {edition} attend-il ?",
      ar: "كم عدد العارضين والزوار المتوقع في {edition}؟",
      es: "¿Cuántos expositores y visitantes espera {edition}?",
      pt: "Quantos expositores e visitantes espera o {edition}?",
      it: "Quanti espositori e visitatori prevede {edition}?",
      tr: "{edition} kaç katılımcı ve ziyaretçi bekliyor?",
      zh: "{edition} 预计有多少参展商和观众？",
      hi: "{edition} में कितने प्रदर्शकों और आगंतुकों की उम्मीद है?",
    },
    a: {
      en: "{edition} targets {exhibitors} exhibitors and {visitors} professional visitors.",
      fr: "{edition} vise {exhibitors} exposants et {visitors} visiteurs professionnels.",
      ar: "يستهدف {edition} {exhibitors} عارض و{visitors} زائر مهني.",
      es: "{edition} prevé {exhibitors} expositores y {visitors} visitantes profesionales.",
      pt: "O {edition} prevê {exhibitors} expositores e {visitors} visitantes profissionais.",
      it: "{edition} punta a {exhibitors} espositori e {visitors} visitatori professionali.",
      tr: "{edition}, {exhibitors} katılımcı ve {visitors} profesyonel ziyaretçi hedefliyor.",
      zh: "{edition} 目标为 {exhibitors} 家参展商和 {visitors} 名专业观众。",
      hi: "{edition} का लक्ष्य {exhibitors} प्रदर्शक और {visitors} पेशेवर आगंतुक हैं।",
    },
  },
];

/** Labels for the "at a glance" facts block. */
export const glance = {
  eyebrow: { en: "Key facts", fr: "L’essentiel", ar: "حقائق أساسية", es: "Datos clave", pt: "Factos essenciais", it: "In sintesi", tr: "Temel bilgiler", zh: "关键信息", hi: "मुख्य तथ्य" } as L,
  title: { en: "SURMAT at a glance", fr: "Le SURMAT en bref", ar: "سورمات في لمحة", es: "SURMAT de un vistazo", pt: "O SURMAT num relance", it: "SURMAT in breve", tr: "Bir bakışta SURMAT", zh: "SURMAT 一览", hi: "एक नज़र में SURMAT" } as L,
  faqTitle: { en: "Frequently asked questions", fr: "Questions fréquentes", ar: "الأسئلة الشائعة", es: "Preguntas frecuentes", pt: "Perguntas frequentes", it: "Domande frequenti", tr: "Sık sorulan sorular", zh: "常见问题", hi: "अक्सर पूछे जाने वाले प्रश्न" } as L,
  event: { en: "Event", fr: "Événement", ar: "الحدث", es: "Evento", pt: "Evento", it: "Evento", tr: "Etkinlik", zh: "活动", hi: "आयोजन" } as L,
  eventValue: { en: "International trade exhibition (B2B)", fr: "Salon professionnel international (B2B)", ar: "معرض تجاري دولي (بين الشركات)", es: "Feria comercial internacional (B2B)", pt: "Feira comercial internacional (B2B)", it: "Fiera internazionale (B2B)", tr: "Uluslararası ticaret fuarı (B2B)", zh: "国际贸易展览会（B2B）", hi: "अंतरराष्ट्रीय व्यापार प्रदर्शनी (B2B)" } as L,
  venue: { en: "Venue", fr: "Lieu", ar: "المكان", es: "Sede", pt: "Local", it: "Sede", tr: "Mekân", zh: "场馆", hi: "स्थान" } as L,
  dates: { en: "Dates", fr: "Dates", ar: "المواعيد", es: "Fechas", pt: "Datas", it: "Date", tr: "Tarihler", zh: "日期", hi: "तारीखें" } as L,
  scope: { en: "Scope", fr: "Périmètre", ar: "النطاق", es: "Alcance", pt: "Âmbito", it: "Ambito", tr: "Kapsam", zh: "范围", hi: "दायरा" } as L,
  scopeValue: { en: "{districts} districts · {families} product families", fr: "{districts} districts · {families} familles de produits", ar: "{districts} أحياء · {families} عائلة منتجات", es: "{districts} distritos · {families} familias de productos", pt: "{districts} distritos · {families} famílias de produtos", it: "{districts} distretti · {families} famiglie di prodotti", tr: "{districts} bölge · {families} ürün ailesi", zh: "{districts} 个展区 · {families} 个产品系列", hi: "{districts} ज़िले · {families} उत्पाद परिवार" } as L,
  audience: { en: "Expected", fr: "Attendus", ar: "المتوقع", es: "Previsión", pt: "Previsão", it: "Previsti", tr: "Beklenen", zh: "预计", hi: "अपेक्षित" } as L,
  audienceValue: { en: "{exhibitors} exhibitors · {visitors} professional visitors", fr: "{exhibitors} exposants · {visitors} visiteurs professionnels", ar: "{exhibitors} عارض · {visitors} زائر مهني", es: "{exhibitors} expositores · {visitors} visitantes profesionales", pt: "{exhibitors} expositores · {visitors} visitantes profissionais", it: "{exhibitors} espositori · {visitors} visitatori professionali", tr: "{exhibitors} katılımcı · {visitors} profesyonel ziyaretçi", zh: "{exhibitors} 家参展商 · {visitors} 名专业观众", hi: "{exhibitors} प्रदर्शक · {visitors} पेशेवर आगंतुक" } as L,
  admission: { en: "Admission", fr: "Accès", ar: "الدخول", es: "Entrada", pt: "Entrada", it: "Ingresso", tr: "Giriş", zh: "入场", hi: "प्रवेश" } as L,
  admissionValue: { en: "Free for professionals, on registration", fr: "Gratuit pour les professionnels, sur inscription", ar: "مجاني للمهنيين، بالتسجيل", es: "Gratis para profesionales, con registro", pt: "Gratuita para profissionais, mediante registo", it: "Gratuito per i professionisti, su registrazione", tr: "Profesyoneller için ücretsiz, kayıtla", zh: "专业人士注册后免费", hi: "पेशेवरों के लिए मुफ़्त, पंजीकरण पर" } as L,
  editions: { en: "Editions", fr: "Éditions", ar: "الدورات", es: "Ediciones", pt: "Edições", it: "Edizioni", tr: "Fuarlar", zh: "届次", hi: "संस्करण" } as L,
  languages: { en: "Website languages", fr: "Langues du site", ar: "لغات الموقع", es: "Idiomas del sitio", pt: "Idiomas do site", it: "Lingue del sito", tr: "Site dilleri", zh: "网站语言", hi: "वेबसाइट की भाषाएँ" } as L,
};
