import type { L, VocabKey } from "@/lib/i18n";
import type { TexKind } from "@/lib/textures";
import type { SectorId } from "./sectors";
import type { ApplicationId } from "./applications";

export type Material = {
  slug: string;
  sector: SectorId;
  tex: TexKind;
  seed: number;
  name: L;
  summary: L;
  finishes: VocabKey[];
  formats: VocabKey[];
  applications: ApplicationId[];
  /** Typical dimensions or range; language-neutral. */
  spec?: string;
  /** Extra search terms in any language. */
  keywords?: string[];
};

export const materials: Material[] = [
  /* ---------- 01 Ceramic & Porcelain ---------- */
  {
    slug: "porcelain", sector: "ceramic-porcelain", tex: "porcelain", seed: 3,
    name: { en: "Porcelain stoneware", fr: "Grès cérame", ar: "البورسلين الحجري", es: "Gres porcelánico", pt: "Grés porcelânico", it: "Gres porcellanato", tr: "Porselen karo", zh: "瓷质砖", hi: "पोर्सिलेन स्टोनवेयर" },
    summary: {
      en: "Dense, low-absorption tile fired above 1,200 °C — the default floor for hotels, homes and retail.",
      fr: "Carreau dense à faible absorption, cuit au-delà de 1 200 °C — le sol par défaut des hôtels, logements et commerces.",
      ar: "بلاط كثيف قليل الامتصاص يُحرق فوق 1200 درجة — الأرضية الأساسية للفنادق والمنازل والمتاجر.",
      es: "Baldosa densa y de baja absorción cocida a más de 1.200 °C — el suelo de referencia en hoteles, viviendas y comercios.",
      pt: "Ladrilho denso e de baixa absorção cozido acima de 1200 °C — o pavimento de referência em hotéis, casas e lojas.",
      it: "Piastrella densa a basso assorbimento cotta oltre 1.200 °C — il pavimento di riferimento per hotel, case e negozi.",
      tr: "1.200 °C’nin üzerinde pişirilmiş, yoğun ve düşük emişli karo — otellerin, konutların ve mağazaların standart zemini.",
      zh: "高于 1200 °C 烧成的致密低吸水率瓷砖——酒店、住宅和零售空间的首选地面。",
      hi: "1,200 °C से ऊपर पकाई गई घनी, कम अवशोषण वाली टाइल — होटलों, घरों और दुकानों का मानक फर्श।",
    },
    finishes: ["matt", "polished", "textured", "antiSlip"], formats: ["tile", "largeFormat", "slab"],
    applications: ["hospitality", "residential", "commercial", "healthcare", "public"],
    spec: "60×60 → 120×280 cm", keywords: ["tile", "floor", "carrelage", "sol", "بلاط", "أرضية", "gres"],
  },
  {
    slug: "large-format-slabs", sector: "ceramic-porcelain", tex: "calacatta", seed: 11,
    name: { en: "Large-format slabs", fr: "Grandes dalles", ar: "البلاطات كبيرة المقاس", es: "Placas de gran formato", pt: "Placas de grande formato", it: "Lastre di grande formato", tr: "Büyük ebatlı plakalar", zh: "大规格岩板", hi: "बड़े आकार के स्लैब" },
    summary: {
      en: "Porcelain panels up to 3.2 m long for seamless walls, façades, worktops and furniture.",
      fr: "Panneaux en grès jusqu’à 3,2 m pour murs sans joints, façades, plans de travail et mobilier.",
      ar: "ألواح بورسلين بطول يصل إلى 3.2 م لجدران بلا فواصل وواجهات وأسطح عمل وأثاث.",
      es: "Paneles porcelánicos de hasta 3,2 m para paredes sin juntas, fachadas, encimeras y mobiliario.",
      pt: "Painéis porcelânicos até 3,2 m para paredes sem juntas, fachadas, bancadas e mobiliário.",
      it: "Pannelli in gres fino a 3,2 m per pareti senza fughe, facciate, piani di lavoro e arredi.",
      tr: "Derzsiz duvarlar, cepheler, tezgâhlar ve mobilya için 3,2 m’ye kadar porselen paneller.",
      zh: "长达 3.2 米的瓷质板材，用于无缝墙面、幕墙、台面和家具。",
      hi: "जोड़-रहित दीवारों, फ़साड, वर्कटॉप और फ़र्नीचर के लिए 3.2 मीटर तक लंबे पोर्सिलेन पैनल।",
    },
    finishes: ["polished", "matt", "satin"], formats: ["slab", "largeFormat"],
    applications: ["hospitality", "residential", "commercial"],
    spec: "160×320 cm · 6–20 mm", keywords: ["slab", "wall", "worktop", "façade", "dalle"],
  },
  {
    slug: "ceramic-tiles", sector: "ceramic-porcelain", tex: "glaze", seed: 2,
    name: { en: "Ceramic wall & floor tiles", fr: "Carreaux céramiques", ar: "البلاط الخزفي", es: "Azulejos y baldosas cerámicas", pt: "Azulejos e ladrilhos cerâmicos", it: "Piastrelle ceramiche", tr: "Seramik duvar ve yer karoları", zh: "陶瓷墙地砖", hi: "सिरेमिक दीवार और फर्श टाइलें" },
    summary: {
      en: "Glazed ceramic in every colour and relief for kitchens, bathrooms and residential floors.",
      fr: "Céramique émaillée en toutes couleurs et reliefs pour cuisines, salles de bains et sols résidentiels.",
      ar: "خزف مزجج بكل الألوان والنقوش للمطابخ والحمامات والأرضيات السكنية.",
      es: "Cerámica esmaltada en todos los colores y relieves para cocinas, baños y suelos residenciales.",
      pt: "Cerâmica vidrada em todas as cores e relevos para cozinhas, casas de banho e pavimentos residenciais.",
      it: "Ceramica smaltata in ogni colore e rilievo per cucine, bagni e pavimenti residenziali.",
      tr: "Mutfaklar, banyolar ve konut zeminleri için her renk ve dokuda sırlı seramik.",
      zh: "适用于厨房、浴室和住宅地面的各种颜色与纹理的釉面陶瓷。",
      hi: "रसोई, बाथरूम और आवासीय फर्श के लिए हर रंग और उभार में ग्लेज़्ड सिरेमिक।",
    },
    finishes: ["glossy", "matt", "textured"], formats: ["tile"],
    applications: ["residential", "healthcare", "hospitality"],
    spec: "20×20 → 60×120 cm", keywords: ["bathroom", "kitchen", "faience", "faïence", "حمام", "مطبخ"],
  },
  {
    slug: "zellige", sector: "ceramic-porcelain", tex: "zellige", seed: 4,
    name: { en: "Zellige & glazed tiles", fr: "Zellige & carreaux émaillés", ar: "الزليج والبلاط المزجج", es: "Zellige y azulejos esmaltados", pt: "Zellige e azulejos vidrados", it: "Zellige e piastrelle smaltate", tr: "Zellige ve sırlı karolar", zh: "Zellige 与釉面砖", hi: "ज़ेलीज और ग्लेज़्ड टाइलें" },
    summary: {
      en: "Hand-cut glazed terracotta with the irregular surface that catches light — a North African craft in contemporary interiors.",
      fr: "Terre cuite émaillée taillée à la main, à la surface irrégulière qui accroche la lumière — un savoir-faire maghrébin dans l’intérieur contemporain.",
      ar: "طين مزجج مقطوع يدويًا بسطح غير منتظم يلتقط الضوء — حرفة مغاربية في الديكور المعاصر.",
      es: "Terracota esmaltada cortada a mano, con una superficie irregular que atrapa la luz — un oficio norteafricano en interiores contemporáneos.",
      pt: "Terracota vidrada cortada à mão, com uma superfície irregular que capta a luz — um ofício norte-africano em interiores contemporâneos.",
      it: "Terracotta smaltata tagliata a mano, dalla superficie irregolare che cattura la luce — un’arte nordafricana negli interni contemporanei.",
      tr: "Işığı yakalayan düzensiz yüzeyiyle elde kesilmiş sırlı pişmiş toprak — çağdaş iç mekânlarda bir Kuzey Afrika zanaatı.",
      zh: "手工切割的釉面陶土，表面不规则、能捕捉光线——北非传统工艺融入当代室内。",
      hi: "हाथ से कटी ग्लेज़्ड टेराकोटा, जिसकी असमान सतह रोशनी पकड़ती है — समकालीन इंटीरियर में उत्तर अफ्रीकी शिल्प।",
    },
    finishes: ["glossy"], formats: ["tile", "mosaic"],
    applications: ["hospitality", "residential", "commercial"],
    spec: "5×5 → 10×10 cm", keywords: ["zelij", "zellij", "craft", "artisan", "زليج"],
  },
  {
    slug: "mosaic", sector: "ceramic-porcelain", tex: "mosaic", seed: 5,
    name: { en: "Mosaic", fr: "Mosaïque", ar: "الفسيفساء", es: "Mosaico", pt: "Mosaico", it: "Mosaico", tr: "Mozaik", zh: "马赛克", hi: "मोज़ेक" },
    summary: {
      en: "Glass, stone and ceramic tesserae on mesh for pools, spas and curved surfaces.",
      fr: "Tesselles de verre, pierre et céramique sur trame pour piscines, spas et surfaces courbes.",
      ar: "قطع زجاجية وحجرية وخزفية على شبك للمسابح والمنتجعات والأسطح المنحنية.",
      es: "Teselas de vidrio, piedra y cerámica sobre malla para piscinas, spas y superficies curvas.",
      pt: "Tesselas de vidro, pedra e cerâmica em rede para piscinas, spas e superfícies curvas.",
      it: "Tessere di vetro, pietra e ceramica su rete per piscine, spa e superfici curve.",
      tr: "Havuzlar, spalar ve kavisli yüzeyler için file üzerinde cam, taş ve seramik tesseralar.",
      zh: "网背玻璃、石材和陶瓷马赛克，适用于泳池、水疗和曲面。",
      hi: "पूल, स्पा और घुमावदार सतहों के लिए जाली पर कांच, पत्थर और सिरेमिक के टुकड़े।",
    },
    finishes: ["glossy", "matt"], formats: ["mosaic"],
    applications: ["hospitality", "residential", "outdoor"],
    spec: "30×30 cm sheets", keywords: ["pool", "spa", "piscine", "مسبح"],
  },
  {
    slug: "cement-tiles", sector: "ceramic-porcelain", tex: "cementTile", seed: 6,
    name: { en: "Cement tiles", fr: "Carreaux de ciment", ar: "البلاط الإسمنتي", es: "Baldosas hidráulicas", pt: "Ladrilho hidráulico", it: "Cementine", tr: "Hidrolik çini karolar", zh: "水泥花砖", hi: "सीमेंट टाइलें" },
    summary: {
      en: "Pressed, unfired encaustic tiles with inlaid pattern — heritage floors for cafés, riads and homes.",
      fr: "Carreaux pressés non cuits aux motifs incrustés — sols patrimoniaux pour cafés, riads et maisons.",
      ar: "بلاط مضغوط غير محروق بنقوش مطعّمة — أرضيات تراثية للمقاهي والرياضات والمنازل.",
      es: "Baldosas prensadas sin cocción con dibujo incrustado — suelos de tradición para cafés, riads y viviendas.",
      pt: "Ladrilhos prensados e não cozidos com desenho incrustado — pavimentos de tradição para cafés, riads e casas.",
      it: "Piastrelle pressate non cotte con decoro intarsiato — pavimenti della tradizione per caffè, riad e abitazioni.",
      tr: "Desen işlenmiş, preslenmiş ve pişirilmemiş karolar — kafeler, riadlar ve evler için geleneksel zeminler.",
      zh: "压制免烧、图案镶嵌的花砖——咖啡馆、庭院住宅和家居的传统地面。",
      hi: "जड़े हुए डिज़ाइन वाली दबाकर बनी, बिना पकी टाइलें — कैफ़े, रियाद और घरों के लिए विरासती फर्श।",
    },
    finishes: ["matt", "honed"], formats: ["tile"],
    applications: ["hospitality", "residential", "commercial"],
    spec: "20×20 cm", keywords: ["encaustic", "pattern", "motif", "carreau", "زخرفة"],
  },
  {
    slug: "terrazzo", sector: "ceramic-porcelain", tex: "terrazzo", seed: 8,
    name: { en: "Terrazzo", fr: "Terrazzo", ar: "التيرازو", es: "Terrazo", pt: "Terrazzo", it: "Terrazzo", tr: "Terrazzo", zh: "水磨石", hi: "टेराज़ो" },
    summary: {
      en: "Marble and stone chips bound in cement or resin, poured in place or supplied as tiles.",
      fr: "Éclats de marbre et de pierre liés au ciment ou à la résine, coulés en place ou en carreaux.",
      ar: "رقائق رخام وحجر مرتبطة بالإسمنت أو الراتنج، تُصب في الموقع أو تُورّد كبلاط.",
      es: "Áridos de mármol y piedra aglomerados con cemento o resina, vertidos in situ o en baldosa.",
      pt: "Agregados de mármore e pedra ligados com cimento ou resina, aplicados in situ ou fornecidos em ladrilho.",
      it: "Scaglie di marmo e pietra legate con cemento o resina, gettate in opera o fornite in piastrelle.",
      tr: "Çimento veya reçineyle bağlanmış mermer ve taş kırıkları, yerinde dökülür ya da karo olarak sunulur.",
      zh: "以水泥或树脂粘结的大理石和石材碎粒，现场浇筑或以砖材供货。",
      hi: "सीमेंट या रेज़िन से बंधे मार्बल और पत्थर के टुकड़े, जगह पर ढाले जाते हैं या टाइल के रूप में मिलते हैं।",
    },
    finishes: ["polished", "honed"], formats: ["tile", "slab"],
    applications: ["public", "commercial", "hospitality"],
    spec: "40×40 → 120×120 cm", keywords: ["granito", "chips", "airport", "مطار"],
  },
  {
    slug: "outdoor-tiles", sector: "ceramic-porcelain", tex: "outdoor", seed: 9,
    name: { en: "Outdoor tiles", fr: "Carrelage extérieur", ar: "البلاط الخارجي", es: "Baldosas de exterior", pt: "Ladrilhos de exterior", it: "Piastrelle per esterni", tr: "Dış mekân karoları", zh: "户外砖", hi: "बाहरी टाइलें" },
    summary: {
      en: "20 mm porcelain for terraces, pool decks and paving — frost-resistant and slip-rated.",
      fr: "Grès de 20 mm pour terrasses, plages de piscine et pavage — ingélif et antidérapant.",
      ar: "بورسلين بسماكة 20 مم للشرفات وحواف المسابح والأرصفة — مقاوم للصقيع والانزلاق.",
      es: "Porcelánico de 20 mm para terrazas, playas de piscina y pavimentos — resistente a la helada y antideslizante.",
      pt: "Porcelânico de 20 mm para terraços, zonas de piscina e pavimentos — resistente ao gelo e antiderrapante.",
      it: "Gres da 20 mm per terrazze, bordi piscina e pavimentazioni — ingelivo e antiscivolo.",
      tr: "Teraslar, havuz kenarları ve yürüyüş yolları için 20 mm porselen — dona dayanıklı ve kaymaz.",
      zh: "用于露台、泳池边和铺装的 20 毫米瓷砖——抗冻、防滑。",
      hi: "टैरेस, पूल डेक और पेविंग के लिए 20 मिमी पोर्सिलेन — पाला-रोधी और फिसलन-रोधी।",
    },
    finishes: ["antiSlip", "textured"], formats: ["tile", "largeFormat"],
    applications: ["outdoor", "residential", "hospitality"],
    spec: "60×60 → 60×120 cm · 20 mm", keywords: ["terrace", "exterior", "paving", "terrasse", "extérieur", "خارجي"],
  },

  /* ---------- 02 Natural & Engineered Stone ---------- */
  {
    slug: "marble", sector: "natural-engineered-stone", tex: "marble", seed: 1,
    name: { en: "Marble", fr: "Marbre", ar: "الرخام", es: "Mármol", pt: "Mármore", it: "Marmo", tr: "Mermer", zh: "大理石", hi: "मार्बल" },
    summary: {
      en: "Metamorphic limestone with veining that makes every slab unique — lobbies, bathrooms and statement walls.",
      fr: "Calcaire métamorphique dont les veines rendent chaque tranche unique — halls, salles de bains et murs signature.",
      ar: "حجر جيري متحوّل تجعل عروقه كل لوح فريدًا — للردهات والحمامات والجدران المميّزة.",
      es: "Caliza metamórfica con vetas que hacen única cada placa — vestíbulos, baños y paredes protagonistas.",
      pt: "Calcário metamórfico com veios que tornam cada placa única — átrios, casas de banho e paredes de destaque.",
      it: "Calcare metamorfico con venature che rendono unica ogni lastra — hall, bagni e pareti protagoniste.",
      tr: "Her plakayı benzersiz kılan damarlara sahip metamorfik kireç taşı — lobiler, banyolar ve vurgu duvarları.",
      zh: "纹理让每块板材独一无二的变质石灰岩——用于大堂、浴室和主题墙。",
      hi: "नसों वाला रूपांतरित चूना-पत्थर जो हर स्लैब को अनोखा बनाता है — लॉबी, बाथरूम और आकर्षक दीवारें।",
    },
    finishes: ["polished", "honed", "leather", "brushed"], formats: ["slab", "tile", "block"],
    applications: ["hospitality", "residential", "commercial", "public"],
    spec: "Slabs up to 320×190 cm", keywords: ["stone", "luxury", "lobby", "pierre", "حجر", "فخم"],
  },
  {
    slug: "travertine", sector: "natural-engineered-stone", tex: "travertine", seed: 2,
    name: { en: "Travertine", fr: "Travertin", ar: "الترافرتين", es: "Travertino", pt: "Travertino", it: "Travertino", tr: "Traverten", zh: "洞石", hi: "ट्रैवर्टीन" },
    summary: {
      en: "Banded, porous limestone in warm tones — filled and honed for walls, floors and façades.",
      fr: "Calcaire rubané et poreux aux tons chauds — rebouché et adouci pour murs, sols et façades.",
      ar: "حجر جيري متعدد الطبقات ومسامي بألوان دافئة — يُملأ ويُنعّم للجدران والأرضيات والواجهات.",
      es: "Caliza porosa y veteada en tonos cálidos — rellenada y apomazada para paredes, suelos y fachadas.",
      pt: "Calcário poroso e bandado em tons quentes — preenchido e amaciado para paredes, pavimentos e fachadas.",
      it: "Calcare poroso e venato dai toni caldi — stuccato e levigato per pareti, pavimenti e facciate.",
      tr: "Sıcak tonlarda, katmanlı ve gözenekli kireç taşı — duvarlar, zeminler ve cepheler için dolgulu ve honlu.",
      zh: "暖色调、带层纹的多孔石灰岩——经填补和亚光处理，用于墙面、地面和外立面。",
      hi: "गर्म रंगों में परतदार, छिद्रयुक्त चूना-पत्थर — दीवारों, फर्श और फ़साड के लिए भरकर होन किया गया।",
    },
    finishes: ["honed", "polished", "brushed"], formats: ["slab", "tile"],
    applications: ["hospitality", "residential", "public", "outdoor"],
    spec: "2–3 cm slabs", keywords: ["stone", "warm", "beige", "pierre", "حجر"],
  },
  {
    slug: "granite", sector: "natural-engineered-stone", tex: "granite", seed: 3,
    name: { en: "Granite", fr: "Granit", ar: "الغرانيت", es: "Granito", pt: "Granito", it: "Granito", tr: "Granit", zh: "花岗岩", hi: "ग्रेनाइट" },
    summary: {
      en: "Igneous stone with crystalline grain — the hardest natural surface for heavy traffic, stairs and kitchens.",
      fr: "Roche magmatique au grain cristallin — la surface naturelle la plus dure pour fort trafic, escaliers et cuisines.",
      ar: "صخر ناري ذو حبيبات بلورية — أصلب سطح طبيعي للحركة الكثيفة والسلالم والمطابخ.",
      es: "Piedra ígnea de grano cristalino — la superficie natural más dura para tráfico intenso, escaleras y cocinas.",
      pt: "Pedra ígnea de grão cristalino — a superfície natural mais dura para tráfego intenso, escadas e cozinhas.",
      it: "Pietra ignea a grana cristallina — la superficie naturale più dura per traffico intenso, scale e cucine.",
      tr: "Kristal taneli volkanik taş — yoğun trafik, merdivenler ve mutfaklar için en sert doğal yüzey.",
      zh: "晶粒结构的火成岩——最坚硬的天然表面，适用于高人流区域、楼梯和厨房。",
      hi: "क्रिस्टलीय दानों वाला आग्नेय पत्थर — भारी आवाजाही, सीढ़ियों और रसोई के लिए सबसे कठोर प्राकृतिक सतह।",
    },
    finishes: ["polished", "flamed", "leather", "bushHammered"], formats: ["slab", "tile", "block"],
    applications: ["public", "commercial", "outdoor", "residential"],
    spec: "2–3 cm slabs", keywords: ["stone", "kitchen", "worktop", "stairs", "pierre", "حجر"],
  },
  {
    slug: "limestone", sector: "natural-engineered-stone", tex: "limestone", seed: 4,
    name: { en: "Limestone", fr: "Pierre calcaire", ar: "الحجر الجيري", es: "Piedra caliza", pt: "Calcário", it: "Pietra calcarea", tr: "Kireç taşı", zh: "石灰石", hi: "लाइमस्टोन" },
    summary: {
      en: "Quiet, even stone for façades, cladding and calm interiors.",
      fr: "Pierre calme et homogène pour façades, bardages et intérieurs sereins.",
      ar: "حجر هادئ ومتجانس للواجهات والتكسية والديكورات الهادئة.",
      es: "Piedra serena y uniforme para fachadas, revestimientos e interiores tranquilos.",
      pt: "Pedra serena e uniforme para fachadas, revestimentos e interiores calmos.",
      it: "Pietra quieta e uniforme per facciate, rivestimenti e interni sereni.",
      tr: "Cepheler, kaplamalar ve sakin iç mekânlar için dingin ve homojen taş.",
      zh: "沉静、均匀的石材，适用于外立面、干挂和宁静的室内空间。",
      hi: "फ़साड, क्लैडिंग और शांत इंटीरियर के लिए सौम्य, एकसमान पत्थर।",
    },
    finishes: ["honed", "bushHammered", "brushed"], formats: ["slab", "tile", "block"],
    applications: ["public", "residential", "outdoor"],
    spec: "2–5 cm", keywords: ["façade", "cladding", "stone", "pierre", "واجهة"],
  },
  {
    slug: "onyx", sector: "natural-engineered-stone", tex: "onyx", seed: 5,
    name: { en: "Onyx", fr: "Onyx", ar: "الأونيكس", es: "Ónix", pt: "Ónix", it: "Onice", tr: "Oniks", zh: "缟玛瑙", hi: "ओनिक्स" },
    summary: {
      en: "Translucent banded stone, often backlit for bars, receptions and feature walls.",
      fr: "Pierre rubanée translucide, souvent rétroéclairée pour bars, accueils et murs signature.",
      ar: "حجر شفاف متموّج، يُضاء غالبًا من الخلف للبارات والاستقبالات والجدران المميّزة.",
      es: "Piedra veteada translúcida, a menudo retroiluminada en barras, recepciones y paredes protagonistas.",
      pt: "Pedra translúcida com bandas, muitas vezes retroiluminada em bares, receções e paredes de destaque.",
      it: "Pietra traslucida a bande, spesso retroilluminata in bar, reception e pareti protagoniste.",
      tr: "Barlarda, resepsiyonlarda ve vurgu duvarlarında sıklıkla arkadan aydınlatılan yarı saydam, katmanlı taş.",
      zh: "半透明带状石材，常以背光形式用于吧台、前台和主题墙。",
      hi: "पारभासी परतदार पत्थर, जिसे अक्सर बार, रिसेप्शन और आकर्षक दीवारों में पीछे से रोशन किया जाता है।",
    },
    finishes: ["polished"], formats: ["slab"],
    applications: ["hospitality", "commercial"],
    spec: "Book-matched slabs", keywords: ["backlit", "luxury", "reception", "فخم"],
  },
  {
    slug: "quartz", sector: "natural-engineered-stone", tex: "quartz", seed: 6,
    name: { en: "Quartz surfaces", fr: "Quartz", ar: "أسطح الكوارتز", es: "Superficies de cuarzo", pt: "Superfícies de quartzo", it: "Superfici in quarzo", tr: "Kuvars yüzeyler", zh: "石英石", hi: "क्वार्ट्ज़ सतहें" },
    summary: {
      en: "Engineered quartz with consistent colour and low porosity for worktops and vanities.",
      fr: "Quartz reconstitué à la teinte régulière et faible porosité pour plans de travail et vasques.",
      ar: "كوارتز مُصنّع بلون ثابت ومسامية منخفضة لأسطح المطابخ والمغاسل.",
      es: "Cuarzo técnico de color homogéneo y baja porosidad para encimeras y lavabos.",
      pt: "Quartzo técnico de cor uniforme e baixa porosidade para bancadas e lavatórios.",
      it: "Quarzo tecnico dal colore costante e bassa porosità per piani di lavoro e lavabi.",
      tr: "Tezgâhlar ve lavabolar için homojen renkli, düşük gözenekli mühendislik kuvarsı.",
      zh: "颜色稳定、孔隙率低的人造石英，用于台面和洗手台。",
      hi: "वर्कटॉप और वैनिटी के लिए एकसमान रंग और कम छिद्रता वाला इंजीनियर्ड क्वार्ट्ज़।",
    },
    finishes: ["polished", "matt"], formats: ["slab"],
    applications: ["residential", "healthcare", "commercial"],
    spec: "306×140 cm", keywords: ["engineered", "worktop", "kitchen", "counter", "plan de travail", "مطبخ"],
  },
  {
    slug: "sintered-stone", sector: "natural-engineered-stone", tex: "sintered", seed: 7,
    name: { en: "Sintered stone", fr: "Pierre frittée", ar: "الحجر الملبّد", es: "Piedra sinterizada", pt: "Pedra sinterizada", it: "Pietra sinterizzata", tr: "Sinterlenmiş taş", zh: "岩板", hi: "सिंटर्ड स्टोन" },
    summary: {
      en: "Minerals compacted under heat and pressure into ultra-thin, heat- and scratch-resistant slabs.",
      fr: "Minéraux compactés sous chaleur et pression en dalles ultra-fines, résistantes à la chaleur et aux rayures.",
      ar: "معادن مضغوطة بالحرارة والضغط في ألواح رقيقة جدًا تقاوم الحرارة والخدش.",
      es: "Minerales compactados con calor y presión en placas ultrafinas, resistentes al calor y al rayado.",
      pt: "Minerais compactados sob calor e pressão em placas ultrafinas, resistentes ao calor e aos riscos.",
      it: "Minerali compattati con calore e pressione in lastre ultrasottili, resistenti al calore e ai graffi.",
      tr: "Isı ve basınçla sıkıştırılarak ultra ince, ısıya ve çizilmeye dayanıklı plakalara dönüştürülmüş mineraller.",
      zh: "矿物经高温高压压制成的超薄板材，耐热、耐刮擦。",
      hi: "गर्मी और दबाव से अति-पतले स्लैब में दबाए गए खनिज — ताप और खरोंच प्रतिरोधी।",
    },
    finishes: ["matt", "polished", "textured"], formats: ["slab", "largeFormat"],
    applications: ["residential", "commercial", "outdoor"],
    spec: "320×160 cm · 6–20 mm", keywords: ["engineered", "worktop", "façade", "ultra compact"],
  },

  /* ---------- 03 Paints, Coatings & Decorative Finishes ---------- */
  {
    slug: "interior-paints", sector: "paints-coatings", tex: "paint", seed: 5,
    name: { en: "Interior paints", fr: "Peintures intérieures", ar: "الدهانات الداخلية", es: "Pinturas de interior", pt: "Tintas de interior", it: "Pitture per interni", tr: "İç cephe boyaları", zh: "内墙涂料", hi: "आंतरिक पेंट" },
    summary: {
      en: "Washable, low-VOC emulsions and enamels for walls, ceilings and joinery.",
      fr: "Émulsions et laques lessivables à faible COV pour murs, plafonds et menuiseries.",
      ar: "دهانات مستحلبة وورنيش قابلة للغسل ومنخفضة المركبات العضوية للجدران والأسقف والنجارة.",
      es: "Emulsiones y esmaltes lavables de bajo COV para paredes, techos y carpintería.",
      pt: "Emulsões e esmaltes laváveis com baixo teor de COV para paredes, tetos e carpintarias.",
      it: "Idropitture e smalti lavabili a basso contenuto di COV per pareti, soffitti e serramenti.",
      tr: "Duvarlar, tavanlar ve doğramalar için silinebilir, düşük VOC’li emülsiyonlar ve vernikler.",
      zh: "可擦洗、低 VOC 的乳胶漆和磁漆，用于墙面、天花和木作。",
      hi: "दीवारों, छतों और लकड़ी के काम के लिए धोने योग्य, कम-VOC इमल्शन और एनामेल।",
    },
    finishes: ["matt", "satin", "velvet", "glossy"], formats: ["liquid"],
    applications: ["residential", "healthcare", "commercial", "public"],
    keywords: ["colour", "color", "wall", "peinture", "دهان", "لون"],
  },
  {
    slug: "exterior-paints", sector: "paints-coatings", tex: "facade", seed: 3,
    name: { en: "Façade paints & renders", fr: "Peintures & enduits de façade", ar: "دهانات ولياسة الواجهات", es: "Pinturas y revocos de fachada", pt: "Tintas e rebocos de fachada", it: "Pitture e intonaci per facciate", tr: "Dış cephe boyaları ve sıvaları", zh: "外墙涂料与抹灰", hi: "बाहरी पेंट और रेंडर" },
    summary: {
      en: "Weather- and UV-resistant coatings for the heat, sun and coastal salt of the region.",
      fr: "Revêtements résistants aux intempéries et UV pour la chaleur, le soleil et le sel marin de la région.",
      ar: "طلاءات مقاومة للطقس والأشعة لحرارة المنطقة وشمسها وملوحة سواحلها.",
      es: "Revestimientos resistentes a la intemperie y a los UV para el calor, el sol y la sal costera de la región.",
      pt: "Revestimentos resistentes às intempéries e aos UV para o calor, o sol e o sal costeiro da região.",
      it: "Rivestimenti resistenti agli agenti atmosferici e ai raggi UV per il caldo, il sole e la salsedine della regione.",
      tr: "Bölgenin sıcağına, güneşine ve kıyı tuzuna karşı hava koşullarına ve UV’ye dayanıklı kaplamalar.",
      zh: "耐候、抗紫外线的涂层，适应本地区的高温、日照和沿海盐分。",
      hi: "क्षेत्र की गर्मी, धूप और तटीय नमक के लिए मौसम- और UV-प्रतिरोधी कोटिंग्स।",
    },
    finishes: ["matt", "textured"], formats: ["liquid", "paste"],
    applications: ["residential", "public", "commercial", "outdoor"],
    keywords: ["exterior", "façade", "facade", "wall", "واجهة"],
  },
  {
    slug: "microcement", sector: "paints-coatings", tex: "microcement", seed: 2,
    name: { en: "Microcement", fr: "Microciment", ar: "الميكروسمنت", es: "Microcemento", pt: "Microcimento", it: "Microcemento", tr: "Mikro beton", zh: "微水泥", hi: "माइक्रोसीमेंट" },
    summary: {
      en: "A 2–3 mm cementitious coating that covers floors, walls and showers without a single joint.",
      fr: "Un enduit cimentaire de 2 à 3 mm qui couvre sols, murs et douches sans aucun joint.",
      ar: "طلاء إسمنتي بسماكة 2–3 مم يغطي الأرضيات والجدران والدُّش دون أي فاصل.",
      es: "Un revestimiento cementoso de 2–3 mm que cubre suelos, paredes y duchas sin una sola junta.",
      pt: "Um revestimento cimentício de 2–3 mm que cobre pavimentos, paredes e duches sem uma única junta.",
      it: "Un rivestimento cementizio di 2–3 mm che copre pavimenti, pareti e docce senza una sola fuga.",
      tr: "Zeminleri, duvarları ve duşları tek bir derz olmadan kaplayan 2–3 mm çimento esaslı kaplama.",
      zh: "2–3 毫米的水泥基涂层，无一条接缝地覆盖地面、墙面和淋浴区。",
      hi: "2–3 मिमी की सीमेंट-आधारित कोटिंग जो फर्श, दीवारों और शावर को बिना एक भी जोड़ के ढकती है।",
    },
    finishes: ["matt", "satin"], formats: ["powder", "paste"],
    applications: ["residential", "hospitality", "commercial"],
    spec: "2–3 mm", keywords: ["seamless", "concrete", "béton ciré", "continuous", "بدون فواصل"],
  },
  {
    slug: "decorative-plaster", sector: "paints-coatings", tex: "tadelakt", seed: 4,
    name: { en: "Tadelakt & decorative plaster", fr: "Tadelakt & enduits décoratifs", ar: "التادلاكت والجص الزخرفي", es: "Tadelakt y revocos decorativos", pt: "Tadelakt e rebocos decorativos", it: "Tadelakt e intonaci decorativi", tr: "Tadelakt ve dekoratif sıvalar", zh: "Tadelakt 与装饰灰泥", hi: "तादेलाक्त और सजावटी प्लास्टर" },
    summary: {
      en: "Lime plasters burnished to a soft sheen — waterproof tadelakt for hammams and bathrooms, stucco for walls.",
      fr: "Enduits à la chaux lissés jusqu’à un léger lustre — tadelakt étanche pour hammams et salles de bains, stuc pour les murs.",
      ar: "لياسة جيرية مصقولة بلمعان خفيف — تادلاكت مقاوم للماء للحمّامات، وستوكو للجدران.",
      es: "Revocos de cal bruñidos hasta un brillo suave — tadelakt impermeable para hammams y baños, estuco para paredes.",
      pt: "Rebocos de cal polidos até um brilho suave — tadelakt impermeável para hammams e casas de banho, estuque para paredes.",
      it: "Intonaci a calce lucidati fino a una lucentezza morbida — tadelakt impermeabile per hammam e bagni, stucco per pareti.",
      tr: "Yumuşak bir parlaklığa kadar perdahlanmış kireç sıvalar — hamamlar ve banyolar için su geçirmez tadelakt, duvarlar için stuko.",
      zh: "打磨出柔和光泽的石灰灰泥——用于哈曼浴室和卫生间的防水 tadelakt，以及墙面灰泥。",
      hi: "हल्की चमक तक घिसे गए चूने के प्लास्टर — हमाम और बाथरूम के लिए जलरोधी तादेलाक्त, दीवारों के लिए स्टको।",
    },
    finishes: ["satin", "polished", "textured"], formats: ["paste", "powder"],
    applications: ["hospitality", "residential"],
    keywords: ["stucco", "lime", "chaux", "hammam", "حمام", "جير"],
  },
  {
    slug: "effect-coatings", sector: "paints-coatings", tex: "metallic", seed: 6,
    name: { en: "Effect coatings", fr: "Revêtements à effets", ar: "طلاءات المؤثرات", es: "Pinturas de efecto", pt: "Tintas de efeito", it: "Pitture a effetto", tr: "Efekt boyalar", zh: "艺术涂料", hi: "इफ़ेक्ट कोटिंग्स" },
    summary: {
      en: "Metallic, pearl, sand and oxidised finishes for walls that read as material, not colour.",
      fr: "Finitions métallisées, nacrées, sablées ou oxydées pour des murs qui se lisent comme une matière.",
      ar: "تشطيبات معدنية ولؤلؤية ورملية ومؤكسدة لجدران تبدو مادةً لا لونًا.",
      es: "Acabados metálicos, perlados, arenados y oxidados para paredes que se leen como materia, no como color.",
      pt: "Acabamentos metálicos, perolados, areados e oxidados para paredes que se leem como matéria, não como cor.",
      it: "Finiture metallizzate, perlate, sabbiate e ossidate per pareti che si leggono come materia, non come colore.",
      tr: "Duvarların renk değil malzeme gibi görünmesini sağlayan metalik, sedefli, kumlu ve oksitli bitişler.",
      zh: "金属、珠光、砂感和氧化效果饰面，让墙面呈现材质而非颜色。",
      hi: "धात्विक, मोती जैसी, रेतीली और ऑक्सीकृत फिनिश, जिनसे दीवारें रंग नहीं बल्कि सामग्री जैसी दिखती हैं।",
    },
    finishes: ["metallic", "textured", "satin"], formats: ["liquid", "paste"],
    applications: ["hospitality", "commercial", "residential"],
    keywords: ["metallic", "decorative", "gold", "rust", "معدني"],
  },
  {
    slug: "resin-epoxy", sector: "paints-coatings", tex: "resin", seed: 3,
    name: { en: "Resin & epoxy floors", fr: "Sols résine & époxy", ar: "أرضيات الراتنج والإيبوكسي", es: "Suelos de resina y epoxi", pt: "Pavimentos de resina e epóxi", it: "Pavimenti in resina ed epossidici", tr: "Reçine ve epoksi zeminler", zh: "树脂与环氧地坪", hi: "रेज़िन और एपॉक्सी फर्श" },
    summary: {
      en: "Poured, seamless floors for clinics, showrooms, kitchens and industry — hygienic and chemical-resistant.",
      fr: "Sols coulés sans joints pour cliniques, showrooms, cuisines et industrie — hygiéniques et résistants aux produits chimiques.",
      ar: "أرضيات مصبوبة بلا فواصل للعيادات وصالات العرض والمطابخ والصناعة — صحية ومقاومة للكيماويات.",
      es: "Suelos continuos vertidos para clínicas, showrooms, cocinas e industria — higiénicos y resistentes a químicos.",
      pt: "Pavimentos contínuos vazados para clínicas, showrooms, cozinhas e indústria — higiénicos e resistentes a químicos.",
      it: "Pavimenti continui colati per cliniche, showroom, cucine e industria — igienici e resistenti agli agenti chimici.",
      tr: "Klinikler, showroomlar, mutfaklar ve sanayi için dökme derzsiz zeminler — hijyenik ve kimyasallara dayanıklı.",
      zh: "适用于诊所、展厅、厨房和工业的浇筑无缝地面——卫生、耐化学品。",
      hi: "क्लिनिक, शोरूम, रसोई और उद्योग के लिए ढाले गए जोड़-रहित फर्श — स्वच्छ और रसायन-प्रतिरोधी।",
    },
    finishes: ["glossy", "satin", "antiSlip"], formats: ["liquid"],
    applications: ["healthcare", "commercial", "public"],
    keywords: ["seamless", "hygienic", "industrial", "floor", "hospital", "sol", "أرضية", "مستشفى"],
  },

  /* ---------- 04 Interior Finishing Systems ---------- */
  {
    slug: "gypsum-boards", sector: "interior-finishing-systems", tex: "gypsum", seed: 1,
    name: { en: "Gypsum boards", fr: "Plaques de plâtre", ar: "ألواح الجبس", es: "Placas de yeso", pt: "Placas de gesso cartonado", it: "Lastre in cartongesso", tr: "Alçı levhalar", zh: "石膏板", hi: "जिप्सम बोर्ड" },
    summary: {
      en: "Standard, moisture-, fire- and impact-rated boards for walls, linings and ceilings.",
      fr: "Plaques standard, hydrofuges, coupe-feu et haute dureté pour cloisons, doublages et plafonds.",
      ar: "ألواح قياسية ومقاومة للرطوبة والحريق والصدمات للجدران والتكسية والأسقف.",
      es: "Placas estándar, hidrófugas, ignífugas y de alta dureza para tabiques, trasdosados y techos.",
      pt: "Placas standard, hidrófugas, resistentes ao fogo e ao impacto para paredes, revestimentos e tetos.",
      it: "Lastre standard, idrorepellenti, ignifughe e ad alta resistenza agli urti per pareti, contropareti e soffitti.",
      tr: "Duvarlar, kaplamalar ve tavanlar için standart, neme, yangına ve darbeye dayanıklı levhalar.",
      zh: "用于墙体、贴面和吊顶的标准型、防潮型、防火型和抗冲击型板材。",
      hi: "दीवारों, लाइनिंग और छतों के लिए मानक, नमी-, अग्नि- और प्रभाव-प्रतिरोधी बोर्ड।",
    },
    finishes: ["raw"], formats: ["board"],
    applications: ["residential", "commercial", "healthcare", "public", "hospitality"],
    spec: "120×250 cm · 12.5 mm", keywords: ["plasterboard", "placo", "drywall", "BA13", "جبس"],
  },
  {
    slug: "suspended-ceilings", sector: "interior-finishing-systems", tex: "ceilingGrid", seed: 2,
    name: { en: "Suspended ceilings", fr: "Plafonds suspendus", ar: "الأسقف المعلقة", es: "Falsos techos", pt: "Tetos falsos", it: "Controsoffitti", tr: "Asma tavanlar", zh: "吊顶", hi: "सस्पेंडेड सीलिंग" },
    summary: {
      en: "Grid and tile ceilings that hide services and keep them accessible in offices, schools and clinics.",
      fr: "Plafonds à ossature et dalles qui dissimulent les réseaux tout en les gardant accessibles.",
      ar: "أسقف بشبكة وبلاطات تخفي التمديدات وتبقيها قابلة للوصول في المكاتب والمدارس والعيادات.",
      es: "Techos registrables de perfilería y placas que ocultan las instalaciones y las mantienen accesibles en oficinas, escuelas y clínicas.",
      pt: "Tetos modulares que escondem as instalações e as mantêm acessíveis em escritórios, escolas e clínicas.",
      it: "Controsoffitti a pannelli che nascondono gli impianti e li mantengono accessibili in uffici, scuole e cliniche.",
      tr: "Ofislerde, okullarda ve kliniklerde tesisatı gizleyen ve erişilebilir tutan karolajlı tavanlar.",
      zh: "在办公室、学校和诊所中隐藏并便于检修设备的龙骨与板块吊顶。",
      hi: "ग्रिड और टाइल वाली छतें जो कार्यालयों, स्कूलों और क्लिनिकों में सेवाओं को छिपाती हैं और सुलभ रखती हैं।",
    },
    finishes: ["matt"], formats: ["tile", "module"],
    applications: ["commercial", "healthcare", "public"],
    spec: "60×60 cm", keywords: ["ceiling", "false ceiling", "faux plafond", "سقف"],
  },
  {
    slug: "acoustic-panels", sector: "interior-finishing-systems", tex: "acoustic", seed: 3,
    name: { en: "Acoustic panels", fr: "Panneaux acoustiques", ar: "الألواح الصوتية", es: "Paneles acústicos", pt: "Painéis acústicos", it: "Pannelli fonoassorbenti", tr: "Akustik paneller", zh: "吸音板", hi: "ध्वनिक पैनल" },
    summary: {
      en: "Slatted and felt-backed panels that absorb sound in restaurants, offices and auditoriums.",
      fr: "Panneaux à lames sur feutre qui absorbent le son dans les restaurants, bureaux et auditoriums.",
      ar: "ألواح شرائحية بظهر لبادي تمتص الصوت في المطاعم والمكاتب والقاعات.",
      es: "Paneles de listones con fieltro que absorben el sonido en restaurantes, oficinas y auditorios.",
      pt: "Painéis ripados com feltro que absorvem o som em restaurantes, escritórios e auditórios.",
      it: "Pannelli a doghe con feltro che assorbono il suono in ristoranti, uffici e auditorium.",
      tr: "Restoranlarda, ofislerde ve oditoryumlarda sesi emen çıtalı, keçe destekli paneller.",
      zh: "在餐厅、办公室和礼堂中吸收声音的格栅毛毡背板。",
      hi: "रेस्तरां, कार्यालयों और सभागारों में ध्वनि सोखने वाले स्लैटेड, फ़ेल्ट-युक्त पैनल।",
    },
    finishes: ["matt", "raw"], formats: ["panel"],
    applications: ["commercial", "hospitality", "public"],
    spec: "60×240 cm", keywords: ["sound", "acoustic", "slats", "wood", "bois", "صوت"],
  },
  {
    slug: "wall-panels", sector: "interior-finishing-systems", tex: "woodSlats", seed: 4,
    name: { en: "Decorative wall panels", fr: "Panneaux muraux décoratifs", ar: "الألواح الجدارية الزخرفية", es: "Paneles murales decorativos", pt: "Painéis de parede decorativos", it: "Pannelli murali decorativi", tr: "Dekoratif duvar panelleri", zh: "装饰墙板", hi: "सजावटी वॉल पैनल" },
    summary: {
      en: "Timber, veneer, fluted and 3D panels that give walls rhythm and warmth.",
      fr: "Panneaux bois, placage, cannelés et 3D qui donnent rythme et chaleur aux murs.",
      ar: "ألواح خشبية وقشرية ومخدّدة وثلاثية الأبعاد تمنح الجدران إيقاعًا ودفئًا.",
      es: "Paneles de madera, chapa, acanalados y 3D que dan ritmo y calidez a las paredes.",
      pt: "Painéis de madeira, folheado, canelados e 3D que dão ritmo e calor às paredes.",
      it: "Pannelli in legno, impiallacciati, cannettati e 3D che danno ritmo e calore alle pareti.",
      tr: "Duvarlara ritim ve sıcaklık katan ahşap, kaplama, oluklu ve 3D paneller.",
      zh: "赋予墙面节奏与温度的实木、饰面板、凹槽和 3D 墙板。",
      hi: "लकड़ी, विनियर, फ़्लूटेड और 3D पैनल जो दीवारों को लय और गर्माहट देते हैं।",
    },
    finishes: ["raw", "satin"], formats: ["panel"],
    applications: ["hospitality", "residential", "commercial"],
    keywords: ["wood", "fluted", "cladding", "bois", "خشب"],
  },
  {
    slug: "partitions", sector: "interior-finishing-systems", tex: "partition", seed: 5,
    name: { en: "Partition systems", fr: "Cloisons", ar: "أنظمة الفواصل", es: "Sistemas de tabiquería", pt: "Sistemas de divisórias", it: "Sistemi di partizione", tr: "Bölme sistemleri", zh: "隔断系统", hi: "पार्टिशन सिस्टम" },
    summary: {
      en: "Glazed and solid demountable partitions for offices, clinics and flexible floor plates.",
      fr: "Cloisons vitrées et pleines démontables pour bureaux, cliniques et plateaux flexibles.",
      ar: "فواصل زجاجية وصلبة قابلة للفك للمكاتب والعيادات والمساحات المرنة.",
      es: "Mamparas desmontables acristaladas y ciegas para oficinas, clínicas y plantas flexibles.",
      pt: "Divisórias amovíveis envidraçadas e cegas para escritórios, clínicas e pisos flexíveis.",
      it: "Pareti mobili vetrate e cieche per uffici, cliniche e piani flessibili.",
      tr: "Ofisler, klinikler ve esnek kat planları için camlı ve dolu demonte bölmeler.",
      zh: "用于办公室、诊所和灵活楼层的可拆卸玻璃与实体隔断。",
      hi: "कार्यालयों, क्लिनिकों और लचीले फ़्लोर प्लान के लिए कांच और ठोस हटाने योग्य पार्टिशन।",
    },
    finishes: ["raw", "glossy"], formats: ["module", "panel"],
    applications: ["commercial", "healthcare"],
    keywords: ["glass", "office", "verre", "bureau", "زجاج", "مكتب"],
  },
  {
    slug: "mouldings", sector: "interior-finishing-systems", tex: "moulding", seed: 6,
    name: { en: "Mouldings & profiles", fr: "Moulures & profilés", ar: "الكرانيش والمقاطع", es: "Molduras y perfiles", pt: "Molduras e perfis", it: "Cornici e profili", tr: "Kartonpiyer ve profiller", zh: "线条与型材", hi: "मोल्डिंग और प्रोफ़ाइल" },
    summary: {
      en: "Cornices, skirting, panel mouldings and trims in plaster, PU and aluminium.",
      fr: "Corniches, plinthes, moulures et profilés en plâtre, PU et aluminium.",
      ar: "كرانيش ووزرات وإطارات ومقاطع من الجبس والبولي يوريثان والألمنيوم.",
      es: "Cornisas, rodapiés, molduras y perfiles de yeso, PU y aluminio.",
      pt: "Cornijas, rodapés, molduras e remates em gesso, PU e alumínio.",
      it: "Cornici, battiscopa, modanature e profili in gesso, PU e alluminio.",
      tr: "Alçı, PU ve alüminyumdan kartonpiyerler, süpürgelikler, çıtalar ve profiller.",
      zh: "石膏、PU 和铝制的顶角线、踢脚线、装饰线条和收边条。",
      hi: "प्लास्टर, PU और एल्युमिनियम में कॉर्निस, स्कर्टिंग, पैनल मोल्डिंग और ट्रिम।",
    },
    finishes: ["raw", "satin"], formats: ["panel"],
    applications: ["residential", "hospitality"],
    keywords: ["cornice", "corniche", "plinthe", "skirting", "كرنيش"],
  },
  {
    slug: "stretch-ceilings", sector: "interior-finishing-systems", tex: "stretch", seed: 7,
    name: { en: "Stretch ceilings", fr: "Plafonds tendus", ar: "الأسقف المشدودة", es: "Techos tensados", pt: "Tetos tensionados", it: "Controsoffitti tesi", tr: "Gergi tavanlar", zh: "软膜天花", hi: "स्ट्रेच सीलिंग" },
    summary: {
      en: "PVC and fabric membranes tensioned wall to wall — gloss, matt, printed or backlit.",
      fr: "Membranes PVC ou textiles tendues de mur à mur — laquées, mates, imprimées ou rétroéclairées.",
      ar: "أغشية PVC أو قماشية مشدودة من جدار إلى جدار — لامعة أو مطفية أو مطبوعة أو مضاءة.",
      es: "Membranas de PVC y tejido tensadas de pared a pared — brillo, mate, impresas o retroiluminadas.",
      pt: "Membranas de PVC e tecido tensionadas de parede a parede — brilho, mate, impressas ou retroiluminadas.",
      it: "Membrane in PVC e tessuto tese da parete a parete — lucide, opache, stampate o retroilluminate.",
      tr: "Duvardan duvara gerilen PVC ve kumaş membranlar — parlak, mat, baskılı veya arkadan aydınlatmalı.",
      zh: "墙到墙张拉的 PVC 和织物膜——亮面、哑光、印花或背光。",
      hi: "दीवार से दीवार तक खिंची PVC और कपड़े की झिल्लियाँ — चमकदार, मैट, प्रिंटेड या बैकलिट।",
    },
    finishes: ["glossy", "matt"], formats: ["roll"],
    applications: ["residential", "commercial", "hospitality"],
    keywords: ["ceiling", "backlit", "plafond", "سقف"],
  },

  /* ---------- 05 Construction Chemicals ---------- */
  {
    slug: "tile-adhesives", sector: "construction-chemicals", tex: "adhesive", seed: 1,
    name: { en: "Tile adhesives", fr: "Colles à carrelage", ar: "لواصق البلاط", es: "Adhesivos para cerámica", pt: "Colas para cerâmica", it: "Adesivi per piastrelle", tr: "Karo yapıştırıcıları", zh: "瓷砖胶", hi: "टाइल एडहेसिव" },
    summary: {
      en: "C1 to C2S2 cementitious adhesives rated for large formats, heat and deformation.",
      fr: "Mortiers-colles C1 à C2S2 adaptés aux grands formats, à la chaleur et à la déformation.",
      ar: "لواصق إسمنتية من C1 إلى C2S2 مناسبة للمقاسات الكبيرة والحرارة والتشوّه.",
      es: "Adhesivos cementosos de C1 a C2S2 aptos para gran formato, calor y deformación.",
      pt: "Colas cimentícias de C1 a C2S2 adequadas a grandes formatos, calor e deformação.",
      it: "Adesivi cementizi da C1 a C2S2 adatti a grandi formati, calore e deformazione.",
      tr: "Büyük ebat, ısı ve deformasyona uygun C1’den C2S2’ye çimento esaslı yapıştırıcılar.",
      zh: "C1 至 C2S2 级水泥基瓷砖胶，适用于大规格、高温和形变。",
      hi: "बड़े आकार, गर्मी और विरूपण के लिए C1 से C2S2 श्रेणी के सीमेंट-आधारित एडहेसिव।",
    },
    finishes: ["raw"], formats: ["powder", "paste"],
    applications: ["residential", "commercial", "public", "hospitality", "outdoor"],
    spec: "25 kg bags", keywords: ["glue", "colle", "installation", "لاصق"],
  },
  {
    slug: "grouts", sector: "construction-chemicals", tex: "grout", seed: 2,
    name: { en: "Grouts", fr: "Joints", ar: "مواد الترويب", es: "Materiales de rejuntado", pt: "Argamassas de junta", it: "Stucchi per fughe", tr: "Derz dolguları", zh: "填缝剂", hi: "ग्राउट" },
    summary: {
      en: "Cementitious and epoxy grouts in matched colours, stain- and mould-resistant.",
      fr: "Joints cimentaires et époxy aux teintes assorties, anti-taches et anti-moisissures.",
      ar: "مواد ترويب إسمنتية وإيبوكسية بألوان متناسقة، مقاومة للبقع والعفن.",
      es: "Juntas cementosas y epoxi en colores a juego, resistentes a manchas y moho.",
      pt: "Juntas cimentícias e epóxi em cores combinadas, resistentes a manchas e bolor.",
      it: "Stucchi cementizi ed epossidici in colori coordinati, resistenti a macchie e muffe.",
      tr: "Leke ve küfe dayanıklı, uyumlu renklerde çimento ve epoksi esaslı derz dolguları.",
      zh: "颜色匹配、防污防霉的水泥基和环氧填缝剂。",
      hi: "मेल खाते रंगों में सीमेंट और एपॉक्सी ग्राउट, दाग- और फफूंद-प्रतिरोधी।",
    },
    finishes: ["raw"], formats: ["powder", "paste"],
    applications: ["residential", "healthcare", "hospitality"],
    keywords: ["joint", "epoxy", "ترويب"],
  },
  {
    slug: "screeds", sector: "construction-chemicals", tex: "screed", seed: 3,
    name: { en: "Screeds & self-levelling", fr: "Chapes & ragréages", ar: "طبقات التسوية", es: "Recrecidos y autonivelantes", pt: "Betonilhas e autonivelantes", it: "Massetti e autolivellanti", tr: "Şaplar ve kendinden yayılan harçlar", zh: "找平层与自流平", hi: "स्क्रीड और सेल्फ़-लेवलिंग" },
    summary: {
      en: "Flat, fast-curing bases that make every floor finish possible.",
      fr: "Supports plans à séchage rapide qui rendent possible chaque revêtement de sol.",
      ar: "طبقات مستوية سريعة الجفاف تجعل كل تشطيب أرضي ممكنًا.",
      es: "Bases planas de fraguado rápido que hacen posible cualquier acabado de suelo.",
      pt: "Bases planas de secagem rápida que tornam possível qualquer acabamento de pavimento.",
      it: "Sottofondi piani a rapida asciugatura che rendono possibile ogni finitura a pavimento.",
      tr: "Her zemin kaplamasını mümkün kılan düz ve hızlı kuruyan altlıklar.",
      zh: "平整、快干的基层，让任何地面饰面成为可能。",
      hi: "समतल, जल्दी सूखने वाले आधार जो हर फर्श फिनिश को संभव बनाते हैं।",
    },
    finishes: ["raw"], formats: ["powder"],
    applications: ["residential", "commercial", "public", "healthcare"],
    keywords: ["floor", "levelling", "ragréage", "chape", "تسوية"],
  },
  {
    slug: "waterproofing", sector: "construction-chemicals", tex: "membrane", seed: 4,
    name: { en: "Waterproofing & membranes", fr: "Étanchéité & membranes", ar: "العزل المائي والأغشية", es: "Impermeabilización y membranas", pt: "Impermeabilização e membranas", it: "Impermeabilizzazioni e membrane", tr: "Su yalıtımı ve membranlar", zh: "防水与卷材", hi: "वॉटरप्रूफ़िंग और मेम्ब्रेन" },
    summary: {
      en: "Bituminous, liquid and cementitious systems for roofs, basements, wet rooms and pools.",
      fr: "Systèmes bitumineux, liquides et cimentaires pour toitures, sous-sols, pièces humides et piscines.",
      ar: "أنظمة بيتومينية وسائلة وإسمنتية للأسطح والأقبية والغرف الرطبة والمسابح.",
      es: "Sistemas bituminosos, líquidos y cementosos para cubiertas, sótanos, zonas húmedas y piscinas.",
      pt: "Sistemas betuminosos, líquidos e cimentícios para coberturas, caves, zonas húmidas e piscinas.",
      it: "Sistemi bituminosi, liquidi e cementizi per coperture, interrati, ambienti umidi e piscine.",
      tr: "Çatılar, bodrumlar, ıslak hacimler ve havuzlar için bitümlü, sıvı ve çimento esaslı sistemler.",
      zh: "用于屋面、地下室、湿区和泳池的沥青类、液体和水泥基防水系统。",
      hi: "छतों, तहखानों, गीले कमरों और पूल के लिए बिटुमिनस, तरल और सीमेंट-आधारित सिस्टम।",
    },
    finishes: ["raw"], formats: ["roll", "liquid"],
    applications: ["residential", "public", "outdoor", "hospitality"],
    keywords: ["waterproof", "roof", "étanchéité", "toiture", "عزل", "سطح"],
  },
  {
    slug: "sealants", sector: "construction-chemicals", tex: "powder", seed: 5,
    name: { en: "Sealants & primers", fr: "Mastics & primaires", ar: "مواد الإحكام والبرايمر", es: "Selladores e imprimaciones", pt: "Selantes e primários", it: "Sigillanti e primer", tr: "Mastikler ve astarlar", zh: "密封胶与底涂", hi: "सीलेंट और प्राइमर" },
    summary: {
      en: "Silicone, PU and hybrid sealants with primers that prepare every substrate.",
      fr: "Mastics silicone, PU et hybrides avec primaires adaptés à chaque support.",
      ar: "مواد إحكام سيليكونية وبولي يوريثان وهجينة مع برايمر يهيّئ كل سطح.",
      es: "Selladores de silicona, PU e híbridos con imprimaciones que preparan cualquier soporte.",
      pt: "Selantes de silicone, PU e híbridos com primários que preparam qualquer suporte.",
      it: "Sigillanti siliconici, poliuretanici e ibridi con primer che preparano ogni supporto.",
      tr: "Her yüzeyi hazırlayan astarlarla birlikte silikon, PU ve hibrit mastikler.",
      zh: "硅酮、聚氨酯和改性密封胶，配套底涂处理各类基材。",
      hi: "हर सतह को तैयार करने वाले प्राइमरों के साथ सिलिकॉन, PU और हाइब्रिड सीलेंट।",
    },
    finishes: ["raw"], formats: ["cartridge", "liquid"],
    applications: ["residential", "commercial", "public"],
    keywords: ["silicone", "mastic", "joint", "primer", "سيليكون"],
  },
  {
    slug: "mortars", sector: "construction-chemicals", tex: "powder", seed: 9,
    name: { en: "Mortars & renders", fr: "Mortiers & enduits", ar: "الملاط واللياسة", es: "Morteros y revocos", pt: "Argamassas e rebocos", it: "Malte e intonaci", tr: "Harçlar ve sıvalar", zh: "砂浆与抹灰", hi: "मोर्टार और रेंडर" },
    summary: {
      en: "Ready-mixed masonry, repair and render mortars with consistent performance on site.",
      fr: "Mortiers prêts à l’emploi de maçonnerie, réparation et enduit, constants sur chantier.",
      ar: "ملاط جاهز للبناء والترميم واللياسة بأداء ثابت في الموقع.",
      es: "Morteros premezclados de albañilería, reparación y revoco con prestaciones constantes en obra.",
      pt: "Argamassas pré-doseadas de alvenaria, reparação e reboco com desempenho constante em obra.",
      it: "Malte premiscelate da muratura, ripristino e intonaco con prestazioni costanti in cantiere.",
      tr: "Şantiyede tutarlı performans sunan hazır duvar, tamir ve sıva harçları.",
      zh: "预拌砌筑、修补和抹灰砂浆，现场性能稳定。",
      hi: "साइट पर एकसमान प्रदर्शन वाले तैयार चिनाई, मरम्मत और रेंडर मोर्टार।",
    },
    finishes: ["raw"], formats: ["powder"],
    applications: ["residential", "public", "commercial"],
    keywords: ["mortar", "mortier", "enduit", "ملاط"],
  },

  /* ---------- 06 Processing Equipment & Technologies ---------- */
  {
    slug: "cnc-waterjet", sector: "surface-technologies", tex: "metal", seed: 1,
    name: { en: "CNC & waterjet cutting", fr: "Découpe CNC & jet d’eau", ar: "القطع الرقمي وبالماء", es: "Corte CNC y por chorro de agua", pt: "Corte CNC e por jato de água", it: "Taglio CNC e a getto d’acqua", tr: "CNC ve su jeti ile kesim", zh: "CNC 与水刀切割", hi: "CNC और वॉटरजेट कटिंग" },
    summary: {
      en: "Bridge saws, 5-axis CNC and waterjets that turn blocks and slabs into finished pieces.",
      fr: "Débiteuses, CNC 5 axes et jets d’eau qui transforment blocs et tranches en pièces finies.",
      ar: "مناشير جسرية وآلات تحكم رقمي خماسية المحاور وقطع بالماء تحوّل الكتل والألواح إلى قطع جاهزة.",
      es: "Cortadoras de puente, CNC de 5 ejes y waterjets que convierten bloques y placas en piezas acabadas.",
      pt: "Serras de ponte, CNC de 5 eixos e waterjets que transformam blocos e placas em peças acabadas.",
      it: "Frese a ponte, CNC a 5 assi e waterjet che trasformano blocchi e lastre in pezzi finiti.",
      tr: "Blokları ve plakaları bitmiş parçalara dönüştüren köprü testereler, 5 eksenli CNC’ler ve su jetleri.",
      zh: "桥式切割机、五轴 CNC 和水刀，将荒料和板材加工成成品。",
      hi: "ब्रिज सॉ, 5-अक्षीय CNC और वॉटरजेट जो ब्लॉक और स्लैब को तैयार टुकड़ों में बदलते हैं।",
    },
    finishes: ["raw"], formats: ["machine"],
    applications: ["commercial"],
    keywords: ["machine", "cutting", "saw", "découpe", "آلة", "قطع"],
  },
  {
    slug: "polishing", sector: "surface-technologies", tex: "perforated", seed: 2,
    name: { en: "Polishing & grinding", fr: "Polissage & ponçage", ar: "الصقل والجلخ", es: "Pulido y rectificado", pt: "Polimento e desbaste", it: "Lucidatura e levigatura", tr: "Parlatma ve taşlama", zh: "抛光与研磨", hi: "पॉलिशिंग और ग्राइंडिंग" },
    summary: {
      en: "Line polishers, calibrators and abrasives for stone, ceramic and terrazzo.",
      fr: "Polisseuses en ligne, calibreuses et abrasifs pour pierre, céramique et terrazzo.",
      ar: "آلات صقل ومعايرة ومواد كاشطة للحجر والخزف والتيرازو.",
      es: "Pulidoras de línea, calibradoras y abrasivos para piedra, cerámica y terrazo.",
      pt: "Polidoras de linha, calibradoras e abrasivos para pedra, cerâmica e terrazzo.",
      it: "Lucidatrici in linea, calibratrici e abrasivi per pietra, ceramica e terrazzo.",
      tr: "Doğal taş, seramik ve terrazzo için hat parlatıcıları, kalibratörler ve aşındırıcılar.",
      zh: "用于石材、陶瓷和水磨石的连续抛光机、定厚机和磨料。",
      hi: "पत्थर, सिरेमिक और टेराज़ो के लिए लाइन पॉलिशर, कैलिब्रेटर और अपघर्षक।",
    },
    finishes: ["raw"], formats: ["machine"],
    applications: ["commercial"],
    keywords: ["abrasive", "polish", "polissage", "صقل"],
  },
  {
    slug: "ceramic-lines", sector: "surface-technologies", tex: "kiln", seed: 3,
    name: { en: "Ceramic lines & kilns", fr: "Lignes céramiques & fours", ar: "خطوط السيراميك والأفران", es: "Líneas cerámicas y hornos", pt: "Linhas cerâmicas e fornos", it: "Linee ceramiche e forni", tr: "Seramik hatları ve fırınlar", zh: "陶瓷生产线与窑炉", hi: "सिरेमिक लाइनें और भट्ठियाँ" },
    summary: {
      en: "Presses, dryers, glazing lines and roller kilns for tile and slab production.",
      fr: "Presses, séchoirs, lignes d’émaillage et fours à rouleaux pour carreaux et dalles.",
      ar: "مكابس ومجففات وخطوط تزجيج وأفران أسطوانية لإنتاج البلاط والألواح.",
      es: "Prensas, secaderos, líneas de esmaltado y hornos de rodillos para la producción de baldosas y placas.",
      pt: "Prensas, secadores, linhas de vidragem e fornos de rolos para a produção de ladrilhos e placas.",
      it: "Presse, essiccatoi, linee di smaltatura e forni a rulli per la produzione di piastrelle e lastre.",
      tr: "Karo ve plaka üretimi için presler, kurutucular, sırlama hatları ve merdaneli fırınlar.",
      zh: "用于瓷砖和岩板生产的压机、干燥器、施釉线和辊道窑。",
      hi: "टाइल और स्लैब उत्पादन के लिए प्रेस, ड्रायर, ग्लेज़िंग लाइनें और रोलर भट्ठियाँ।",
    },
    finishes: ["raw"], formats: ["line"],
    applications: ["commercial"],
    keywords: ["kiln", "four", "press", "factory", "usine", "فرن", "مصنع"],
  },
  {
    slug: "digital-decoration", sector: "surface-technologies", tex: "inkjet", seed: 4,
    name: { en: "Digital decoration", fr: "Décoration numérique", ar: "الزخرفة الرقمية", es: "Decoración digital", pt: "Decoração digital", it: "Decorazione digitale", tr: "Dijital dekorasyon", zh: "数码装饰", hi: "डिजिटल सजावट" },
    summary: {
      en: "Inkjet printers and ceramic inks that reproduce stone, wood and pattern at production speed.",
      fr: "Imprimantes jet d’encre et encres céramiques qui reproduisent pierre, bois et motifs en production.",
      ar: "طابعات نفث الحبر وأحبار خزفية تعيد إنتاج الحجر والخشب والنقوش بسرعة الإنتاج.",
      es: "Impresoras inkjet y tintas cerámicas que reproducen piedra, madera y diseños a velocidad de producción.",
      pt: "Impressoras inkjet e tintas cerâmicas que reproduzem pedra, madeira e padrões à velocidade de produção.",
      it: "Stampanti inkjet e inchiostri ceramici che riproducono pietra, legno e decori alla velocità di produzione.",
      tr: "Taşı, ahşabı ve desenleri üretim hızında yeniden üreten inkjet yazıcılar ve seramik mürekkepler.",
      zh: "以生产速度再现石材、木纹和图案的喷墨打印机与陶瓷墨水。",
      hi: "इंकजेट प्रिंटर और सिरेमिक स्याहियाँ जो उत्पादन की गति से पत्थर, लकड़ी और पैटर्न बनाती हैं।",
    },
    finishes: ["raw"], formats: ["machine"],
    applications: ["commercial"],
    keywords: ["inkjet", "printing", "impression", "طباعة"],
  },
  {
    slug: "automation", sector: "surface-technologies", tex: "perforated", seed: 7,
    name: { en: "Handling, automation & packaging", fr: "Manutention, automatisation & emballage", ar: "المناولة والأتمتة والتغليف", es: "Manipulación, automatización y embalaje", pt: "Movimentação, automação e embalagem", it: "Movimentazione, automazione e imballaggio", tr: "Taşıma, otomasyon ve ambalaj", zh: "搬运、自动化与包装", hi: "हैंडलिंग, ऑटोमेशन और पैकेजिंग" },
    summary: {
      en: "Robots, sorting, palletising and quality control at the end of the line.",
      fr: "Robots, tri, palettisation et contrôle qualité en bout de ligne.",
      ar: "روبوتات وفرز وتكديس وضبط جودة في نهاية خط الإنتاج.",
      es: "Robots, clasificación, paletizado y control de calidad al final de la línea.",
      pt: "Robôs, triagem, paletização e controlo de qualidade no fim da linha.",
      it: "Robot, scelta, pallettizzazione e controllo qualità a fine linea.",
      tr: "Hat sonunda robotlar, ayıklama, paletleme ve kalite kontrol.",
      zh: "生产线末端的机器人、分拣、码垛和质量检测。",
      hi: "लाइन के अंत में रोबोट, छँटाई, पैलेटाइज़िंग और गुणवत्ता नियंत्रण।",
    },
    finishes: ["raw"], formats: ["line", "machine"],
    applications: ["commercial"],
    keywords: ["robot", "packaging", "emballage", "تغليف"],
  },
  {
    slug: "raw-materials", sector: "surface-technologies", tex: "pigment", seed: 5,
    name: { en: "Raw materials & glazes", fr: "Matières premières & émaux", ar: "المواد الخام والمينا", es: "Materias primas y esmaltes", pt: "Matérias-primas e vidrados", it: "Materie prime e smalti", tr: "Hammaddeler ve sırlar", zh: "原料与釉料", hi: "कच्चा माल और ग्लेज़" },
    summary: {
      en: "Clays, feldspars, frits, pigments and glazes — the inputs of every ceramic surface.",
      fr: "Argiles, feldspaths, frittes, pigments et émaux — les intrants de chaque surface céramique.",
      ar: "الطين والفلسبار والفريت والأصباغ والمينا — مدخلات كل سطح خزفي.",
      es: "Arcillas, feldespatos, fritas, pigmentos y esmaltes — los insumos de toda superficie cerámica.",
      pt: "Argilas, feldspatos, fritas, pigmentos e vidrados — os insumos de toda a superfície cerâmica.",
      it: "Argille, feldspati, fritte, pigmenti e smalti — gli ingredienti di ogni superficie ceramica.",
      tr: "Killer, feldispatlar, fritler, pigmentler ve sırlar — her seramik yüzeyin girdileri.",
      zh: "黏土、长石、熔块、色料和釉料——所有陶瓷表面的原材料。",
      hi: "मिट्टी, फ़ेल्डस्पार, फ़्रिट, पिगमेंट और ग्लेज़ — हर सिरेमिक सतह की सामग्री।",
    },
    finishes: ["raw"], formats: ["powder"],
    applications: ["commercial"],
    keywords: ["clay", "argile", "pigment", "glaze", "émail", "طين"],
  },
];

export const materialBySlug = (slug: string) => materials.find((m) => m.slug === slug);
export const materialsBySector = (id: SectorId) => materials.filter((m) => m.sector === id);
