/** English UI dictionary — the reference shape for every language. */
export const en = {
  brand: {
    descriptor: "Surface Materials & Building Finishing Products",
    eyebrow: "The international exhibition for",
  },
  nav: {
    materials: "Materials",
    applications: "Applications",
    exhibitors: "Exhibitors",
    experience: "Experience",
    visit: "Visit",
    exhibit: "Exhibit",
    register: "Register to visit",
    search: "Search",
    menu: "Menu",
    close: "Close",
    edition: "Edition",
    language: "Language",
    skip: "Skip to content",
    pro: "Professional Space",
  },
  hero: {
    explore: "Explore materials",
    exhibit: "Exhibit at SURMAT",
    visit: "Visit SURMAT",
    searchLabel: "Search the material universe",
    searchPlaceholder: "Try “marble”, “hotel floor” or “waterproofing”",
    matches: "{n} materials brought forward",
    noMatch: "Nothing in the universe matches “{q}” yet",
    clear: "Clear search",
    close: "Back to the universe",
    exploreMaterial: "Explore material",
    findExhibitors: "Find exhibitors",
    usedIn: "Used in",
    format: "Format",
    hint: "Drag to turn the universe. Select a sample to bring it forward.",
    scroll: "Scroll to explore",
    tagline: "Materials shape better spaces",
  },
  stats: {
    sectors: "Material sectors",
    editions: "Editions",
    exhibitors: "Exhibitors (target)",
    visitors: "Professional visitors (target)",
    hub: "A regional hub for global opportunities",
  },
  home: {
    materialsTitle: "Explore the world of materials",
    materialsLead: "From natural stone to advanced finishing systems — six sectors that shape modern architecture.",
    viewAll: "View all materials",
    spacesTitle: "Materials become spaces",
    spacesLead: "Every material at SURMAT ends up in a hotel, a home, a hospital or a public building. Start from the space.",
    exploreApps: "Explore all applications",
    industryTitle: "Meet the industry",
    industryLead: "Manufacturers, suppliers and innovators presenting their collections at SURMAT.",
    viewExhibitors: "View exhibitors",
    experienceTitle: "Experience SURMAT",
    experienceLead: "Walk the six districts of the exhibition floor and find every stand by the material it shows.",
    exploreExperience: "Explore the experience",
    editionsTitle: "SURMAT editions",
    editionsLead: "Two markets. One material universe.",
    exploreEdition: "Explore edition",
    current: "You are here",
    visitTitle: "Come and touch the materials",
    visitLead: "Registration is free for architects, developers, contractors, distributors and buyers.",
    exhibitTitle: "Your products belong here",
    exhibitLead: "Put your collections in front of the people who specify, buy and install them.",
    editionsHeadline: "Two editions. One platform.",
  },
  why: {
    eyebrow: "Why exhibit",
    title: "One stand. Four markets.",
    lead: "SURMAT connects the manufacturers of every surface in a building with the people building North and West Africa — and gives companies from around the world a door into the continent.",
    markets: [
      {
        id: "dz",
        name: "Algeria",
        kicker: "North Africa’s largest market",
        points: [
          "Africa’s largest country by area, with around 47 million people",
          "Sustained programmes in housing, infrastructure, hospitality and public buildings",
          "A bridge between the Maghreb, the Mediterranean and the Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "The door to West Africa",
        points: [
          "Dakar: a stable, fast-growing business hub on the Atlantic",
          "Member of ECOWAS (15 countries) and WAEMU (8 countries sharing the CFA franc)",
          "New cities, ports, hotels and public facilities under construction",
        ],
      },
      {
        id: "africa",
        name: "Africa",
        kicker: "The next building boom",
        points: [
          "More than 1.4 billion people — the youngest population in the world",
          "The African Continental Free Trade Area brings 54 countries into one market",
          "Urban population expected to nearly double by 2050",
        ],
      },
      {
        id: "world",
        name: "The world",
        kicker: "Your door into the continent",
        points: [
          "National pavilions for Europe, Türkiye, China, India, the Gulf and the Americas",
          "Meet importers, distributors and agents from across Africa in one place",
          "A platform in nine languages, open to exhibitors from every country",
        ],
      },
    ],
    offerTitle: "What exhibitors get",
    offerLead: "Everything at SURMAT is built around one outcome: putting your products in front of the people who specify, buy and install them.",
    offer: [
      {
        title: "Qualified buyers",
        text: "Architects, developers, contractors, distributors and public buyers, registered by profile and by the materials they source.",
      },
      { title: "Meetings booked in advance", text: "Visitors request meetings with your stand before the doors open. You arrive with an agenda, not a hope." },
      { title: "The right district", text: "Your stand sits among the materials you make — exactly where specifiers go to compare them." },
      { title: "A year-round showroom", text: "Your profile in the SURMAT material library keeps working after the show, in nine languages." },
      { title: "A stage for launches", text: "Present new collections and technologies in the conference and live-demonstration programme." },
      { title: "Market intelligence", text: "See which materials and applications draw the most interest in each market, edition after edition." },
    ],
    audienceTitle: "Who you will meet",
    audienceLead: "Professional visitors only. Every one registers with a profile and the materials they are sourcing.",
    participateTitle: "Ways to take part",
    participate: [
      { title: "Stand", text: "Space only or shell scheme, from 9 m², in the district of your materials." },
      { title: "National pavilion", text: "Exhibit under your country’s flag with a shared pavilion and joint promotion." },
      { title: "Sponsorship", text: "Put your brand on the exhibition, the conference stage or the visitor journey." },
      { title: "Digital showroom", text: "Not ready for a stand yet? Start with a profile in the online material library." },
    ],
    cta: "Apply to exhibit",
    brochure: "Talk to our sales team",
  },
  universe: {
    title: "Discover the material universe",
    lead: "Explore a rich library of surface materials and finishing products, from natural stone to advanced technologies.",
    browse: "Browse all materials",
    explore: "Explore material",
    exhibitThis: "Exhibit this product",
    prev: "Previous material",
    next: "Next material",
    taglines: {
      "ceramic-porcelain": "Engineered to last. Designed to be seen.",
      "natural-engineered-stone": "Natural beauty. Lasting value.",
      "paints-coatings": "Colour, texture and protection.",
      "interior-finishing-systems": "The systems behind every interior.",
      "construction-chemicals": "What holds every surface in place.",
      "surface-technologies": "Where surfaces are made.",
    },
  },
  explorer: {
    title: "Materials for every space",
    lead: "Select a point in the space to see the material behind it — and the exhibitors who make it.",
    viewMaterial: "View material",
    findExhibitors: "Find exhibitors",
    surfaces: { floor: "Flooring", wall: "Walls", feature: "Feature wall", counter: "Reception counter", ceiling: "Ceiling" },
  },
  leading: {
    title: "Leading exhibitors",
    lead: "Manufacturers presenting their collections at SURMAT — each with a digital showroom.",
    discover: "Discover exhibitor",
    featured: "Featured products",
  },
  split: {
    visitTitle: "Visit SURMAT",
    visitLead: "Register now to attend the exhibition.",
    exhibitTitle: "Exhibit at SURMAT",
    exhibitLead: "Showcase your products to a qualified audience of professionals.",
  },
  success: {
    next: "What happens next",
    calendar: "Add to calendar",
    visitSteps: [
      "Your badge arrives by email before the doors open.",
      "Request meetings with exhibitors from their showroom pages.",
      "Bring your badge on your phone to the venue.",
    ],
    exhibitSteps: [
      "A sales manager contacts you with stand options and prices.",
      "You confirm your space in the district of your materials.",
      "Your digital showroom goes live once your participation is confirmed.",
    ],
  },
  pro: {
    title: "Professional Space",
    lead: "A private space for exhibitors and professional visitors, opening ahead of each edition.",
    soon: "Opens to confirmed exhibitors before the edition",
    features: [
      "Exhibitor dashboard and lead management",
      "Edit your showroom profile and product catalogue",
      "Meeting requests with professional visitors",
      "Documents, badges and event information",
    ],
    exhibitorCta: "Apply to exhibit",
    visitorCta: "Register to visit",
    contactCta: "Contact the SURMAT team",
  },
  contact: {
    title: "Contact",
    lead: "Tell us who you are and what you need. The right member of the SURMAT team will reply.",
    topic: "Subject",
    topics: {
      exhibitor: "Exhibiting at SURMAT",
      visitor: "Visiting SURMAT",
      buyer: "Sourcing and buying",
      partner: "Partnership",
      media: "Press and media",
      speaker: "Speaking at the conference",
      other: "Other",
    },
    message: "Message",
    submit: "Send message",
    successTitle: "Message sent.",
    successLead: "We will reply to {email}.",
  },
  legal: {
    title: "Legal notice",
    publisher: "Publisher",
    pending: "The publisher’s details will be published here before launch.",
    hosting: "Hosting",
    hostingText: "This website is hosted by Vercel Inc., United States.",
    ip: "Intellectual property",
    ipText: "The SURMAT name, content and design of this website are protected. Exhibitor names, logos and product images belong to their respective owners and are shown with their permission.",
  },
  privacy: {
    title: "Privacy",
    lead: "What this website collects, why, and how to reach us about it.",
    sections: [
      {
        title: "What we collect",
        text: "The details you enter in our forms — name, work email, company, job title, phone, country and your answers — together with the page and campaign that brought you to SURMAT.",
      },
      {
        title: "Why",
        text: "To register your visit, process your exhibitor application or answer your message. We contact you about the edition only if you tick the consent box.",
      },
      {
        title: "Analytics",
        text: "We record anonymous interactions — materials viewed, searches, clicks on calls to action — to improve the platform and understand which materials draw interest. They are not linked to your name.",
      },
      {
        title: "Cookies",
        text: "We keep two preference cookies, your edition and your language, for one year. This website does not use advertising cookies.",
      },
      { title: "Your rights", text: "You can ask to see, correct or delete your data at any time by writing to the SURMAT team." },
    ],
  },
  sector: {
    materials: "Materials in this sector",
    exhibitors: "Exhibitors in this district",
    district: "District",
  },
  material: {
    sector: "Sector",
    finishes: "Finishes",
    applications: "Applications",
    formats: "Formats",
    spec: "Typical range",
    exhibitors: "Exhibitors presenting this material",
    noExhibitors: "No exhibitor has confirmed this material yet. Yours could be the first.",
    related: "Related materials",
    manufacturerQ: "Do you manufacture {material}?",
    usedIn: "Used in:",
  },
  catalogue: {
    title: "Material library",
    lead: "Every material presented at SURMAT, organised by sector. Each one leads to the companies that make it.",
    all: "All sectors",
    search: "Filter materials",
    noResults: "No materials match “{q}”. Try a broader word such as “stone” or “tile”.",
    count: "{n} materials",
  },
  apps: {
    title: "Applications",
    lead: "Start from the space you are building and meet the exhibitors who supply every surface in it.",
    materialsUsed: "Materials in this space",
    suppliers: "Exhibitors supplying these materials",
  },
  exhibitors: {
    title: "Exhibitors",
    lead: "Browse the companies presenting at SURMAT by the materials they make.",
    sample: "Sample profile",
    sampleNote: "Sample profiles show how exhibitor showrooms will appear. Confirmed exhibitors are published as they sign.",
    district: "District",
    stand: "Stand",
    requestMeeting: "Request a meeting",
    visitStand: "Find the stand",
    products: "Product wall",
    materials: "Materials",
    markets: "Markets",
    founded: "Founded",
    all: "All",
    empty: "No exhibitors in this sector yet.",
  },
  experience: {
    title: "The SURMAT experience",
    lead: "The exhibition is organised as six material districts. Walk the floor, find a stand, book yours.",
    mapTitle: "Exhibition floor",
    mapHint: "Select a stand to see who is exhibiting.",
    open: "Open stand",
    available: "Available stand",
    availableLead: "This stand is open for booking.",
    book: "Book this stand",
    teaserTitle: "More than an exhibition",
    teaserLead: "An immersive journey through materials, applications, innovation and industry expertise.",
    central: "Central experience",
    branches: [
      "Floor plan",
      "Material districts",
      "Conference",
      "Product demonstrations",
      "Networking",
    ],
  },
  visit: {
    title: "Visit SURMAT",
    lead: "Four days with the manufacturers of every surface in a building. Registration is free for professionals.",
    who: "Who visits",
    profiles: {
      architect: "Architect or interior designer",
      developer: "Developer or project owner",
      contractor: "Contractor or installer",
      distributor: "Distributor or retailer",
      buyer: "Buyer or procurement",
      manufacturer: "Manufacturer",
      other: "Other professional",
    },
    formTitle: "Register to visit",
    profile: "Your profile",
    interests: "Materials you are sourcing",
    submit: "Register to visit",
    successTitle: "You are registered.",
    successLead: "Your badge will be sent to {email} before the exhibition opens.",
    meetingWith: "Meeting request for {name}",
  },
  exhibit: {
    title: "Exhibit at SURMAT",
    lead: "Your products belong here.",
    why: [
      "Architects, developers, contractors and distributors from Algeria, Senegal and across Africa",
      "Your stand sits in the district of your materials, where specifiers come looking",
      "Your products stay online all year in the SURMAT material library, in nine languages",
    ],
    steps: ["Materials", "Company", "Portfolio", "Space", "Contact"],
    manufacture: "What do you manufacture?",
    companyTitle: "Tell us about your company",
    portfolioTitle: "What will you show?",
    spaceTitle: "How much space do you need?",
    contactTitle: "Who should we contact?",
    companyName: "Company name",
    website: "Website",
    country: "Country",
    families: "Product families",
    brands: "Brands",
    machinery: "We will demonstrate machinery",
    demo: "We want a live demonstration area",
    meetingRoom: "We need a private meeting area",
    description: "Products you plan to show",
    recommended: "Based on your portfolio, SURMAT recommends {min}–{max} m².",
    requested: "Requested space (m²)",
    edition: "Edition",
    back: "Back",
    next: "Continue",
    submit: "Send application",
    successTitle: "Your products belong at SURMAT.",
    successLead: "A SURMAT sales manager will contact {email} with stand options in the {sector} district.",
    pickOne: "Select at least one sector to continue.",
  },
  form: {
    name: "Full name",
    role: "Job title",
    company: "Company",
    email: "Work email",
    phone: "Phone",
    country: "Country",
    required: "Required",
    invalidEmail: "Enter an email address like name@company.com.",
    error: "Your form could not be sent. Check your connection and try again.",
    sending: "Sending…",
    consent: "SURMAT may contact me about this edition.",
  },
  cta: {
    dialogTitle: "Exhibit at SURMAT",
    dialogLead: "Your products belong here.",
    apply: "Apply to exhibit",
    close: "Close",
  },
  edition: {
    datesTBA: "Dates to be announced",
    venueTBA: "Venue to be announced",
    switchTo: "Switch to {name}",
  },
  search: {
    title: "Search SURMAT",
    placeholder: "Material, space or company — e.g. “marble hotel floor”",
    materials: "Materials",
    sectors: "Sectors",
    applications: "Applications",
    exhibitors: "Exhibitors",
    empty: "Type a material, a space or a company.",
    none: "No results for “{q}”. Try a single material such as “porcelain”.",
    popularMaterials: "Popular materials",
    popularApplications: "Popular applications",
    featuredExhibitors: "Featured exhibitors",
  },
  footer: {
    tagline: "The international exhibition for surface materials & building finishing products.",
    rights: "© {year} SURMAT. All rights reserved.",
    platform: "Platform",
    editions: "Editions",
    languages: "Languages",
    legal: "Legal notice",
    privacy: "Privacy",
    contact: "Contact",
  },
  common: { back: "Back", all: "All", learnMore: "Learn more", of: "of", explore: "Explore" },
  vocab: {
    matt: "Matt", polished: "Polished", honed: "Honed", textured: "Textured", antiSlip: "Anti-slip",
    brushed: "Brushed", glossy: "Gloss", satin: "Satin", leather: "Leathered", flamed: "Flamed",
    bushHammered: "Bush-hammered", metallic: "Metallic", velvet: "Velvet", raw: "Natural",
    tile: "Tile", largeFormat: "Large format", slab: "Slab", mosaic: "Mosaic", block: "Block",
    board: "Board", panel: "Panel", roll: "Roll", liquid: "Liquid", powder: "Powder", paste: "Paste",
    cartridge: "Cartridge", line: "Production line", machine: "Machine", module: "Module",
  },
};

export type Dict = typeof en;
