import type { Dict } from "./en";

export const es: Dict = {
  brand: {
    descriptor: "Materiales de superficie y productos de acabado para la construcción",
    eyebrow: "La feria internacional de",
  },
  nav: {
    materials: "Materiales",
    applications: "Aplicaciones",
    exhibitors: "Expositores",
    experience: "Experiencia",
    visit: "Visitar",
    exhibit: "Exponer",
    register: "Registrarse para visitar",
    search: "Buscar",
    menu: "Menú",
    close: "Cerrar",
    edition: "Edición",
    language: "Idioma",
    skip: "Ir al contenido",
  },
  hero: {
    explore: "Explorar materiales",
    exhibit: "Exponer en SURMAT",
    visit: "Visitar SURMAT",
    searchLabel: "Buscar en el universo de materiales",
    searchPlaceholder: "Pruebe “mármol”, “suelo de hotel” o “impermeabilización”",
    matches: "{n} materiales destacados",
    noMatch: "Nada en el universo coincide todavía con “{q}”",
    clear: "Borrar la búsqueda",
    close: "Volver al universo",
    exploreMaterial: "Ver el material",
    findExhibitors: "Encontrar expositores",
    usedIn: "Se usa en",
    format: "Formato",
    hint: "Arrastre para girar el universo. Seleccione una muestra para acercarla.",
  },
  stats: {
    sectors: "Sectores de materiales",
    editions: "Ediciones",
    exhibitors: "Expositores (objetivo)",
    visitors: "Visitantes profesionales (objetivo)",
    hub: "Un centro regional para oportunidades globales",
  },
  home: {
    materialsTitle: "Explore el mundo de los materiales",
    materialsLead: "De la piedra natural a los sistemas de acabado más avanzados — seis sectores que dan forma a la arquitectura moderna.",
    viewAll: "Ver todos los materiales",
    spacesTitle: "Los materiales se convierten en espacios",
    spacesLead: "Cada material de SURMAT termina en un hotel, una vivienda, un hospital o un edificio público. Empiece por el espacio.",
    exploreApps: "Ver todas las aplicaciones",
    industryTitle: "Conozca la industria",
    industryLead: "Fabricantes, proveedores e innovadores que presentan sus colecciones en SURMAT.",
    viewExhibitors: "Ver expositores",
    experienceTitle: "Viva SURMAT",
    experienceLead: "Recorra los seis distritos de la feria y encuentre cada stand por el material que presenta.",
    exploreExperience: "Descubrir la experiencia",
    editionsTitle: "Ediciones de SURMAT",
    editionsLead: "Dos mercados. Un universo de materiales.",
    exploreEdition: "Ver la edición",
    current: "Usted está aquí",
    visitTitle: "Venga a tocar los materiales",
    visitLead: "El registro es gratuito para arquitectos, promotores, constructores, distribuidores y compradores.",
    exhibitTitle: "Sus productos tienen su lugar aquí",
    exhibitLead: "Ponga sus colecciones frente a quienes las prescriben, las compran y las instalan.",
  },
  why: {
    eyebrow: "Por qué exponer",
    title: "Un stand. Cuatro mercados.",
    lead: "SURMAT conecta a los fabricantes de cada superficie de un edificio con quienes construyen el norte y el oeste de África — y abre a empresas de todo el mundo una puerta al continente.",
    markets: [
      {
        id: "dz",
        name: "Argelia",
        kicker: "El mayor mercado del norte de África",
        points: [
          "El país más extenso de África, con unos 47 millones de habitantes",
          "Programas sostenidos de vivienda, infraestructuras, hostelería y edificios públicos",
          "Un puente entre el Magreb, el Mediterráneo y el Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "La puerta de África Occidental",
        points: [
          "Dakar: un centro de negocios estable y dinámico sobre el Atlántico",
          "Miembro de la CEDEAO (15 países) y de la UEMOA (8 países que comparten el franco CFA)",
          "Nuevas ciudades, puertos, hoteles y equipamientos públicos en construcción",
        ],
      },
      {
        id: "africa",
        name: "África",
        kicker: "El próximo auge de la construcción",
        points: [
          "Más de 1.400 millones de habitantes — la población más joven del mundo",
          "La Zona de Libre Comercio Continental Africana reúne a 54 países en un solo mercado",
          "Se espera que la población urbana casi se duplique de aquí a 2050",
        ],
      },
      {
        id: "world",
        name: "El mundo",
        kicker: "Su puerta al continente",
        points: [
          "Pabellones nacionales para Europa, Türkiye, China, India, el Golfo y las Américas",
          "Reúnase en un solo lugar con importadores, distribuidores y agentes de toda África",
          "Una plataforma en nueve idiomas, abierta a expositores de todos los países",
        ],
      },
    ],
    offerTitle: "Lo que obtienen los expositores",
    offerLead: "Todo en SURMAT se construye en torno a un resultado: poner sus productos frente a quienes los prescriben, los compran y los instalan.",
    offer: [
      {
        title: "Compradores cualificados",
        text: "Arquitectos, promotores, constructores, distribuidores y compradores públicos, registrados por perfil y por los materiales que buscan.",
      },
      { title: "Reuniones concertadas de antemano", text: "Los visitantes solicitan citas en su stand antes de la apertura. Usted llega con una agenda, no con una esperanza." },
      { title: "El distrito adecuado", text: "Su stand se sitúa entre los materiales que fabrica — justo donde los prescriptores van a compararlos." },
      { title: "Un showroom todo el año", text: "Su perfil en la biblioteca de materiales de SURMAT sigue trabajando después de la feria, en nueve idiomas." },
      { title: "Un escenario para sus lanzamientos", text: "Presente nuevas colecciones y tecnologías en el programa de conferencias y demostraciones en vivo." },
      { title: "Inteligencia de mercado", text: "Vea qué materiales y aplicaciones despiertan más interés en cada mercado, edición tras edición." },
    ],
    audienceTitle: "A quién conocerá",
    audienceLead: "Solo visitantes profesionales. Cada uno se registra con su perfil y los materiales que busca.",
    participateTitle: "Formas de participar",
    participate: [
      { title: "Stand", text: "Solo suelo o stand modular, desde 9 m², en el distrito de sus materiales." },
      { title: "Pabellón nacional", text: "Exponga bajo la bandera de su país en un pabellón compartido con promoción conjunta." },
      { title: "Patrocinio", text: "Asocie su marca a la feria, al escenario de conferencias o al recorrido del visitante." },
      { title: "Showroom digital", text: "¿Aún no está listo para un stand? Empiece con un perfil en la biblioteca de materiales en línea." },
    ],
    cta: "Solicitar un stand",
    brochure: "Hablar con el equipo comercial",
  },
  sector: {
    materials: "Materiales de este sector",
    exhibitors: "Expositores de este distrito",
    district: "Distrito",
  },
  material: {
    sector: "Sector",
    finishes: "Acabados",
    applications: "Aplicaciones",
    formats: "Formatos",
    spec: "Gama habitual",
    exhibitors: "Expositores que presentan este material",
    noExhibitors: "Ningún expositor ha confirmado aún este material. El suyo podría ser el primero.",
    related: "Materiales relacionados",
    manufacturerQ: "¿Fabrica usted {material}?",
  },
  catalogue: {
    title: "Biblioteca de materiales",
    lead: "Todos los materiales presentados en SURMAT, organizados por sector. Cada uno lleva a las empresas que lo fabrican.",
    all: "Todos los sectores",
    search: "Filtrar materiales",
    noResults: "Ningún material coincide con “{q}”. Pruebe una palabra más amplia como “piedra” o “baldosa”.",
    count: "{n} materiales",
  },
  apps: {
    title: "Aplicaciones",
    lead: "Empiece por el espacio que está construyendo y conozca a los expositores que suministran cada una de sus superficies.",
    materialsUsed: "Materiales de este espacio",
    suppliers: "Expositores que suministran estos materiales",
  },
  exhibitors: {
    title: "Expositores",
    lead: "Explore las empresas presentes en SURMAT según los materiales que fabrican.",
    sample: "Perfil de ejemplo",
    sampleNote: "Los perfiles de ejemplo muestran cómo se verán los showrooms de los expositores. Los expositores confirmados se publican a medida que firman.",
    district: "Distrito",
    stand: "Stand",
    requestMeeting: "Solicitar una reunión",
    visitStand: "Encontrar el stand",
    products: "Muro de productos",
    materials: "Materiales",
    markets: "Mercados",
    founded: "Fundada en",
    all: "Todos",
    empty: "Todavía no hay expositores en este sector.",
  },
  experience: {
    title: "La experiencia SURMAT",
    lead: "La feria se organiza en seis distritos de materiales. Recorra el plano, encuentre un stand, reserve el suyo.",
    mapTitle: "Plano de la feria",
    mapHint: "Seleccione un stand para ver quién expone.",
    open: "Ver el stand",
    available: "Stand disponible",
    availableLead: "Este stand está disponible para reservar.",
    book: "Reservar este stand",
  },
  visit: {
    title: "Visitar SURMAT",
    lead: "Cuatro días con los fabricantes de cada superficie de un edificio. El registro es gratuito para profesionales.",
    who: "Quién visita",
    profiles: {
      architect: "Arquitecto o interiorista",
      developer: "Promotor o propiedad",
      contractor: "Constructor o instalador",
      distributor: "Distribuidor o minorista",
      buyer: "Comprador o compras",
      manufacturer: "Fabricante",
      other: "Otro profesional",
    },
    formTitle: "Registrarse para visitar",
    profile: "Su perfil",
    interests: "Materiales que busca",
    submit: "Registrarse para visitar",
    successTitle: "Ya está registrado.",
    successLead: "Su acreditación se enviará a {email} antes de la apertura de la feria.",
    meetingWith: "Solicitud de reunión con {name}",
  },
  exhibit: {
    title: "Exponer en SURMAT",
    lead: "Sus productos tienen su lugar aquí.",
    why: [
      "Arquitectos, promotores, constructores y distribuidores de Argelia, Senegal y toda África",
      "Su stand está en el distrito de sus materiales, donde los prescriptores vienen a buscar",
      "Sus productos siguen en línea todo el año en la biblioteca de materiales de SURMAT, en nueve idiomas",
    ],
    steps: ["Materiales", "Empresa", "Catálogo", "Espacio", "Contacto"],
    manufacture: "¿Qué fabrica usted?",
    companyTitle: "Háblenos de su empresa",
    portfolioTitle: "¿Qué va a presentar?",
    spaceTitle: "¿Cuánto espacio necesita?",
    contactTitle: "¿A quién debemos contactar?",
    companyName: "Nombre de la empresa",
    website: "Sitio web",
    country: "País",
    families: "Familias de productos",
    brands: "Marcas",
    machinery: "Haremos demostraciones de maquinaria",
    demo: "Queremos una zona de demostración en vivo",
    meetingRoom: "Necesitamos una zona de reuniones privada",
    description: "Productos que prevé presentar",
    recommended: "Según su catálogo, SURMAT recomienda {min}–{max} m².",
    requested: "Superficie solicitada (m²)",
    edition: "Edición",
    back: "Atrás",
    next: "Continuar",
    submit: "Enviar la solicitud",
    successTitle: "Sus productos tienen su lugar en SURMAT.",
    successLead: "Un responsable comercial de SURMAT contactará con {email} con opciones de stand en el distrito {sector}.",
    pickOne: "Seleccione al menos un sector para continuar.",
  },
  form: {
    name: "Nombre completo",
    role: "Cargo",
    company: "Empresa",
    email: "Correo profesional",
    phone: "Teléfono",
    country: "País",
    required: "Obligatorio",
    invalidEmail: "Introduzca una dirección como nombre@empresa.com.",
    error: "No se ha podido enviar el formulario. Compruebe su conexión e inténtelo de nuevo.",
    sending: "Enviando…",
    consent: "SURMAT puede contactarme sobre esta edición.",
  },
  cta: {
    dialogTitle: "Exponer en SURMAT",
    dialogLead: "Sus productos tienen su lugar aquí.",
    apply: "Solicitar un stand",
    close: "Cerrar",
  },
  edition: {
    datesTBA: "Fechas por anunciar",
    venueTBA: "Sede por anunciar",
    switchTo: "Cambiar a {name}",
  },
  search: {
    title: "Buscar en SURMAT",
    placeholder: "Material, espacio o empresa — p. ej. “suelo de mármol hotel”",
    materials: "Materiales",
    sectors: "Sectores",
    applications: "Aplicaciones",
    exhibitors: "Expositores",
    empty: "Escriba un material, un espacio o una empresa.",
    none: "Sin resultados para “{q}”. Pruebe con un solo material, como “porcelánico”.",
  },
  footer: {
    tagline: "La feria internacional de materiales de superficie y productos de acabado para la construcción.",
    rights: "© {year} SURMAT. Todos los derechos reservados.",
    platform: "Plataforma",
    editions: "Ediciones",
  },
  common: { back: "Atrás", all: "Todos", learnMore: "Más información", of: "de" },
  vocab: {
    matt: "Mate", polished: "Pulido", honed: "Apomazado", textured: "Texturizado", antiSlip: "Antideslizante",
    brushed: "Cepillado", glossy: "Brillo", satin: "Satinado", leather: "Envejecido", flamed: "Flameado",
    bushHammered: "Abujardado", metallic: "Metálico", velvet: "Aterciopelado", raw: "Natural",
    tile: "Baldosa", largeFormat: "Gran formato", slab: "Placa", mosaic: "Mosaico", block: "Bloque",
    board: "Placa", panel: "Panel", roll: "Rollo", liquid: "Líquido", powder: "Polvo", paste: "Pasta",
    cartridge: "Cartucho", line: "Línea de producción", machine: "Máquina", module: "Módulo",
  },
};
