import type { Dict } from "./en";

export const es: Dict = {
  brand: {
    descriptor: "Materiales de superficie y productos de acabado para la construcción",
    eyebrow: "La feria internacional de",
  },
  nav: {
    board: "Muestrario",
    partners: "Alianzas",
    materials: "Materiales",
    applications: "Aplicaciones",
    exhibitors: "Expositores",
    experience: "Experiencia",
    visit: "Visitar",
    exhibit: "Exponer",
    register: "Registrarse para visitar",
    search: "Buscar",
    menu: "Menú",
    close: "Cerrar",
    edition: "Edición",
    language: "Idioma",
    skip: "Ir al contenido",
    pro: "Espacio Pro",
  },
  hero: {
    explore: "Explorar materiales",
    exhibit: "Exponer en SURMAT",
    visit: "Visitar SURMAT",
    searchLabel: "Buscar en el universo de materiales",
    searchPlaceholder: "Pruebe “mármol”, “suelo de hotel” o “impermeabilización”",
    matches: "{n} materiales destacados",
    noMatch: "Nada en el universo coincide todavía con “{q}”",
    clear: "Borrar la búsqueda",
    close: "Volver al universo",
    exploreMaterial: "Ver el material",
    findExhibitors: "Encontrar expositores",
    usedIn: "Se usa en",
    format: "Formato",
    hint: "Arrastre para girar el universo. Seleccione una muestra para acercarla.",
    viewSwitch: "Vista del fondo",
    preparing3d: "Preparando el 3D…",
    scroll: "Desplácese para explorar",
    tagline: "Los materiales dan forma a mejores espacios",
  },
  stats: {
    sectors: "Sectores de materiales",
    editions: "Ediciones",
    exhibitors: "Expositores (objetivo)",
    visitors: "Visitantes profesionales (objetivo)",
    hub: "Un centro regional para oportunidades globales",
  },
  home: {
    materialsTitle: "Explore el mundo de los materiales",
    materialsLead: "De la piedra natural a los sistemas de acabado más avanzados — seis sectores que dan forma a la arquitectura moderna.",
    viewAll: "Ver todos los materiales",
    spacesTitle: "Los materiales se convierten en espacios",
    spacesLead: "Cada material de SURMAT termina en un hotel, una vivienda, un hospital o un edificio público. Empiece por el espacio.",
    exploreApps: "Ver todas las aplicaciones",
    industryTitle: "Conozca la industria",
    industryLead: "Fabricantes, proveedores e innovadores que presentan sus colecciones en SURMAT.",
    viewExhibitors: "Ver expositores",
    experienceTitle: "Viva SURMAT",
    experienceLead: "Recorra los seis distritos de la feria y encuentre cada stand por el material que presenta.",
    exploreExperience: "Descubrir la experiencia",
    editionsTitle: "Ediciones de SURMAT",
    editionsLead: "Dos mercados. Un universo de materiales.",
    exploreEdition: "Ver la edición",
    current: "Usted está aquí",
    visitTitle: "Venga a tocar los materiales",
    visitLead: "El registro es gratuito para arquitectos, promotores, constructores, distribuidores y compradores.",
    exhibitTitle: "Sus productos tienen su lugar aquí",
    exhibitLead: "Ponga sus colecciones frente a quienes las prescriben, las compran y las instalan.",
    editionsHeadline: "Dos ediciones. Una plataforma.",
  },
  why: {
    eyebrow: "Por qué exponer",
    title: "Un stand. Cuatro mercados.",
    lead: "SURMAT conecta a los fabricantes de cada superficie de un edificio con quienes construyen el norte y el oeste de África — y abre a empresas de todo el mundo una puerta al continente.",
    markets: [
      {
        id: "dz",
        name: "Argelia",
        kicker: "El mayor mercado del norte de África",
        points: [
          "El país más extenso de África, con unos 47 millones de habitantes",
          "Programas sostenidos de vivienda, infraestructuras, hostelería y edificios públicos",
          "Un puente entre el Magreb, el Mediterráneo y el Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "La puerta de África Occidental",
        points: [
          "Dakar: un centro de negocios estable y dinámico sobre el Atlántico",
          "Miembro de la CEDEAO (15 países) y de la UEMOA (8 países que comparten el franco CFA)",
          "Nuevas ciudades, puertos, hoteles y equipamientos públicos en construcción",
        ],
      },
      {
        id: "africa",
        name: "África",
        kicker: "El próximo auge de la construcción",
        points: [
          "Más de 1.400 millones de habitantes — la población más joven del mundo",
          "La Zona de Libre Comercio Continental Africana reúne a 54 países en un solo mercado",
          "Se espera que la población urbana casi se duplique de aquí a 2050",
        ],
      },
      {
        id: "world",
        name: "El mundo",
        kicker: "Su puerta al continente",
        points: [
          "Pabellones nacionales para Europa, Türkiye, China, India, el Golfo y las Américas",
          "Reúnase en un solo lugar con importadores, distribuidores y agentes de toda África",
          "Una plataforma en nueve idiomas, abierta a expositores de todos los países",
        ],
      },
    ],
    offerTitle: "Lo que obtienen los expositores",
    offerLead: "Todo en SURMAT se construye en torno a un resultado: poner sus productos frente a quienes los prescriben, los compran y los instalan.",
    offer: [
      {
        title: "Compradores cualificados",
        text: "Arquitectos, promotores, constructores, distribuidores y compradores públicos, registrados por perfil y por los materiales que buscan.",
      },
      { title: "Reuniones concertadas de antemano", text: "Los visitantes solicitan citas en su stand antes de la apertura. Usted llega con una agenda, no con una esperanza." },
      { title: "El distrito adecuado", text: "Su stand se sitúa entre los materiales que fabrica — justo donde los prescriptores van a compararlos." },
      { title: "Un showroom todo el año", text: "Su perfil en la biblioteca de materiales de SURMAT sigue trabajando después de la feria, en nueve idiomas." },
      { title: "Un escenario para sus lanzamientos", text: "Presente nuevas colecciones y tecnologías en el programa de conferencias y demostraciones en vivo." },
      { title: "Inteligencia de mercado", text: "Vea qué materiales y aplicaciones despiertan más interés en cada mercado, edición tras edición." },
    ],
    audienceTitle: "A quién conocerá",
    audienceLead: "Solo visitantes profesionales. Cada uno se registra con su perfil y los materiales que busca.",
    participateTitle: "Formas de participar",
    participate: [
      { title: "Stand", text: "Solo suelo o stand modular, desde 9 m², en el distrito de sus materiales." },
      { title: "Pabellón nacional", text: "Exponga bajo la bandera de su país en un pabellón compartido con promoción conjunta." },
      { title: "Patrocinio", text: "Asocie su marca a la feria, al escenario de conferencias o al recorrido del visitante." },
      { title: "Showroom digital", text: "¿Aún no está listo para un stand? Empiece con un perfil en la biblioteca de materiales en línea." },
    ],
    cta: "Solicitar un stand",
    brochure: "Hablar con el equipo comercial",
  },
  universe: {
    title: "Descubra el universo de los materiales",
    lead: "Explore una amplia biblioteca de materiales de superficie y productos de acabado, de la piedra natural a las tecnologías más avanzadas.",
    browse: "Ver todos los materiales",
    explore: "Ver el material",
    exhibitThis: "Exponer este producto",
    prev: "Material anterior",
    next: "Material siguiente",
    taglines: {
      "ceramic-porcelain": "Hecha para durar. Diseñada para ser vista.",
      "natural-engineered-stone": "Belleza natural. Valor duradero.",
      "paints-coatings": "Color, textura y protección.",
      "interior-finishing-systems": "Los sistemas detrás de cada interior.",
      "construction-chemicals": "Lo que sostiene cada superficie.",
      "surface-technologies": "Donde nacen las superficies.",
    },
  },
  explorer: {
    alternatives: "También especificado para esta superficie",
    title: "Materiales para cada espacio",
    lead: "Seleccione un punto del espacio para ver el material — y los expositores que lo fabrican.",
    viewMaterial: "Ver el material",
    findExhibitors: "Encontrar expositores",
    surfaces: { floor: "Suelo", wall: "Paredes", feature: "Pared protagonista", counter: "Mostrador de recepción", ceiling: "Techo" },
  },
  leading: {
    title: "Expositores destacados",
    lead: "Fabricantes que presentan sus colecciones en SURMAT — cada uno con su showroom digital.",
    discover: "Descubrir el expositor",
    featured: "Productos destacados",
  },
  split: {
    visitTitle: "Visitar SURMAT",
    visitLead: "Regístrese ya para asistir a la feria.",
    exhibitTitle: "Exponer en SURMAT",
    exhibitLead: "Presente sus productos a un público profesional cualificado.",
  },
  success: {
    next: "Próximos pasos",
    calendar: "Añadir al calendario",
    visitSteps: [
      "Su acreditación llega por correo antes de la apertura.",
      "Solicite reuniones con los expositores desde sus showrooms.",
      "Lleve su acreditación en el teléfono a la feria.",
    ],
    exhibitSteps: [
      "Un responsable comercial le contacta con opciones de stand y precios.",
      "Confirma su espacio en el distrito de sus materiales.",
      "Su showroom digital se publica en cuanto se confirma su participación.",
    ],
  },
  pro: {
    title: "Espacio Pro",
    lead: "Un espacio privado para expositores y visitantes profesionales, que abre antes de cada edición.",
    soon: "Abre a los expositores confirmados antes de la edición",
    features: [
      "Panel del expositor y gestión de contactos",
      "Edición de su showroom y de su catálogo",
      "Solicitudes de reunión de visitantes profesionales",
      "Documentos, acreditaciones e información práctica",
    ],
    exhibitorCta: "Solicitar un stand",
    visitorCta: "Registrarse para visitar",
    contactCta: "Contactar con el equipo SURMAT",
  },
  contact: {
    title: "Contacto",
    lead: "Díganos quién es y qué necesita. La persona adecuada del equipo SURMAT le responderá.",
    topic: "Asunto",
    topics: {
      exhibitor: "Exponer en SURMAT",
      visitor: "Visitar SURMAT",
      buyer: "Abastecimiento y compras",
      partner: "Colaboración",
      media: "Prensa y medios",
      speaker: "Intervenir en las conferencias",
      other: "Otro",
    },
    message: "Mensaje",
    submit: "Enviar mensaje",
    successTitle: "Mensaje enviado.",
    successLead: "Responderemos a {email}.",
  },
  legal: {
    title: "Aviso legal",
    publisher: "Editor",
    pending: "Los datos del editor se publicarán aquí antes del lanzamiento.",
    hosting: "Alojamiento",
    hostingText: "Este sitio está alojado por Vercel Inc., Estados Unidos.",
    ip: "Propiedad intelectual",
    ipText: "El nombre SURMAT, los contenidos y el diseño de este sitio están protegidos. Los nombres, logotipos e imágenes de producto de los expositores pertenecen a sus propietarios y se muestran con su autorización.",
  },
  privacy: {
    title: "Privacidad",
    lead: "Qué recoge este sitio, por qué y cómo contactarnos al respecto.",
    sections: [
      {
        title: "Qué recogemos",
        text: "Los datos que introduce en nuestros formularios — nombre, correo profesional, empresa, cargo, teléfono, país y sus respuestas — junto con la página y la campaña que le trajeron a SURMAT.",
      },
      {
        title: "Para qué",
        text: "Para registrar su visita, tramitar su solicitud de expositor o responder a su mensaje. Solo le contactamos sobre la edición si marca la casilla de consentimiento.",
      },
      {
        title: "Analítica",
        text: "Registramos interacciones anónimas — materiales vistos, búsquedas, clics en llamadas a la acción — para mejorar la plataforma y saber qué materiales despiertan interés. No se vinculan a su nombre.",
      },
      {
        title: "Cookies",
        text: "Guardamos dos cookies de preferencias, su edición y su idioma, durante un año. Este sitio no utiliza cookies publicitarias.",
      },
      { title: "Sus derechos", text: "Puede pedir en cualquier momento ver, corregir o eliminar sus datos escribiendo al equipo SURMAT." },
    ],
  },
  event: {
    bandTitle: "Verlo, tocarlo, comprarlo — en persona",
    bar: "Feria profesional internacional",
    bookStand: "Reservar un stand",
    freeVisit: "Registro gratuito",
    visual: "Visualización",
    eyebrow: "La feria",
    title: "Donde la industria del acabado se encuentra cara a cara",
    lead: "SURMAT es un evento profesional en vivo, no un catálogo. Los expositores presentan sus productos en el stand, compradores y prescriptores vienen a abastecerse y los proyectos se negocian en la mesa — en Orán y en Dakar.",
    pillars: [
      {
        title: "Zona de exposición",
        text: "Cientos de stands organizados por distrito de materiales: tocar, comparar y encontrar cada producto en una sola visita.",
      },
      { title: "Networking B2B", text: "Reuniones concertadas entre expositores, distribuidores, promotores, arquitectos y compradores públicos." },
      {
        title: "Conferencias y presentación de proyectos",
        text: "Arquitectos, promotores y organismos públicos presentan los proyectos que necesitarán estos materiales.",
      },
      {
        title: "Demostraciones y lanzamientos",
        text: "Demostraciones de instalación, maquinaria en funcionamiento y nuevas colecciones presentadas en la feria.",
      },
    ],
    exhibitors: "{n} expositores",
    visitors: "{n} visitantes profesionales",
    visitPoints: [
      "Entrada gratuita para profesionales",
      "Todos los productos de acabado en una visita",
      "Conozca a fabricantes y distribuidores en persona",
    ],
    exhibitPoints: [
      "Conozca compradores y prescriptores cualificados",
      "Reuniones B2B concertadas en su stand",
      "Lance sus productos en los mercados africanos",
    ],
  },
  scope: {
    statDistricts: "Distritos",
    statFamilies: "Familias de productos",
    district: "Distrito",
    bookHere: "Reservar un stand en este distrito",
    eyebrow: "Alcance de la feria",
    title: "Nueve distritos. Toda la industria del acabado.",
    lead: "La biblioteca de materiales muestra ejemplos. La feria se organiza en nueve distritos que cubren todo lo que reviste, termina, protege o equipa un edificio. Elija un distrito para ver quién expone allí.",
    core: "Sector principal",
    adjacent: "También bienvenidos",
    families: "{n} familias",
    missing: "¿No ve su producto?",
    missingText: "Si reviste, termina, protege o equipa un edificio, tiene su lugar en SURMAT. Díganos qué fabrica y le ubicaremos en el distrito adecuado.",
    cta: "Proponer mi producto",
    count: "{m} materiales documentados · {f} familias de productos admitidas en la feria",
  },
  partners: {
    eyebrow: "Oportunidad de alianza",
    title: "Lleve SURMAT a su país",
    lead: "SURMAT está hecho para viajar. Agencias de eventos, asociaciones sectoriales y cámaras de comercio pueden llevar el formato a su mercado, con nuestra marca, plataforma, red de expositores y método detrás.",
    cta: "Solicitar ser socio",
    mapLabel: "Argelia y Senegal hoy — su mercado mañana",
    formatsTitle: "Tres formas de asociarse",
    formats: [
      {
        title: "Edición bajo licencia",
        text: "Organice SURMAT en su país con una licencia de franquicia.",
        points: [
          "Uso completo de la marca y el formato SURMAT",
          "Plano de nueve distritos y taxonomía de materiales",
          "Su edición en esta plataforma, en nueve idiomas",
        ],
      },
      {
        title: "Edición coorganizada",
        text: "Lancemos juntos una nueva edición, compartiendo inversión y resultados.",
        points: [
          "Plan de negocio y presupuesto conjuntos",
          "Equipo comercial y expositores internacionales compartidos",
          "Apoyo operativo de SURMAT in situ",
        ],
      },
      {
        title: "Agente y pabellón nacional",
        text: "Represente a SURMAT en su país y lleve sus empresas a nuestras ediciones.",
        points: [
          "Comisión por los stands que venda",
          "Organización del pabellón nacional de su país",
          "Delegaciones de compradores a Orán y Dakar",
        ],
      },
    ],
    weBringTitle: "Lo que aporta SURMAT",
    weBring: [
      "Una marca y un formato de feria consolidados",
      "La plataforma digital: biblioteca de materiales, showrooms de expositores, registro",
      "Expositores internacionales y programa de compradores invitados",
      "Método comercial, modelo de precios y formación",
      "Kit de marketing, contenidos y campañas en nueve idiomas",
      "Manuales operativos y apoyo in situ",
    ],
    youBringTitle: "Lo que aporta usted",
    youBring: [
      "Conocimiento de su mercado de la construcción",
      "Relaciones con recintos, autoridades y asociaciones",
      "Un equipo local de ventas y marketing",
      "Red logística y de proveedores",
      "Compromiso con los estándares de calidad SURMAT",
    ],
    stepsTitle: "Cómo funciona",
    steps: [
      { title: "Solicitud", text: "Cuéntenos sobre su organización y su mercado." },
      { title: "Estudio de mercado", text: "Evaluamos juntos la oportunidad." },
      { title: "Acuerdo", text: "Elegimos el modelo de alianza y firmamos." },
      { title: "Lanzamiento", text: "Su edición SURMAT se publica en la plataforma." },
    ],
    who: "Para organizadores de eventos, agencias feriales, asociaciones sectoriales, cámaras de comercio e inversores de África, Oriente Medio y otros mercados.",
    applyTitle: "Iniciemos la conversación",
    applyLead: "Comparta algunos datos y el equipo de alianzas de SURMAT le responderá en cinco días hábiles.",
    homeTitle: "¿Su país es el siguiente?",
    homeLead: "Lleve SURMAT a su mercado como edición bajo licencia o coorganizada.",
  },
  systems: {
    eyebrow: "Cómo se construye",
    title: "Cada sistema, capa a capa",
    lead: "Detrás de cada superficie hay un sistema de productos: paneles, subestructuras, aislamientos, membranas, adhesivos, recrecidos, placas y acabados, y las máquinas que los fabrican. Elija un sistema y luego una capa para ver qué es, su especificación típica y dónde exponen sus fabricantes.",
    onSite: "En obra",
    section: "Sección técnica",
    process: "Línea de producción",
    layers: "capas",
    steps: "estaciones",
    outside: "Exterior",
    inside: "Interior",
    top: "Arriba",
    district: "Distrito",
    structure: "Estructura del edificio — no es una categoría de producto",
    note: "Especificaciones típicas a título ilustrativo. Consulte las fichas técnicas de los fabricantes y la normativa local.",
  },
  board: {
    eyebrow: "Muestrario y estudio de renders",
    title: "De la muestra al espacio",
    lead: "Cada familia de productos de la feria, como la especifica un arquitecto: muestras reales en el panel, la familia en uso con sus puntos técnicos y el distrito donde exponen sus fabricantes.",
    sampleBoard: "Panel de materiales",
    exhibitedIn: "Se expone en el",
    district: "Distrito",
    palette: "La paleta",
    synthTitle: "Un edificio, todos los distritos",
    synthLead: "Doce muestras, un proyecto: señale una muestra para ver dónde se usa — fachada, terraza, oficina, vestíbulo, baño.",
    open: "Abrir el muestrario",
    pageTitle: "El muestrario",
    pageLead: "Una guía de especificación de la feria a la obra: cada familia de productos con sus muestras, su uso y sus puntos técnicos.",
  },
  sector: {
    materials: "Materiales de este sector",
    exhibitors: "Expositores de este distrito",
    district: "Distrito",
  },
  material: {
    sector: "Sector",
    finishes: "Acabados",
    applications: "Aplicaciones",
    formats: "Formatos",
    spec: "Gama habitual",
    exhibitors: "Expositores que presentan este material",
    noExhibitors: "Ningún expositor ha confirmado aún este material. El suyo podría ser el primero.",
    related: "Materiales relacionados",
    manufacturerQ: "¿Fabrica usted {material}?",
    usedIn: "Se usa en:",
  },
  catalogue: {
    title: "Biblioteca de materiales",
    lead: "Todos los materiales presentados en SURMAT, organizados por sector. Cada uno lleva a las empresas que lo fabrican.",
    all: "Todos los sectores",
    search: "Filtrar materiales",
    noResults: "Ningún material coincide con “{q}”. Pruebe una palabra más amplia como “piedra” o “baldosa”.",
    count: "{n} materiales",
  },
  apps: {
    allSpaces: "Todos los espacios",
    stats: "{m} materiales · {e} expositores",
    title: "Aplicaciones",
    lead: "Empiece por el espacio que está construyendo y conozca a los expositores que suministran cada una de sus superficies.",
    materialsUsed: "Materiales de este espacio",
    suppliers: "Expositores que suministran estos materiales",
  },
  exhibitors: {
    title: "Expositores",
    lead: "Explore las empresas presentes en SURMAT según los materiales que fabrican.",
    sample: "Perfil de ejemplo",
    sampleNote: "Los perfiles de ejemplo muestran cómo se verán los showrooms de los expositores. Los expositores confirmados se publican a medida que firman.",
    district: "Distrito",
    stand: "Stand",
    requestMeeting: "Solicitar una reunión",
    visitStand: "Encontrar el stand",
    products: "Muro de productos",
    materials: "Materiales",
    markets: "Mercados",
    founded: "Fundada en",
    all: "Todos",
    empty: "Todavía no hay expositores en este sector.",
  },
  experience: {
    zones: {
      conference: "Sala de conferencias",
      conferenceSub: "Charlas, mesas redondas, presentación de proyectos",
      b2b: "Salón de reuniones B2B",
      b2bSub: "Reuniones concertadas con compradores",
      demo: "Escenario de demostraciones",
      demoSub: "Demos de instalación y maquinaria",
      aisle: "Pasillo principal",
      pavilions: "Pabellones nacionales",
      lounge: "Lounge y cafetería",
      registration: "Acreditación",
      entrance: "Entrada principal",
    },
    legendTaken: "Stand reservado",
    title: "La experiencia SURMAT",
    lead: "Nueve distritos, una sala de conferencias, un salón B2B y un escenario de demostraciones. Recorra el plano, encuentre un stand, reserve el suyo.",
    mapTitle: "Plano de la feria",
    mapHint: "Seleccione un stand para ver quién expone.",
    open: "Ver el stand",
    available: "Stand disponible",
    availableLead: "Este stand está disponible para reservar.",
    book: "Reservar este stand",
    teaserTitle: "Más que una feria",
    teaserLead: "Un recorrido inmersivo por los materiales, las aplicaciones, la innovación y la experiencia del sector.",
    central: "Espacio central",
    branches: [
      "Plano de la feria",
      "Distritos de materiales",
      "Conferencias",
      "Demostraciones de producto",
      "Networking",
    ],
  },
  visit: {
    title: "Visitar SURMAT",
    lead: "Cuatro días con los fabricantes de cada superficie de un edificio. El registro es gratuito para profesionales.",
    who: "Quién visita",
    profiles: {
      architect: "Arquitecto o interiorista",
      developer: "Promotor o propiedad",
      contractor: "Constructor o instalador",
      distributor: "Distribuidor o minorista",
      buyer: "Comprador o compras",
      manufacturer: "Fabricante",
      other: "Otro profesional",
    },
    formTitle: "Registrarse para visitar",
    profile: "Su perfil",
    interests: "Materiales que busca",
    submit: "Registrarse para visitar",
    successTitle: "Ya está registrado.",
    successLead: "Su acreditación se enviará a {email} antes de la apertura de la feria.",
    meetingWith: "Solicitud de reunión con {name}",
  },
  exhibit: {
    title: "Exponer en SURMAT",
    lead: "Sus productos tienen su lugar aquí.",
    why: [
      "Arquitectos, promotores, constructores y distribuidores de Argelia, Senegal y toda África",
      "Su stand está en el distrito de sus materiales, donde los prescriptores vienen a buscar",
      "Sus productos siguen en línea todo el año en la biblioteca de materiales de SURMAT, en nueve idiomas",
    ],
    steps: ["Materiales", "Empresa", "Catálogo", "Espacio", "Contacto"],
    manufacture: "¿Qué fabrica usted?",
    companyTitle: "Háblenos de su empresa",
    portfolioTitle: "¿Qué va a presentar?",
    spaceTitle: "¿Cuánto espacio necesita?",
    contactTitle: "¿A quién debemos contactar?",
    companyName: "Nombre de la empresa",
    website: "Sitio web",
    country: "País",
    families: "Familias de productos",
    brands: "Marcas",
    machinery: "Haremos demostraciones de maquinaria",
    demo: "Queremos una zona de demostración en vivo",
    meetingRoom: "Necesitamos una zona de reuniones privada",
    description: "Productos que prevé presentar",
    recommended: "Según su catálogo, SURMAT recomienda {min}–{max} m².",
    requested: "Superficie solicitada (m²)",
    edition: "Edición",
    back: "Atrás",
    next: "Continuar",
    submit: "Enviar la solicitud",
    successTitle: "Sus productos tienen su lugar en SURMAT.",
    successLead: "Un responsable comercial de SURMAT contactará con {email} con opciones de stand en el distrito {sector}.",
    pickOne: "Seleccione al menos un sector para continuar.",
  },
  form: {
    name: "Nombre completo",
    role: "Cargo",
    company: "Empresa",
    email: "Correo profesional",
    phone: "Teléfono",
    country: "País",
    required: "Obligatorio",
    invalidEmail: "Introduzca una dirección como nombre@empresa.com.",
    error: "No se ha podido enviar el formulario. Compruebe su conexión e inténtelo de nuevo.",
    sending: "Enviando…",
    consent: "SURMAT puede contactarme sobre esta edición.",
  },
  cta: {
    dialogTitle: "Exponer en SURMAT",
    dialogLead: "Sus productos tienen su lugar aquí.",
    apply: "Solicitar un stand",
    close: "Cerrar",
  },
  edition: {
    datesTBA: "Fechas por anunciar",
    venueTBA: "Sede por anunciar",
    switchTo: "Cambiar a {name}",
  },
  search: {
    title: "Buscar en SURMAT",
    placeholder: "Material, espacio o empresa — p. ej. “suelo de mármol hotel”",
    materials: "Materiales",
    sectors: "Sectores",
    applications: "Aplicaciones",
    exhibitors: "Expositores",
    empty: "Escriba un material, un espacio o una empresa.",
    none: "Sin resultados para “{q}”. Pruebe con un solo material, como “porcelánico”.",
    popularMaterials: "Materiales populares",
    popularApplications: "Aplicaciones populares",
    featuredExhibitors: "Expositores destacados",
  },
  footer: {
    tagline: "La feria internacional de materiales de superficie y productos de acabado para la construcción.",
    rights: "© {year} SURMAT. Todos los derechos reservados.",
    platform: "Plataforma",
    editions: "Ediciones",
    languages: "Idiomas",
    legal: "Aviso legal",
    privacy: "Privacidad",
    contact: "Contacto",
  },
  common: { back: "Atrás", all: "Todos", learnMore: "Más información", of: "de", explore: "Explorar" },
  vocab: {
    matt: "Mate", polished: "Pulido", honed: "Apomazado", textured: "Texturizado", antiSlip: "Antideslizante",
    brushed: "Cepillado", glossy: "Brillo", satin: "Satinado", leather: "Envejecido", flamed: "Flameado",
    bushHammered: "Abujardado", metallic: "Metálico", velvet: "Aterciopelado", raw: "Natural",
    tile: "Baldosa", largeFormat: "Gran formato", slab: "Placa", mosaic: "Mosaico", block: "Bloque",
    board: "Placa", panel: "Panel", roll: "Rollo", liquid: "Líquido", powder: "Polvo", paste: "Pasta",
    cartridge: "Cartucho", line: "Línea de producción", machine: "Máquina", module: "Módulo",
  },
};
