import type { Dict } from "./en";

export const fr: Dict = {
  brand: {
    descriptor: "Matériaux de surface & produits de finition du bâtiment",
    eyebrow: "Le salon international des",
  },
  nav: {
    partners: "Partenariats",
    materials: "Matériaux",
    applications: "Applications",
    exhibitors: "Exposants",
    experience: "Expérience",
    visit: "Visiter",
    exhibit: "Exposer",
    register: "S’inscrire pour visiter",
    search: "Rechercher",
    menu: "Menu",
    close: "Fermer",
    edition: "Édition",
    language: "Langue",
    skip: "Aller au contenu",
    pro: "Espace Pro",
  },
  hero: {
    explore: "Explorer les matériaux",
    exhibit: "Exposer au SURMAT",
    visit: "Visiter le SURMAT",
    searchLabel: "Rechercher dans l’univers des matériaux",
    searchPlaceholder: "Essayez « marbre », « sol d’hôtel » ou « étanchéité »",
    matches: "{n} matériaux mis en avant",
    noMatch: "Rien ne correspond encore à « {q} »",
    clear: "Effacer la recherche",
    close: "Retour à l’univers",
    exploreMaterial: "Découvrir le matériau",
    findExhibitors: "Trouver des exposants",
    usedIn: "Utilisé dans",
    format: "Format",
    hint: "Faites glisser pour tourner l’univers. Sélectionnez un échantillon pour l’approcher.",
    scroll: "Défiler pour explorer",
    tagline: "Les matériaux façonnent de meilleurs espaces",
  },
  stats: {
    sectors: "Secteurs de matériaux",
    editions: "Éditions",
    exhibitors: "Exposants (objectif)",
    visitors: "Visiteurs professionnels (objectif)",
    hub: "Un hub régional pour des opportunités mondiales",
  },
  home: {
    materialsTitle: "Explorez l’univers des matériaux",
    materialsLead: "De la pierre naturelle aux systèmes de finition avancés — six secteurs qui façonnent l’architecture moderne.",
    viewAll: "Tous les matériaux",
    spacesTitle: "Les matériaux deviennent des espaces",
    spacesLead: "Chaque matériau du SURMAT finit dans un hôtel, un logement, un hôpital ou un bâtiment public. Partez de l’espace.",
    exploreApps: "Toutes les applications",
    industryTitle: "Rencontrez l’industrie",
    industryLead: "Fabricants, fournisseurs et innovateurs présentent leurs collections au SURMAT.",
    viewExhibitors: "Voir les exposants",
    experienceTitle: "Vivez le SURMAT",
    experienceLead: "Parcourez les six districts du salon et trouvez chaque stand par le matériau qu’il présente.",
    exploreExperience: "Découvrir l’expérience",
    editionsTitle: "Éditions SURMAT",
    editionsLead: "Deux marchés. Un seul univers de matériaux.",
    exploreEdition: "Découvrir l’édition",
    current: "Vous êtes ici",
    visitTitle: "Venez toucher les matériaux",
    visitLead: "Inscription gratuite pour les architectes, promoteurs, entreprises, distributeurs et acheteurs.",
    exhibitTitle: "Vos produits ont leur place ici",
    exhibitLead: "Présentez vos collections à ceux qui les prescrivent, les achètent et les posent.",
    editionsHeadline: "Deux éditions. Une plateforme.",
  },
  why: {
    eyebrow: "Pourquoi exposer",
    title: "Un stand. Quatre marchés.",
    lead: "Le SURMAT relie les fabricants de chaque surface d’un bâtiment à ceux qui construisent l’Afrique du Nord et de l’Ouest — et ouvre aux entreprises du monde entier une porte sur le continent.",
    markets: [
      {
        id: "dz",
        name: "Algérie",
        kicker: "Le premier marché d’Afrique du Nord",
        points: [
          "Le plus grand pays d’Afrique par sa superficie, environ 47 millions d’habitants",
          "Des programmes soutenus de logement, d’infrastructures, d’hôtellerie et d’équipements publics",
          "Un pont entre le Maghreb, la Méditerranée et le Sahel",
        ],
      },
      {
        id: "sn",
        name: "Sénégal",
        kicker: "La porte de l’Afrique de l’Ouest",
        points: [
          "Dakar : un pôle d’affaires stable et dynamique sur l’Atlantique",
          "Membre de la CEDEAO (15 pays) et de l’UEMOA (8 pays partageant le franc CFA)",
          "Villes nouvelles, ports, hôtels et équipements publics en construction",
        ],
      },
      {
        id: "africa",
        name: "Afrique",
        kicker: "Le prochain boom de la construction",
        points: [
          "Plus de 1,4 milliard d’habitants — la population la plus jeune du monde",
          "La Zone de libre-échange continentale africaine réunit 54 pays en un seul marché",
          "Une population urbaine appelée à presque doubler d’ici 2050",
        ],
      },
      {
        id: "world",
        name: "Le monde",
        kicker: "Votre porte vers le continent",
        points: [
          "Des pavillons nationaux pour l’Europe, la Türkiye, la Chine, l’Inde, le Golfe et les Amériques",
          "Rencontrez importateurs, distributeurs et agents de toute l’Afrique en un seul lieu",
          "Une plateforme en neuf langues, ouverte aux exposants de tous les pays",
        ],
      },
    ],
    offerTitle: "Ce que reçoivent les exposants",
    offerLead: "Tout au SURMAT vise un seul résultat : placer vos produits devant ceux qui les prescrivent, les achètent et les posent.",
    offer: [
      {
        title: "Des acheteurs qualifiés",
        text: "Architectes, promoteurs, entreprises, distributeurs et acheteurs publics, inscrits par profil et par matériaux recherchés.",
      },
      {
        title: "Des rendez-vous planifiés",
        text: "Les visiteurs demandent un rendez-vous sur votre stand avant l’ouverture. Vous arrivez avec un agenda, pas un espoir.",
      },
      { title: "Le bon district", text: "Votre stand se trouve parmi les matériaux que vous fabriquez — là où les prescripteurs viennent les comparer." },
      { title: "Une vitrine à l’année", text: "Votre profil dans la matériauthèque SURMAT continue de travailler après le salon, en neuf langues." },
      { title: "Une scène pour vos lancements", text: "Présentez nouvelles collections et technologies dans le programme de conférences et de démonstrations." },
      { title: "Une veille de marché", text: "Voyez quels matériaux et applications suscitent le plus d’intérêt sur chaque marché, édition après édition." },
    ],
    audienceTitle: "Qui vous rencontrerez",
    audienceLead: "Uniquement des visiteurs professionnels. Chacun s’inscrit avec son profil et les matériaux qu’il recherche.",
    participateTitle: "Façons de participer",
    participate: [
      { title: "Stand", text: "Surface nue ou stand équipé, dès 9 m², dans le district de vos matériaux." },
      { title: "Pavillon national", text: "Exposez sous le drapeau de votre pays avec un pavillon partagé et une promotion commune." },
      { title: "Sponsoring", text: "Associez votre marque au salon, à la scène de conférences ou au parcours visiteur." },
      { title: "Vitrine digitale", text: "Pas encore prêt pour un stand ? Commencez par un profil dans la matériauthèque en ligne." },
    ],
    cta: "Demander un stand",
    brochure: "Parler à notre équipe commerciale",
  },
  universe: {
    title: "Découvrez l’univers des matériaux",
    lead: "Explorez une riche bibliothèque de matériaux de surface et de produits de finition, de la pierre naturelle aux technologies les plus avancées.",
    browse: "Parcourir tous les matériaux",
    explore: "Découvrir le matériau",
    exhibitThis: "Exposer ce produit",
    prev: "Matériau précédent",
    next: "Matériau suivant",
    taglines: {
      "ceramic-porcelain": "Conçue pour durer. Pensée pour être vue.",
      "natural-engineered-stone": "Beauté naturelle. Valeur durable.",
      "paints-coatings": "Couleur, texture et protection.",
      "interior-finishing-systems": "Les systèmes derrière chaque intérieur.",
      "construction-chemicals": "Ce qui tient chaque surface en place.",
      "surface-technologies": "Là où naissent les surfaces.",
    },
  },
  explorer: {
    alternatives: "Aussi prescrit pour cette surface",
    title: "Des matériaux pour chaque espace",
    lead: "Sélectionnez un point dans l’espace pour découvrir le matériau — et les exposants qui le fabriquent.",
    viewMaterial: "Voir le matériau",
    findExhibitors: "Trouver les exposants",
    surfaces: { floor: "Sol", wall: "Murs", feature: "Mur signature", counter: "Comptoir d’accueil", ceiling: "Plafond" },
  },
  leading: {
    title: "Exposants de référence",
    lead: "Des fabricants qui présentent leurs collections au SURMAT — chacun avec son showroom digital.",
    discover: "Découvrir l’exposant",
    featured: "Produits phares",
  },
  split: {
    visitTitle: "Visiter le SURMAT",
    visitLead: "Inscrivez-vous dès maintenant pour participer au salon.",
    exhibitTitle: "Exposer au SURMAT",
    exhibitLead: "Présentez vos produits à un public qualifié de professionnels.",
  },
  success: {
    next: "Et maintenant",
    calendar: "Ajouter à l’agenda",
    visitSteps: [
      "Votre badge arrive par e-mail avant l’ouverture.",
      "Demandez des rendez-vous aux exposants depuis leurs showrooms.",
      "Présentez votre badge sur téléphone à l’entrée.",
    ],
    exhibitSteps: [
      "Un responsable commercial vous contacte avec les options de stand et les tarifs.",
      "Vous confirmez votre surface dans le district de vos matériaux.",
      "Votre showroom digital est publié dès que votre participation est confirmée.",
    ],
  },
  pro: {
    title: "Espace Pro",
    lead: "Un espace privé pour les exposants et les visiteurs professionnels, ouvert avant chaque édition.",
    soon: "Ouverture aux exposants confirmés avant l’édition",
    features: [
      "Tableau de bord exposant et gestion des contacts",
      "Modification de votre showroom et de votre catalogue",
      "Demandes de rendez-vous des visiteurs professionnels",
      "Documents, badges et informations pratiques",
    ],
    exhibitorCta: "Demander un stand",
    visitorCta: "S’inscrire pour visiter",
    contactCta: "Contacter l’équipe SURMAT",
  },
  contact: {
    title: "Contact",
    lead: "Dites-nous qui vous êtes et ce dont vous avez besoin. Le bon interlocuteur de l’équipe SURMAT vous répondra.",
    topic: "Objet",
    topics: {
      exhibitor: "Exposer au SURMAT",
      visitor: "Visiter le SURMAT",
      buyer: "Sourcing et achats",
      partner: "Partenariat",
      media: "Presse et médias",
      speaker: "Intervenir aux conférences",
      other: "Autre",
    },
    message: "Message",
    submit: "Envoyer le message",
    successTitle: "Message envoyé.",
    successLead: "Nous répondrons à {email}.",
  },
  legal: {
    title: "Mentions légales",
    publisher: "Éditeur",
    pending: "Les informations de l’éditeur seront publiées ici avant le lancement.",
    hosting: "Hébergement",
    hostingText: "Ce site est hébergé par Vercel Inc., États-Unis.",
    ip: "Propriété intellectuelle",
    ipText: "Le nom SURMAT, les contenus et le design de ce site sont protégés. Les noms, logos et visuels produits des exposants appartiennent à leurs propriétaires respectifs et sont présentés avec leur accord.",
  },
  privacy: {
    title: "Confidentialité",
    lead: "Ce que ce site collecte, pourquoi, et comment nous contacter à ce sujet.",
    sections: [
      {
        title: "Ce que nous collectons",
        text: "Les informations saisies dans nos formulaires — nom, e-mail professionnel, entreprise, fonction, téléphone, pays et vos réponses — ainsi que la page et la campagne qui vous ont amené au SURMAT.",
      },
      {
        title: "Pourquoi",
        text: "Pour enregistrer votre visite, traiter votre demande d’exposition ou répondre à votre message. Nous vous contactons au sujet de l’édition uniquement si vous cochez la case de consentement.",
      },
      {
        title: "Mesure d’audience",
        text: "Nous enregistrons des interactions anonymes — matériaux consultés, recherches, clics sur les appels à l’action — pour améliorer la plateforme et comprendre quels matériaux suscitent l’intérêt. Elles ne sont pas liées à votre nom.",
      },
      {
        title: "Cookies",
        text: "Nous conservons deux cookies de préférence, votre édition et votre langue, pendant un an. Ce site n’utilise pas de cookies publicitaires.",
      },
      {
        title: "Vos droits",
        text: "Vous pouvez demander à tout moment l’accès, la rectification ou la suppression de vos données en écrivant à l’équipe SURMAT.",
      },
    ],
  },
  event: {
    bandTitle: "Voir, toucher, sourcer — en personne",
    bar: "Salon professionnel international",
    bookStand: "Réserver un stand",
    freeVisit: "Inscription gratuite",
    visual: "Visualisation",
    eyebrow: "Le salon",
    title: "Là où la filière de la finition se rencontre en face à face",
    lead: "SURMAT est un événement professionnel vivant, pas un catalogue. Les exposants présentent leurs produits sur stand, acheteurs et prescripteurs viennent sourcer, et les projets se discutent autour de la table — à Oran et à Dakar.",
    pillars: [
      {
        title: "Surface d’exposition",
        text: "Des centaines de stands organisés par quartier de matériaux — toucher, comparer et sourcer chaque produit en une seule visite.",
      },
      { title: "Rencontres B2B", text: "Rendez-vous planifiés entre exposants, distributeurs, promoteurs, architectes et acheteurs publics." },
      {
        title: "Conférences & présentations de projets",
        text: "Architectes, promoteurs et maîtres d’ouvrage publics présentent les projets qui auront besoin de ces matériaux.",
      },
      { title: "Démonstrations & lancements", text: "Démonstrations de pose, machines en fonctionnement et nouvelles collections dévoilées sur le salon." },
    ],
    exhibitors: "{n} exposants",
    visitors: "{n} visiteurs professionnels",
    visitPoints: [
      "Entrée gratuite pour les professionnels",
      "Sourcer tous les produits de finition en une visite",
      "Rencontrer fabricants et distributeurs en direct",
    ],
    exhibitPoints: [
      "Rencontrer acheteurs et prescripteurs qualifiés",
      "Rendez-vous B2B planifiés sur votre stand",
      "Lancer vos produits sur les marchés africains",
    ],
  },
  scope: {
    statDistricts: "Quartiers",
    statFamilies: "Familles de produits",
    district: "Quartier",
    bookHere: "Réserver un stand dans ce quartier",
    eyebrow: "Périmètre du salon",
    title: "Neuf quartiers. Toute la filière de la finition.",
    lead: "La matériauthèque montre des exemples. Le salon est organisé en neuf quartiers qui couvrent tout ce qui revêt, finit, protège ou équipe un bâtiment. Choisissez un quartier pour voir qui y expose.",
    core: "Secteur principal",
    adjacent: "Également bienvenus",
    families: "{n} familles",
    missing: "Votre produit n’apparaît pas ?",
    missingText: "S’il revêt, finit, protège ou équipe un bâtiment, il a sa place à SURMAT. Dites-nous ce que vous fabriquez et nous vous placerons dans le bon quartier.",
    cta: "Proposer mon produit",
    count: "{m} matériaux documentés · {f} familles de produits accueillies au salon",
  },
  partners: {
    eyebrow: "Opportunité de partenariat",
    title: "Organisez SURMAT dans votre pays",
    lead: "SURMAT est conçu pour voyager. Agences événementielles, fédérations professionnelles et chambres de commerce peuvent déployer le format sur leur marché — avec notre marque, notre plateforme, notre réseau d’exposants et notre méthode.",
    cta: "Devenir partenaire",
    mapLabel: "L’Algérie et le Sénégal aujourd’hui — votre marché demain",
    formatsTitle: "Trois façons de s’associer",
    formats: [
      {
        title: "Édition sous licence",
        text: "Organisez SURMAT dans votre pays sous licence de franchise.",
        points: [
          "Utilisation complète de la marque et du format SURMAT",
          "Plan en neuf quartiers et taxonomie des matériaux",
          "Votre édition sur cette plateforme, en neuf langues",
        ],
      },
      {
        title: "Édition co-organisée",
        text: "Lancez ensemble une nouvelle édition, en partageant investissement et résultats.",
        points: [
          "Business plan et budget communs",
          "Équipe commerciale et exposants internationaux partagés",
          "Appui opérationnel SURMAT sur site",
        ],
      },
      {
        title: "Agent & pavillon national",
        text: "Représentez SURMAT dans votre pays et amenez vos entreprises à nos éditions.",
        points: [
          "Commission sur les stands vendus",
          "Organisation du pavillon national de votre pays",
          "Délégations d’acheteurs à Oran et Dakar",
        ],
      },
    ],
    weBringTitle: "Ce qu’apporte SURMAT",
    weBring: [
      "Une marque et un format de salon établis",
      "La plateforme digitale : matériauthèque, showrooms exposants, inscriptions",
      "Des exposants internationaux et un programme d’acheteurs invités",
      "Méthode commerciale, modèle tarifaire et formation",
      "Kit marketing, contenus et campagnes en neuf langues",
      "Manuels opérationnels et accompagnement sur site",
    ],
    youBringTitle: "Ce que vous apportez",
    youBring: [
      "La connaissance de votre marché de la construction",
      "Vos relations avec les sites, les autorités et les fédérations",
      "Une équipe commerciale et marketing locale",
      "Un réseau logistique et de prestataires",
      "L’engagement sur les standards de qualité SURMAT",
    ],
    stepsTitle: "Comment ça marche",
    steps: [
      { title: "Candidature", text: "Présentez votre organisation et votre marché." },
      { title: "Étude de marché", text: "Nous évaluons ensemble l’opportunité." },
      { title: "Accord", text: "Nous choisissons le modèle de partenariat et signons." },
      { title: "Lancement", text: "Votre édition SURMAT est en ligne sur la plateforme." },
    ],
    who: "Pour les organisateurs d’événements, agences de salons, fédérations professionnelles, chambres de commerce et investisseurs en Afrique, au Moyen-Orient et au-delà.",
    applyTitle: "Engager la discussion",
    applyLead: "Donnez-nous quelques informations : l’équipe partenariats SURMAT vous répondra sous cinq jours ouvrés.",
    homeTitle: "Votre pays, la prochaine étape ?",
    homeLead: "Déployez SURMAT sur votre marché en édition sous licence ou co-organisée.",
  },
  systems: {
    eyebrow: "Comment c’est construit",
    title: "Chaque système, couche par couche",
    lead: "Derrière chaque surface, un système de produits : panneaux, ossatures, isolants, membranes, colles, chapes, plaques et finitions — et les machines qui les fabriquent. Choisissez un système puis une couche pour voir ce que c’est, sa spécification type et où exposent ses fabricants.",
    onSite: "Sur chantier",
    section: "Coupe technique",
    process: "Ligne de production",
    layers: "couches",
    steps: "postes",
    outside: "Extérieur",
    inside: "Intérieur",
    top: "Dessus",
    district: "Quartier",
    structure: "Structure du bâtiment — hors catégorie de produits",
    note: "Spécifications types à titre indicatif. Consultez les fiches techniques des fabricants et les normes locales.",
  },
  sector: {
    materials: "Matériaux de ce secteur",
    exhibitors: "Exposants de ce district",
    district: "District",
  },
  material: {
    sector: "Secteur",
    finishes: "Finitions",
    applications: "Applications",
    formats: "Formats",
    spec: "Gamme type",
    exhibitors: "Exposants présentant ce matériau",
    noExhibitors: "Aucun exposant n’a encore confirmé ce matériau. Le vôtre pourrait être le premier.",
    related: "Matériaux associés",
    manufacturerQ: "Vous fabriquez : {material} ?",
    usedIn: "Utilisé en :",
  },
  catalogue: {
    title: "Matériauthèque",
    lead: "Tous les matériaux présentés au SURMAT, classés par secteur. Chacun mène aux entreprises qui le fabriquent.",
    all: "Tous les secteurs",
    search: "Filtrer les matériaux",
    noResults: "Aucun matériau ne correspond à « {q} ». Essayez un mot plus large comme « pierre » ou « carreau ».",
    count: "{n} matériaux",
  },
  apps: {
    allSpaces: "Tous les espaces",
    stats: "{m} matériaux · {e} exposants",
    title: "Applications",
    lead: "Partez de l’espace que vous construisez et rencontrez les exposants qui en fournissent chaque surface.",
    materialsUsed: "Matériaux de cet espace",
    suppliers: "Exposants fournissant ces matériaux",
  },
  exhibitors: {
    title: "Exposants",
    lead: "Parcourez les entreprises présentes au SURMAT selon les matériaux qu’elles fabriquent.",
    sample: "Profil exemple",
    sampleNote: "Les profils exemples montrent l’apparence des showrooms exposants. Les exposants confirmés sont publiés dès leur signature.",
    district: "District",
    stand: "Stand",
    requestMeeting: "Demander un rendez-vous",
    visitStand: "Trouver le stand",
    products: "Mur de produits",
    materials: "Matériaux",
    markets: "Marchés",
    founded: "Fondée en",
    all: "Tous",
    empty: "Aucun exposant dans ce secteur pour le moment.",
  },
  experience: {
    zones: {
      conference: "Salle de conférences",
      conferenceSub: "Conférences, tables rondes, présentations de projets",
      b2b: "Salon d’affaires B2B",
      b2bSub: "Rendez-vous acheteurs planifiés",
      demo: "Scène des démonstrations",
      demoSub: "Démos de pose et de machines",
      aisle: "Allée principale",
      pavilions: "Pavillons nationaux",
      lounge: "Lounge & café",
      registration: "Accueil & badges",
      entrance: "Entrée principale",
    },
    legendTaken: "Stand réservé",
    title: "L’expérience SURMAT",
    lead: "Neuf quartiers, une salle de conférences, un salon B2B et une scène de démonstrations. Parcourez le plan, trouvez un stand, réservez le vôtre.",
    mapTitle: "Plan du salon",
    mapHint: "Sélectionnez un stand pour voir qui expose.",
    open: "Ouvrir le stand",
    available: "Stand disponible",
    availableLead: "Ce stand est ouvert à la réservation.",
    book: "Réserver ce stand",
    teaserTitle: "Plus qu’un salon",
    teaserLead: "Un parcours immersif à travers les matériaux, les applications, l’innovation et l’expertise du secteur.",
    central: "Espace central",
    branches: [
      "Plan du salon",
      "Districts de matériaux",
      "Conférences",
      "Démonstrations produits",
      "Networking",
    ],
  },
  visit: {
    title: "Visiter le SURMAT",
    lead: "Quatre jours avec les fabricants de chaque surface d’un bâtiment. Inscription gratuite pour les professionnels.",
    who: "Qui visite",
    profiles: {
      architect: "Architecte ou architecte d’intérieur",
      developer: "Promoteur ou maître d’ouvrage",
      contractor: "Entreprise ou poseur",
      distributor: "Distributeur ou négociant",
      buyer: "Acheteur",
      manufacturer: "Fabricant",
      other: "Autre professionnel",
    },
    formTitle: "S’inscrire pour visiter",
    profile: "Votre profil",
    interests: "Matériaux recherchés",
    submit: "S’inscrire pour visiter",
    successTitle: "Vous êtes inscrit.",
    successLead: "Votre badge sera envoyé à {email} avant l’ouverture du salon.",
    meetingWith: "Demande de rendez-vous avec {name}",
  },
  exhibit: {
    title: "Exposer au SURMAT",
    lead: "Vos produits ont leur place ici.",
    why: [
      "Architectes, promoteurs, entreprises et distributeurs d’Algérie, du Sénégal et de toute l’Afrique",
      "Votre stand se trouve dans le district de vos matériaux, là où les prescripteurs viennent chercher",
      "Vos produits restent en ligne toute l’année dans la matériauthèque SURMAT, en neuf langues",
    ],
    steps: ["Matériaux", "Entreprise", "Portefeuille", "Surface", "Contact"],
    manufacture: "Que fabriquez-vous ?",
    companyTitle: "Présentez votre entreprise",
    portfolioTitle: "Qu’allez-vous exposer ?",
    spaceTitle: "De quelle surface avez-vous besoin ?",
    contactTitle: "Qui devons-nous contacter ?",
    companyName: "Raison sociale",
    website: "Site web",
    country: "Pays",
    families: "Familles de produits",
    brands: "Marques",
    machinery: "Nous ferons une démonstration de machines",
    demo: "Nous souhaitons une zone de démonstration",
    meetingRoom: "Nous avons besoin d’un espace de réunion privé",
    description: "Produits que vous prévoyez d’exposer",
    recommended: "D’après votre portefeuille, SURMAT recommande {min}–{max} m².",
    requested: "Surface souhaitée (m²)",
    edition: "Édition",
    back: "Retour",
    next: "Continuer",
    submit: "Envoyer la candidature",
    successTitle: "Vos produits ont leur place au SURMAT.",
    successLead: "Un chargé commercial SURMAT contactera {email} avec des options de stand dans le district {sector}.",
    pickOne: "Sélectionnez au moins un secteur pour continuer.",
  },
  form: {
    name: "Nom complet",
    role: "Fonction",
    company: "Entreprise",
    email: "E-mail professionnel",
    phone: "Téléphone",
    country: "Pays",
    required: "Obligatoire",
    invalidEmail: "Saisissez une adresse comme nom@entreprise.com.",
    error: "Le formulaire n’a pas pu être envoyé. Vérifiez votre connexion et réessayez.",
    sending: "Envoi…",
    consent: "SURMAT peut me contacter au sujet de cette édition.",
  },
  cta: {
    dialogTitle: "Exposer au SURMAT",
    dialogLead: "Vos produits ont leur place ici.",
    apply: "Candidater pour exposer",
    close: "Fermer",
  },
  edition: {
    datesTBA: "Dates à annoncer",
    venueTBA: "Lieu à annoncer",
    switchTo: "Passer à {name}",
  },
  search: {
    title: "Rechercher sur SURMAT",
    placeholder: "Matériau, espace ou entreprise — ex. « marbre sol hôtel »",
    materials: "Matériaux",
    sectors: "Secteurs",
    applications: "Applications",
    exhibitors: "Exposants",
    empty: "Saisissez un matériau, un espace ou une entreprise.",
    none: "Aucun résultat pour « {q} ». Essayez un seul matériau, comme « porcelaine ».",
    popularMaterials: "Matériaux populaires",
    popularApplications: "Applications populaires",
    featuredExhibitors: "Exposants à la une",
  },
  footer: {
    tagline: "Salon International des Matériaux de Surface et des Produits de Finition du Bâtiment.",
    rights: "© {year} SURMAT. Tous droits réservés.",
    platform: "Plateforme",
    editions: "Éditions",
    languages: "Langues",
    legal: "Mentions légales",
    privacy: "Confidentialité",
    contact: "Contact",
  },
  common: { back: "Retour", all: "Tous", learnMore: "En savoir plus", of: "sur", explore: "Explorer" },
  vocab: {
    matt: "Mat", polished: "Poli", honed: "Adouci", textured: "Structuré", antiSlip: "Antidérapant",
    brushed: "Brossé", glossy: "Brillant", satin: "Satiné", leather: "Cuir", flamed: "Flammé",
    bushHammered: "Bouchardé", metallic: "Métallisé", velvet: "Velours", raw: "Naturel",
    tile: "Carreau", largeFormat: "Grand format", slab: "Dalle", mosaic: "Mosaïque", block: "Bloc",
    board: "Plaque", panel: "Panneau", roll: "Rouleau", liquid: "Liquide", powder: "Poudre", paste: "Pâte",
    cartridge: "Cartouche", line: "Ligne de production", machine: "Machine", module: "Module",
  },
};
