import type { Dict } from "./en";

export const fr: Dict = {
  brand: {
    descriptor: "Matériaux de surface & produits de finition du bâtiment",
    eyebrow: "Le salon international des",
  },
  nav: {
    materials: "Matériaux",
    applications: "Applications",
    exhibitors: "Exposants",
    experience: "Expérience",
    visit: "Visiter",
    exhibit: "Exposer",
    register: "S’inscrire pour visiter",
    search: "Rechercher",
    menu: "Menu",
    close: "Fermer",
    edition: "Édition",
    language: "Langue",
    skip: "Aller au contenu",
  },
  hero: {
    explore: "Explorer les matériaux",
    exhibit: "Exposer au SURMAT",
    visit: "Visiter le SURMAT",
    searchLabel: "Rechercher dans l’univers des matériaux",
    searchPlaceholder: "Essayez « marbre », « sol d’hôtel » ou « étanchéité »",
    matches: "{n} matériaux mis en avant",
    noMatch: "Rien ne correspond encore à « {q} »",
    clear: "Effacer la recherche",
    close: "Retour à l’univers",
    exploreMaterial: "Découvrir le matériau",
    findExhibitors: "Trouver des exposants",
    usedIn: "Utilisé dans",
    format: "Format",
    hint: "Faites glisser pour tourner l’univers. Sélectionnez un échantillon pour l’approcher.",
  },
  stats: {
    sectors: "Secteurs de matériaux",
    editions: "Éditions",
    exhibitors: "Exposants (objectif)",
    visitors: "Visiteurs professionnels (objectif)",
    hub: "Un hub régional pour des opportunités mondiales",
  },
  home: {
    materialsTitle: "Explorez l’univers des matériaux",
    materialsLead: "De la pierre naturelle aux systèmes de finition avancés — six secteurs qui façonnent l’architecture moderne.",
    viewAll: "Tous les matériaux",
    spacesTitle: "Les matériaux deviennent des espaces",
    spacesLead: "Chaque matériau du SURMAT finit dans un hôtel, un logement, un hôpital ou un bâtiment public. Partez de l’espace.",
    exploreApps: "Toutes les applications",
    industryTitle: "Rencontrez l’industrie",
    industryLead: "Fabricants, fournisseurs et innovateurs présentent leurs collections au SURMAT.",
    viewExhibitors: "Voir les exposants",
    experienceTitle: "Vivez le SURMAT",
    experienceLead: "Parcourez les six districts du salon et trouvez chaque stand par le matériau qu’il présente.",
    exploreExperience: "Découvrir l’expérience",
    editionsTitle: "Éditions SURMAT",
    editionsLead: "Deux marchés. Un seul univers de matériaux.",
    exploreEdition: "Découvrir l’édition",
    current: "Vous êtes ici",
    visitTitle: "Venez toucher les matériaux",
    visitLead: "Inscription gratuite pour les architectes, promoteurs, entreprises, distributeurs et acheteurs.",
    exhibitTitle: "Vos produits ont leur place ici",
    exhibitLead: "Présentez vos collections à ceux qui les prescrivent, les achètent et les posent.",
  },
  why: {
    eyebrow: "Pourquoi exposer",
    title: "Un stand. Quatre marchés.",
    lead: "Le SURMAT relie les fabricants de chaque surface d’un bâtiment à ceux qui construisent l’Afrique du Nord et de l’Ouest — et ouvre aux entreprises du monde entier une porte sur le continent.",
    markets: [
      {
        id: "dz",
        name: "Algérie",
        kicker: "Le premier marché d’Afrique du Nord",
        points: [
          "Le plus grand pays d’Afrique par sa superficie, environ 47 millions d’habitants",
          "Des programmes soutenus de logement, d’infrastructures, d’hôtellerie et d’équipements publics",
          "Un pont entre le Maghreb, la Méditerranée et le Sahel",
        ],
      },
      {
        id: "sn",
        name: "Sénégal",
        kicker: "La porte de l’Afrique de l’Ouest",
        points: [
          "Dakar : un pôle d’affaires stable et dynamique sur l’Atlantique",
          "Membre de la CEDEAO (15 pays) et de l’UEMOA (8 pays partageant le franc CFA)",
          "Villes nouvelles, ports, hôtels et équipements publics en construction",
        ],
      },
      {
        id: "africa",
        name: "Afrique",
        kicker: "Le prochain boom de la construction",
        points: [
          "Plus de 1,4 milliard d’habitants — la population la plus jeune du monde",
          "La Zone de libre-échange continentale africaine réunit 54 pays en un seul marché",
          "Une population urbaine appelée à presque doubler d’ici 2050",
        ],
      },
      {
        id: "world",
        name: "Le monde",
        kicker: "Votre porte vers le continent",
        points: [
          "Des pavillons nationaux pour l’Europe, la Türkiye, la Chine, l’Inde, le Golfe et les Amériques",
          "Rencontrez importateurs, distributeurs et agents de toute l’Afrique en un seul lieu",
          "Une plateforme en neuf langues, ouverte aux exposants de tous les pays",
        ],
      },
    ],
    offerTitle: "Ce que reçoivent les exposants",
    offerLead: "Tout au SURMAT vise un seul résultat : placer vos produits devant ceux qui les prescrivent, les achètent et les posent.",
    offer: [
      {
        title: "Des acheteurs qualifiés",
        text: "Architectes, promoteurs, entreprises, distributeurs et acheteurs publics, inscrits par profil et par matériaux recherchés.",
      },
      {
        title: "Des rendez-vous planifiés",
        text: "Les visiteurs demandent un rendez-vous sur votre stand avant l’ouverture. Vous arrivez avec un agenda, pas un espoir.",
      },
      { title: "Le bon district", text: "Votre stand se trouve parmi les matériaux que vous fabriquez — là où les prescripteurs viennent les comparer." },
      { title: "Une vitrine à l’année", text: "Votre profil dans la matériauthèque SURMAT continue de travailler après le salon, en neuf langues." },
      { title: "Une scène pour vos lancements", text: "Présentez nouvelles collections et technologies dans le programme de conférences et de démonstrations." },
      { title: "Une veille de marché", text: "Voyez quels matériaux et applications suscitent le plus d’intérêt sur chaque marché, édition après édition." },
    ],
    audienceTitle: "Qui vous rencontrerez",
    audienceLead: "Uniquement des visiteurs professionnels. Chacun s’inscrit avec son profil et les matériaux qu’il recherche.",
    participateTitle: "Façons de participer",
    participate: [
      { title: "Stand", text: "Surface nue ou stand équipé, dès 9 m², dans le district de vos matériaux." },
      { title: "Pavillon national", text: "Exposez sous le drapeau de votre pays avec un pavillon partagé et une promotion commune." },
      { title: "Sponsoring", text: "Associez votre marque au salon, à la scène de conférences ou au parcours visiteur." },
      { title: "Vitrine digitale", text: "Pas encore prêt pour un stand ? Commencez par un profil dans la matériauthèque en ligne." },
    ],
    cta: "Demander un stand",
    brochure: "Parler à notre équipe commerciale",
  },
  sector: {
    materials: "Matériaux de ce secteur",
    exhibitors: "Exposants de ce district",
    district: "District",
  },
  material: {
    sector: "Secteur",
    finishes: "Finitions",
    applications: "Applications",
    formats: "Formats",
    spec: "Gamme type",
    exhibitors: "Exposants présentant ce matériau",
    noExhibitors: "Aucun exposant n’a encore confirmé ce matériau. Le vôtre pourrait être le premier.",
    related: "Matériaux associés",
    manufacturerQ: "Vous fabriquez : {material} ?",
  },
  catalogue: {
    title: "Matériauthèque",
    lead: "Tous les matériaux présentés au SURMAT, classés par secteur. Chacun mène aux entreprises qui le fabriquent.",
    all: "Tous les secteurs",
    search: "Filtrer les matériaux",
    noResults: "Aucun matériau ne correspond à « {q} ». Essayez un mot plus large comme « pierre » ou « carreau ».",
    count: "{n} matériaux",
  },
  apps: {
    title: "Applications",
    lead: "Partez de l’espace que vous construisez et rencontrez les exposants qui en fournissent chaque surface.",
    materialsUsed: "Matériaux de cet espace",
    suppliers: "Exposants fournissant ces matériaux",
  },
  exhibitors: {
    title: "Exposants",
    lead: "Parcourez les entreprises présentes au SURMAT selon les matériaux qu’elles fabriquent.",
    sample: "Profil exemple",
    sampleNote: "Les profils exemples montrent l’apparence des showrooms exposants. Les exposants confirmés sont publiés dès leur signature.",
    district: "District",
    stand: "Stand",
    requestMeeting: "Demander un rendez-vous",
    visitStand: "Trouver le stand",
    products: "Mur de produits",
    materials: "Matériaux",
    markets: "Marchés",
    founded: "Fondée en",
    all: "Tous",
    empty: "Aucun exposant dans ce secteur pour le moment.",
  },
  experience: {
    title: "L’expérience SURMAT",
    lead: "Le salon est organisé en six districts de matériaux. Parcourez le plan, trouvez un stand, réservez le vôtre.",
    mapTitle: "Plan du salon",
    mapHint: "Sélectionnez un stand pour voir qui expose.",
    open: "Ouvrir le stand",
    available: "Stand disponible",
    availableLead: "Ce stand est ouvert à la réservation.",
    book: "Réserver ce stand",
  },
  visit: {
    title: "Visiter le SURMAT",
    lead: "Quatre jours avec les fabricants de chaque surface d’un bâtiment. Inscription gratuite pour les professionnels.",
    who: "Qui visite",
    profiles: {
      architect: "Architecte ou architecte d’intérieur",
      developer: "Promoteur ou maître d’ouvrage",
      contractor: "Entreprise ou poseur",
      distributor: "Distributeur ou négociant",
      buyer: "Acheteur",
      manufacturer: "Fabricant",
      other: "Autre professionnel",
    },
    formTitle: "S’inscrire pour visiter",
    profile: "Votre profil",
    interests: "Matériaux recherchés",
    submit: "S’inscrire pour visiter",
    successTitle: "Vous êtes inscrit.",
    successLead: "Votre badge sera envoyé à {email} avant l’ouverture du salon.",
    meetingWith: "Demande de rendez-vous avec {name}",
  },
  exhibit: {
    title: "Exposer au SURMAT",
    lead: "Vos produits ont leur place ici.",
    why: [
      "Architectes, promoteurs, entreprises et distributeurs d’Algérie, du Sénégal et de toute l’Afrique",
      "Votre stand se trouve dans le district de vos matériaux, là où les prescripteurs viennent chercher",
      "Vos produits restent en ligne toute l’année dans la matériauthèque SURMAT, en neuf langues",
    ],
    steps: ["Matériaux", "Entreprise", "Portefeuille", "Surface", "Contact"],
    manufacture: "Que fabriquez-vous ?",
    companyTitle: "Présentez votre entreprise",
    portfolioTitle: "Qu’allez-vous exposer ?",
    spaceTitle: "De quelle surface avez-vous besoin ?",
    contactTitle: "Qui devons-nous contacter ?",
    companyName: "Raison sociale",
    website: "Site web",
    country: "Pays",
    families: "Familles de produits",
    brands: "Marques",
    machinery: "Nous ferons une démonstration de machines",
    demo: "Nous souhaitons une zone de démonstration",
    meetingRoom: "Nous avons besoin d’un espace de réunion privé",
    description: "Produits que vous prévoyez d’exposer",
    recommended: "D’après votre portefeuille, SURMAT recommande {min}–{max} m².",
    requested: "Surface souhaitée (m²)",
    edition: "Édition",
    back: "Retour",
    next: "Continuer",
    submit: "Envoyer la candidature",
    successTitle: "Vos produits ont leur place au SURMAT.",
    successLead: "Un chargé commercial SURMAT contactera {email} avec des options de stand dans le district {sector}.",
    pickOne: "Sélectionnez au moins un secteur pour continuer.",
  },
  form: {
    name: "Nom complet",
    role: "Fonction",
    company: "Entreprise",
    email: "E-mail professionnel",
    phone: "Téléphone",
    country: "Pays",
    required: "Obligatoire",
    invalidEmail: "Saisissez une adresse comme nom@entreprise.com.",
    error: "Le formulaire n’a pas pu être envoyé. Vérifiez votre connexion et réessayez.",
    sending: "Envoi…",
    consent: "SURMAT peut me contacter au sujet de cette édition.",
  },
  cta: {
    dialogTitle: "Exposer au SURMAT",
    dialogLead: "Vos produits ont leur place ici.",
    apply: "Candidater pour exposer",
    close: "Fermer",
  },
  edition: {
    datesTBA: "Dates à annoncer",
    venueTBA: "Lieu à annoncer",
    switchTo: "Passer à {name}",
  },
  search: {
    title: "Rechercher sur SURMAT",
    placeholder: "Matériau, espace ou entreprise — ex. « marbre sol hôtel »",
    materials: "Matériaux",
    sectors: "Secteurs",
    applications: "Applications",
    exhibitors: "Exposants",
    empty: "Saisissez un matériau, un espace ou une entreprise.",
    none: "Aucun résultat pour « {q} ». Essayez un seul matériau, comme « porcelaine ».",
  },
  footer: {
    tagline: "Le salon international des matériaux de surface & produits de finition du bâtiment.",
    rights: "© {year} SURMAT. Tous droits réservés.",
    platform: "Plateforme",
    editions: "Éditions",
  },
  common: { back: "Retour", all: "Tous", learnMore: "En savoir plus", of: "sur" },
  vocab: {
    matt: "Mat", polished: "Poli", honed: "Adouci", textured: "Structuré", antiSlip: "Antidérapant",
    brushed: "Brossé", glossy: "Brillant", satin: "Satiné", leather: "Cuir", flamed: "Flammé",
    bushHammered: "Bouchardé", metallic: "Métallisé", velvet: "Velours", raw: "Naturel",
    tile: "Carreau", largeFormat: "Grand format", slab: "Dalle", mosaic: "Mosaïque", block: "Bloc",
    board: "Plaque", panel: "Panneau", roll: "Rouleau", liquid: "Liquide", powder: "Poudre", paste: "Pâte",
    cartridge: "Cartouche", line: "Ligne de production", machine: "Machine", module: "Module",
  },
};
