import type { Dict } from "./en";

export const it: Dict = {
  brand: {
    descriptor: "Materiali di superficie e prodotti di finitura per l’edilizia",
    eyebrow: "La fiera internazionale dei",
  },
  nav: {
    materials: "Materiali",
    applications: "Applicazioni",
    exhibitors: "Espositori",
    experience: "Esperienza",
    visit: "Visitare",
    exhibit: "Esporre",
    register: "Registrati per visitare",
    search: "Cerca",
    menu: "Menu",
    close: "Chiudi",
    edition: "Edizione",
    language: "Lingua",
    skip: "Vai al contenuto",
  },
  hero: {
    explore: "Esplora i materiali",
    exhibit: "Esponi a SURMAT",
    visit: "Visita SURMAT",
    searchLabel: "Cerca nell’universo dei materiali",
    searchPlaceholder: "Prova “marmo”, “pavimento hotel” o “impermeabilizzazione”",
    matches: "{n} materiali in primo piano",
    noMatch: "Nulla nell’universo corrisponde ancora a “{q}”",
    clear: "Cancella la ricerca",
    close: "Torna all’universo",
    exploreMaterial: "Scopri il materiale",
    findExhibitors: "Trova gli espositori",
    usedIn: "Utilizzato in",
    format: "Formato",
    hint: "Trascina per ruotare l’universo. Seleziona un campione per portarlo in primo piano.",
  },
  stats: {
    sectors: "Settori di materiali",
    editions: "Edizioni",
    exhibitors: "Espositori (obiettivo)",
    visitors: "Visitatori professionali (obiettivo)",
    hub: "Un hub regionale per opportunità globali",
  },
  home: {
    materialsTitle: "Esplora il mondo dei materiali",
    materialsLead: "Dalla pietra naturale ai sistemi di finitura più avanzati — sei settori che danno forma all’architettura moderna.",
    viewAll: "Tutti i materiali",
    spacesTitle: "I materiali diventano spazi",
    spacesLead: "Ogni materiale di SURMAT finisce in un hotel, una casa, un ospedale o un edificio pubblico. Parti dallo spazio.",
    exploreApps: "Tutte le applicazioni",
    industryTitle: "Incontra l’industria",
    industryLead: "Produttori, fornitori e innovatori che presentano le loro collezioni a SURMAT.",
    viewExhibitors: "Vedi gli espositori",
    experienceTitle: "Vivi SURMAT",
    experienceLead: "Percorri i sei distretti della fiera e trova ogni stand in base al materiale che presenta.",
    exploreExperience: "Scopri l’esperienza",
    editionsTitle: "Le edizioni di SURMAT",
    editionsLead: "Due mercati. Un universo di materiali.",
    exploreEdition: "Scopri l’edizione",
    current: "Sei qui",
    visitTitle: "Vieni a toccare i materiali",
    visitLead: "La registrazione è gratuita per architetti, sviluppatori, imprese, distributori e buyer.",
    exhibitTitle: "Il posto dei tuoi prodotti è qui",
    exhibitLead: "Metti le tue collezioni davanti a chi le prescrive, le acquista e le posa.",
  },
  why: {
    eyebrow: "Perché esporre",
    title: "Uno stand. Quattro mercati.",
    lead: "SURMAT collega i produttori di ogni superficie di un edificio con chi costruisce il Nord e l’Ovest dell’Africa — e apre alle aziende di tutto il mondo una porta sul continente.",
    markets: [
      {
        id: "dz",
        name: "Algeria",
        kicker: "Il più grande mercato del Nord Africa",
        points: [
          "Il paese più esteso dell’Africa, con circa 47 milioni di abitanti",
          "Programmi continui di edilizia abitativa, infrastrutture, ospitalità ed edifici pubblici",
          "Un ponte tra Maghreb, Mediterraneo e Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "La porta dell’Africa occidentale",
        points: [
          "Dakar: un hub d’affari stabile e in rapida crescita sull’Atlantico",
          "Membro dell’ECOWAS (15 paesi) e dell’UEMOA (8 paesi che condividono il franco CFA)",
          "Nuove città, porti, hotel e strutture pubbliche in costruzione",
        ],
      },
      {
        id: "africa",
        name: "Africa",
        kicker: "Il prossimo boom edilizio",
        points: [
          "Oltre 1,4 miliardi di persone — la popolazione più giovane del mondo",
          "L’Area continentale africana di libero scambio riunisce 54 paesi in un unico mercato",
          "Si prevede che la popolazione urbana quasi raddoppi entro il 2050",
        ],
      },
      {
        id: "world",
        name: "Il mondo",
        kicker: "La tua porta sul continente",
        points: [
          "Padiglioni nazionali per Europa, Türkiye, Cina, India, Golfo e Americhe",
          "Incontra in un unico luogo importatori, distributori e agenti di tutta l’Africa",
          "Una piattaforma in nove lingue, aperta agli espositori di ogni paese",
        ],
      },
    ],
    offerTitle: "Cosa ottengono gli espositori",
    offerLead: "Tutto a SURMAT è costruito intorno a un risultato: mettere i tuoi prodotti davanti a chi li prescrive, li acquista e li posa.",
    offer: [
      {
        title: "Buyer qualificati",
        text: "Architetti, sviluppatori, imprese, distributori e acquirenti pubblici, registrati per profilo e per i materiali che cercano.",
      },
      { title: "Incontri fissati in anticipo", text: "I visitatori richiedono appuntamenti al tuo stand prima dell’apertura. Arrivi con un’agenda, non con una speranza." },
      { title: "Il distretto giusto", text: "Il tuo stand si trova tra i materiali che produci — proprio dove i progettisti vanno a confrontarli." },
      { title: "Uno showroom tutto l’anno", text: "Il tuo profilo nella libreria dei materiali SURMAT continua a lavorare dopo la fiera, in nove lingue." },
      { title: "Un palco per i lanci", text: "Presenta nuove collezioni e tecnologie nel programma di conferenze e dimostrazioni dal vivo." },
      { title: "Informazioni di mercato", text: "Scopri quali materiali e applicazioni suscitano più interesse in ogni mercato, edizione dopo edizione." },
    ],
    audienceTitle: "Chi incontrerai",
    audienceLead: "Solo visitatori professionali. Ognuno si registra con il proprio profilo e i materiali che cerca.",
    participateTitle: "Come partecipare",
    participate: [
      { title: "Stand", text: "Area libera o stand preallestito, da 9 m², nel distretto dei tuoi materiali." },
      { title: "Padiglione nazionale", text: "Esponi sotto la bandiera del tuo paese in un padiglione condiviso con promozione congiunta." },
      { title: "Sponsorizzazione", text: "Associa il tuo marchio alla fiera, al palco delle conferenze o al percorso dei visitatori." },
      { title: "Showroom digitale", text: "Non sei ancora pronto per uno stand? Inizia con un profilo nella libreria dei materiali online." },
    ],
    cta: "Richiedi uno stand",
    brochure: "Parla con il team commerciale",
  },
  sector: {
    materials: "Materiali di questo settore",
    exhibitors: "Espositori di questo distretto",
    district: "Distretto",
  },
  material: {
    sector: "Settore",
    finishes: "Finiture",
    applications: "Applicazioni",
    formats: "Formati",
    spec: "Gamma tipica",
    exhibitors: "Espositori che presentano questo materiale",
    noExhibitors: "Nessun espositore ha ancora confermato questo materiale. Il tuo potrebbe essere il primo.",
    related: "Materiali correlati",
    manufacturerQ: "Produci {material}?",
  },
  catalogue: {
    title: "Libreria dei materiali",
    lead: "Tutti i materiali presentati a SURMAT, organizzati per settore. Ognuno porta alle aziende che lo producono.",
    all: "Tutti i settori",
    search: "Filtra i materiali",
    noResults: "Nessun materiale corrisponde a “{q}”. Prova una parola più ampia come “pietra” o “piastrella”.",
    count: "{n} materiali",
  },
  apps: {
    title: "Applicazioni",
    lead: "Parti dallo spazio che stai costruendo e incontra gli espositori che ne forniscono ogni superficie.",
    materialsUsed: "Materiali in questo spazio",
    suppliers: "Espositori che forniscono questi materiali",
  },
  exhibitors: {
    title: "Espositori",
    lead: "Esplora le aziende presenti a SURMAT in base ai materiali che producono.",
    sample: "Profilo di esempio",
    sampleNote: "I profili di esempio mostrano come appariranno gli showroom degli espositori. Gli espositori confermati vengono pubblicati man mano che firmano.",
    district: "Distretto",
    stand: "Stand",
    requestMeeting: "Richiedi un incontro",
    visitStand: "Trova lo stand",
    products: "Parete prodotti",
    materials: "Materiali",
    markets: "Mercati",
    founded: "Fondata nel",
    all: "Tutti",
    empty: "Ancora nessun espositore in questo settore.",
  },
  experience: {
    title: "L’esperienza SURMAT",
    lead: "La fiera è organizzata in sei distretti di materiali. Percorri la planimetria, trova uno stand, prenota il tuo.",
    mapTitle: "Planimetria della fiera",
    mapHint: "Seleziona uno stand per vedere chi espone.",
    open: "Apri lo stand",
    available: "Stand disponibile",
    availableLead: "Questo stand è disponibile per la prenotazione.",
    book: "Prenota questo stand",
  },
  visit: {
    title: "Visita SURMAT",
    lead: "Quattro giorni con i produttori di ogni superficie di un edificio. La registrazione è gratuita per i professionisti.",
    who: "Chi visita",
    profiles: {
      architect: "Architetto o interior designer",
      developer: "Sviluppatore o committente",
      contractor: "Impresa o posatore",
      distributor: "Distributore o rivenditore",
      buyer: "Buyer o ufficio acquisti",
      manufacturer: "Produttore",
      other: "Altro professionista",
    },
    formTitle: "Registrati per visitare",
    profile: "Il tuo profilo",
    interests: "Materiali che cerchi",
    submit: "Registrati per visitare",
    successTitle: "Sei registrato.",
    successLead: "Il tuo badge sarà inviato a {email} prima dell’apertura della fiera.",
    meetingWith: "Richiesta di incontro con {name}",
  },
  exhibit: {
    title: "Esponi a SURMAT",
    lead: "Il posto dei tuoi prodotti è qui.",
    why: [
      "Architetti, sviluppatori, imprese e distributori da Algeria, Senegal e tutta l’Africa",
      "Il tuo stand è nel distretto dei tuoi materiali, dove i progettisti vengono a cercarli",
      "I tuoi prodotti restano online tutto l’anno nella libreria dei materiali SURMAT, in nove lingue",
    ],
    steps: ["Materiali", "Azienda", "Portfolio", "Spazio", "Contatto"],
    manufacture: "Che cosa produci?",
    companyTitle: "Parlaci della tua azienda",
    portfolioTitle: "Che cosa esporrai?",
    spaceTitle: "Di quanto spazio hai bisogno?",
    contactTitle: "Chi dobbiamo contattare?",
    companyName: "Nome dell’azienda",
    website: "Sito web",
    country: "Paese",
    families: "Famiglie di prodotti",
    brands: "Marchi",
    machinery: "Faremo dimostrazioni di macchinari",
    demo: "Vogliamo un’area per dimostrazioni dal vivo",
    meetingRoom: "Ci serve un’area riunioni riservata",
    description: "Prodotti che intendi presentare",
    recommended: "In base al tuo portfolio, SURMAT consiglia {min}–{max} m².",
    requested: "Superficie richiesta (m²)",
    edition: "Edizione",
    back: "Indietro",
    next: "Continua",
    submit: "Invia la domanda",
    successTitle: "Il posto dei tuoi prodotti è a SURMAT.",
    successLead: "Un responsabile commerciale SURMAT contatterà {email} con le opzioni di stand nel distretto {sector}.",
    pickOne: "Seleziona almeno un settore per continuare.",
  },
  form: {
    name: "Nome e cognome",
    role: "Ruolo",
    company: "Azienda",
    email: "E-mail di lavoro",
    phone: "Telefono",
    country: "Paese",
    required: "Obbligatorio",
    invalidEmail: "Inserisci un indirizzo come nome@azienda.com.",
    error: "Impossibile inviare il modulo. Controlla la connessione e riprova.",
    sending: "Invio in corso…",
    consent: "SURMAT può contattarmi in merito a questa edizione.",
  },
  cta: {
    dialogTitle: "Esponi a SURMAT",
    dialogLead: "Il posto dei tuoi prodotti è qui.",
    apply: "Richiedi uno stand",
    close: "Chiudi",
  },
  edition: {
    datesTBA: "Date da annunciare",
    venueTBA: "Sede da annunciare",
    switchTo: "Passa a {name}",
  },
  search: {
    title: "Cerca in SURMAT",
    placeholder: "Materiale, spazio o azienda — es. “pavimento in marmo hotel”",
    materials: "Materiali",
    sectors: "Settori",
    applications: "Applicazioni",
    exhibitors: "Espositori",
    empty: "Scrivi un materiale, uno spazio o un’azienda.",
    none: "Nessun risultato per “{q}”. Prova un solo materiale, come “gres”.",
  },
  footer: {
    tagline: "La fiera internazionale dei materiali di superficie e dei prodotti di finitura per l’edilizia.",
    rights: "© {year} SURMAT. Tutti i diritti riservati.",
    platform: "Piattaforma",
    editions: "Edizioni",
  },
  common: { back: "Indietro", all: "Tutti", learnMore: "Scopri di più", of: "di" },
  vocab: {
    matt: "Opaco", polished: "Lucido", honed: "Levigato", textured: "Strutturato", antiSlip: "Antiscivolo",
    brushed: "Spazzolato", glossy: "Brillante", satin: "Satinato", leather: "Anticato", flamed: "Fiammato",
    bushHammered: "Bocciardato", metallic: "Metallico", velvet: "Vellutato", raw: "Naturale",
    tile: "Piastrella", largeFormat: "Grande formato", slab: "Lastra", mosaic: "Mosaico", block: "Blocco",
    board: "Lastra", panel: "Pannello", roll: "Rotolo", liquid: "Liquido", powder: "Polvere", paste: "Pasta",
    cartridge: "Cartuccia", line: "Linea di produzione", machine: "Macchina", module: "Modulo",
  },
};
