import type { Dict } from "./en";

export const it: Dict = {
  brand: {
    descriptor: "Materiali di superficie e prodotti di finitura per l’edilizia",
    eyebrow: "La fiera internazionale dei",
  },
  nav: {
    board: "Il campionario",
    partners: "Partnership",
    materials: "Materiali",
    applications: "Applicazioni",
    exhibitors: "Espositori",
    experience: "Esperienza",
    visit: "Visitare",
    exhibit: "Esporre",
    register: "Registrati per visitare",
    search: "Cerca",
    menu: "Menu",
    close: "Chiudi",
    edition: "Edizione",
    language: "Lingua",
    skip: "Vai al contenuto",
    pro: "Area Pro",
  },
  hero: {
    explore: "Esplora i materiali",
    exhibit: "Esponi a SURMAT",
    visit: "Visita SURMAT",
    searchLabel: "Cerca nell’universo dei materiali",
    searchPlaceholder: "Prova “marmo”, “pavimento hotel” o “impermeabilizzazione”",
    matches: "{n} materiali in primo piano",
    noMatch: "Nulla nell’universo corrisponde ancora a “{q}”",
    clear: "Cancella la ricerca",
    close: "Torna all’universo",
    exploreMaterial: "Scopri il materiale",
    findExhibitors: "Trova gli espositori",
    usedIn: "Utilizzato in",
    format: "Formato",
    hint: "Trascina per ruotare l’universo. Seleziona un campione per portarlo in primo piano.",
    scroll: "Scorri per esplorare",
    tagline: "I materiali danno forma a spazi migliori",
  },
  stats: {
    sectors: "Settori di materiali",
    editions: "Edizioni",
    exhibitors: "Espositori (obiettivo)",
    visitors: "Visitatori professionali (obiettivo)",
    hub: "Un hub regionale per opportunità globali",
  },
  home: {
    materialsTitle: "Esplora il mondo dei materiali",
    materialsLead: "Dalla pietra naturale ai sistemi di finitura più avanzati — sei settori che danno forma all’architettura moderna.",
    viewAll: "Tutti i materiali",
    spacesTitle: "I materiali diventano spazi",
    spacesLead: "Ogni materiale di SURMAT finisce in un hotel, una casa, un ospedale o un edificio pubblico. Parti dallo spazio.",
    exploreApps: "Tutte le applicazioni",
    industryTitle: "Incontra l’industria",
    industryLead: "Produttori, fornitori e innovatori che presentano le loro collezioni a SURMAT.",
    viewExhibitors: "Vedi gli espositori",
    experienceTitle: "Vivi SURMAT",
    experienceLead: "Percorri i sei distretti della fiera e trova ogni stand in base al materiale che presenta.",
    exploreExperience: "Scopri l’esperienza",
    editionsTitle: "Le edizioni di SURMAT",
    editionsLead: "Due mercati. Un universo di materiali.",
    exploreEdition: "Scopri l’edizione",
    current: "Sei qui",
    visitTitle: "Vieni a toccare i materiali",
    visitLead: "La registrazione è gratuita per architetti, sviluppatori, imprese, distributori e buyer.",
    exhibitTitle: "Il posto dei tuoi prodotti è qui",
    exhibitLead: "Metti le tue collezioni davanti a chi le prescrive, le acquista e le posa.",
    editionsHeadline: "Due edizioni. Una piattaforma.",
  },
  why: {
    eyebrow: "Perché esporre",
    title: "Uno stand. Quattro mercati.",
    lead: "SURMAT collega i produttori di ogni superficie di un edificio con chi costruisce il Nord e l’Ovest dell’Africa — e apre alle aziende di tutto il mondo una porta sul continente.",
    markets: [
      {
        id: "dz",
        name: "Algeria",
        kicker: "Il più grande mercato del Nord Africa",
        points: [
          "Il paese più esteso dell’Africa, con circa 47 milioni di abitanti",
          "Programmi continui di edilizia abitativa, infrastrutture, ospitalità ed edifici pubblici",
          "Un ponte tra Maghreb, Mediterraneo e Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "La porta dell’Africa occidentale",
        points: [
          "Dakar: un hub d’affari stabile e in rapida crescita sull’Atlantico",
          "Membro dell’ECOWAS (15 paesi) e dell’UEMOA (8 paesi che condividono il franco CFA)",
          "Nuove città, porti, hotel e strutture pubbliche in costruzione",
        ],
      },
      {
        id: "africa",
        name: "Africa",
        kicker: "Il prossimo boom edilizio",
        points: [
          "Oltre 1,4 miliardi di persone — la popolazione più giovane del mondo",
          "L’Area continentale africana di libero scambio riunisce 54 paesi in un unico mercato",
          "Si prevede che la popolazione urbana quasi raddoppi entro il 2050",
        ],
      },
      {
        id: "world",
        name: "Il mondo",
        kicker: "La tua porta sul continente",
        points: [
          "Padiglioni nazionali per Europa, Türkiye, Cina, India, Golfo e Americhe",
          "Incontra in un unico luogo importatori, distributori e agenti di tutta l’Africa",
          "Una piattaforma in nove lingue, aperta agli espositori di ogni paese",
        ],
      },
    ],
    offerTitle: "Cosa ottengono gli espositori",
    offerLead: "Tutto a SURMAT è costruito intorno a un risultato: mettere i tuoi prodotti davanti a chi li prescrive, li acquista e li posa.",
    offer: [
      {
        title: "Buyer qualificati",
        text: "Architetti, sviluppatori, imprese, distributori e acquirenti pubblici, registrati per profilo e per i materiali che cercano.",
      },
      { title: "Incontri fissati in anticipo", text: "I visitatori richiedono appuntamenti al tuo stand prima dell’apertura. Arrivi con un’agenda, non con una speranza." },
      { title: "Il distretto giusto", text: "Il tuo stand si trova tra i materiali che produci — proprio dove i progettisti vanno a confrontarli." },
      { title: "Uno showroom tutto l’anno", text: "Il tuo profilo nella libreria dei materiali SURMAT continua a lavorare dopo la fiera, in nove lingue." },
      { title: "Un palco per i lanci", text: "Presenta nuove collezioni e tecnologie nel programma di conferenze e dimostrazioni dal vivo." },
      { title: "Informazioni di mercato", text: "Scopri quali materiali e applicazioni suscitano più interesse in ogni mercato, edizione dopo edizione." },
    ],
    audienceTitle: "Chi incontrerai",
    audienceLead: "Solo visitatori professionali. Ognuno si registra con il proprio profilo e i materiali che cerca.",
    participateTitle: "Come partecipare",
    participate: [
      { title: "Stand", text: "Area libera o stand preallestito, da 9 m², nel distretto dei tuoi materiali." },
      { title: "Padiglione nazionale", text: "Esponi sotto la bandiera del tuo paese in un padiglione condiviso con promozione congiunta." },
      { title: "Sponsorizzazione", text: "Associa il tuo marchio alla fiera, al palco delle conferenze o al percorso dei visitatori." },
      { title: "Showroom digitale", text: "Non sei ancora pronto per uno stand? Inizia con un profilo nella libreria dei materiali online." },
    ],
    cta: "Richiedi uno stand",
    brochure: "Parla con il team commerciale",
  },
  universe: {
    title: "Scopri l’universo dei materiali",
    lead: "Esplora una ricca libreria di materiali di superficie e prodotti di finitura, dalla pietra naturale alle tecnologie più avanzate.",
    browse: "Tutti i materiali",
    explore: "Scopri il materiale",
    exhibitThis: "Esponi questo prodotto",
    prev: "Materiale precedente",
    next: "Materiale successivo",
    taglines: {
      "ceramic-porcelain": "Fatta per durare. Pensata per essere vista.",
      "natural-engineered-stone": "Bellezza naturale. Valore duraturo.",
      "paints-coatings": "Colore, texture e protezione.",
      "interior-finishing-systems": "I sistemi dietro ogni interno.",
      "construction-chemicals": "Ciò che tiene ogni superficie al suo posto.",
      "surface-technologies": "Dove nascono le superfici.",
    },
  },
  explorer: {
    alternatives: "Specificato anche per questa superficie",
    title: "Materiali per ogni spazio",
    lead: "Seleziona un punto dello spazio per vedere il materiale — e gli espositori che lo producono.",
    viewMaterial: "Vedi il materiale",
    findExhibitors: "Trova gli espositori",
    surfaces: { floor: "Pavimento", wall: "Pareti", feature: "Parete protagonista", counter: "Banco reception", ceiling: "Soffitto" },
  },
  leading: {
    title: "Espositori di riferimento",
    lead: "Produttori che presentano le loro collezioni a SURMAT — ognuno con il proprio showroom digitale.",
    discover: "Scopri l’espositore",
    featured: "Prodotti in evidenza",
  },
  split: {
    visitTitle: "Visita SURMAT",
    visitLead: "Registrati ora per partecipare alla fiera.",
    exhibitTitle: "Esponi a SURMAT",
    exhibitLead: "Presenta i tuoi prodotti a un pubblico qualificato di professionisti.",
  },
  success: {
    next: "I prossimi passi",
    calendar: "Aggiungi al calendario",
    visitSteps: [
      "Il badge arriva via e-mail prima dell’apertura.",
      "Richiedi incontri agli espositori dai loro showroom.",
      "Porta il badge sul telefono in fiera.",
    ],
    exhibitSteps: [
      "Un responsabile commerciale ti contatta con opzioni di stand e prezzi.",
      "Confermi il tuo spazio nel distretto dei tuoi materiali.",
      "Il tuo showroom digitale va online appena la partecipazione è confermata.",
    ],
  },
  pro: {
    title: "Area Pro",
    lead: "Uno spazio riservato a espositori e visitatori professionali, che apre prima di ogni edizione.",
    soon: "Apre agli espositori confermati prima dell’edizione",
    features: [
      "Dashboard espositore e gestione dei contatti",
      "Modifica del tuo showroom e del catalogo prodotti",
      "Richieste di incontro dai visitatori professionali",
      "Documenti, badge e informazioni pratiche",
    ],
    exhibitorCta: "Richiedi uno stand",
    visitorCta: "Registrati per visitare",
    contactCta: "Contatta il team SURMAT",
  },
  contact: {
    title: "Contatti",
    lead: "Dicci chi sei e di cosa hai bisogno. La persona giusta del team SURMAT ti risponderà.",
    topic: "Oggetto",
    topics: {
      exhibitor: "Esporre a SURMAT",
      visitor: "Visitare SURMAT",
      buyer: "Sourcing e acquisti",
      partner: "Partnership",
      media: "Stampa e media",
      speaker: "Intervenire alle conferenze",
      other: "Altro",
    },
    message: "Messaggio",
    submit: "Invia il messaggio",
    successTitle: "Messaggio inviato.",
    successLead: "Risponderemo a {email}.",
  },
  legal: {
    title: "Note legali",
    publisher: "Editore",
    pending: "I dati dell’editore saranno pubblicati qui prima del lancio.",
    hosting: "Hosting",
    hostingText: "Questo sito è ospitato da Vercel Inc., Stati Uniti.",
    ip: "Proprietà intellettuale",
    ipText: "Il nome SURMAT, i contenuti e il design di questo sito sono protetti. Nomi, loghi e immagini dei prodotti degli espositori appartengono ai rispettivi titolari e sono mostrati con il loro consenso.",
  },
  privacy: {
    title: "Privacy",
    lead: "Cosa raccoglie questo sito, perché e come contattarci in merito.",
    sections: [
      {
        title: "Cosa raccogliamo",
        text: "I dati che inserisci nei nostri moduli — nome, e-mail di lavoro, azienda, ruolo, telefono, paese e le tue risposte — insieme alla pagina e alla campagna che ti hanno portato a SURMAT.",
      },
      {
        title: "Perché",
        text: "Per registrare la tua visita, gestire la tua domanda di partecipazione o rispondere al tuo messaggio. Ti contattiamo sull’edizione solo se spunti la casella del consenso.",
      },
      {
        title: "Statistiche",
        text: "Registriamo interazioni anonime — materiali visti, ricerche, clic sulle call to action — per migliorare la piattaforma e capire quali materiali suscitano interesse. Non sono collegate al tuo nome.",
      },
      { title: "Cookie", text: "Conserviamo due cookie di preferenza, l’edizione e la lingua, per un anno. Questo sito non usa cookie pubblicitari." },
      { title: "I tuoi diritti", text: "Puoi chiedere in qualsiasi momento di vedere, correggere o cancellare i tuoi dati scrivendo al team SURMAT." },
    ],
  },
  event: {
    bandTitle: "Vederlo, toccarlo, sceglierlo — di persona",
    bar: "Fiera professionale internazionale",
    bookStand: "Prenota uno stand",
    freeVisit: "Registrazione gratuita",
    visual: "Visualizzazione",
    eyebrow: "La fiera",
    title: "Dove l’industria delle finiture si incontra di persona",
    lead: "SURMAT è un evento professionale dal vivo, non un catalogo. Gli espositori presentano i prodotti allo stand, buyer e progettisti vengono a selezionare fornitori e i progetti si discutono al tavolo — a Orano e a Dakar.",
    pillars: [
      {
        title: "Area espositiva",
        text: "Centinaia di stand organizzati per distretto di materiali: toccare, confrontare e trovare ogni prodotto in una sola visita.",
      },
      { title: "Incontri B2B", text: "Appuntamenti prefissati tra espositori, distributori, sviluppatori, architetti e committenti pubblici." },
      {
        title: "Conferenze e presentazioni di progetti",
        text: "Architetti, sviluppatori ed enti pubblici presentano i progetti che avranno bisogno di questi materiali.",
      },
      { title: "Dimostrazioni e lanci", text: "Dimostrazioni di posa, macchinari in funzione e nuove collezioni svelate in fiera." },
    ],
    exhibitors: "{n} espositori",
    visitors: "{n} visitatori professionali",
    visitPoints: [
      "Ingresso gratuito per i professionisti",
      "Tutti i prodotti di finitura in una visita",
      "Incontra produttori e distributori di persona",
    ],
    exhibitPoints: [
      "Incontra buyer e progettisti qualificati",
      "Incontri B2B prefissati al tuo stand",
      "Lancia i prodotti sui mercati africani",
    ],
  },
  scope: {
    statDistricts: "Distretti",
    statFamilies: "Famiglie di prodotti",
    district: "Distretto",
    bookHere: "Prenota uno stand in questo distretto",
    eyebrow: "Perimetro della fiera",
    title: "Nove distretti. Tutta l’industria delle finiture.",
    lead: "La materioteca mostra degli esempi. La fiera è organizzata in nove distretti che coprono tutto ciò che riveste, rifinisce, protegge o attrezza un edificio. Scegli un distretto per vedere chi espone.",
    core: "Settore principale",
    adjacent: "Benvenuti anche",
    families: "{n} famiglie",
    missing: "Non trovi il tuo prodotto?",
    missingText: "Se riveste, rifinisce, protegge o attrezza un edificio, ha il suo posto a SURMAT. Dicci cosa produci e ti collocheremo nel distretto giusto.",
    cta: "Proponi il mio prodotto",
    count: "{m} materiali documentati · {f} famiglie di prodotti ammesse in fiera",
  },
  partners: {
    eyebrow: "Opportunità di partnership",
    title: "Porta SURMAT nel tuo Paese",
    lead: "SURMAT è pensato per viaggiare. Agenzie di eventi, associazioni di categoria e camere di commercio possono portare il format nel loro mercato — con il nostro marchio, la piattaforma, la rete di espositori e il metodo alle spalle.",
    cta: "Candidati come partner",
    mapLabel: "Algeria e Senegal oggi — il tuo mercato domani",
    formatsTitle: "Tre modi per collaborare",
    formats: [
      {
        title: "Edizione in licenza",
        text: "Organizza SURMAT nel tuo Paese con una licenza in franchising.",
        points: [
          "Uso completo del marchio e del format SURMAT",
          "Pianta in nove distretti e tassonomia dei materiali",
          "La tua edizione su questa piattaforma, in nove lingue",
        ],
      },
      {
        title: "Edizione co-organizzata",
        text: "Lanciamo insieme una nuova edizione, condividendo investimento e risultati.",
        points: [
          "Business plan e budget comuni",
          "Team vendite ed espositori internazionali condivisi",
          "Supporto operativo SURMAT in loco",
        ],
      },
      {
        title: "Agente e padiglione nazionale",
        text: "Rappresenta SURMAT nel tuo Paese e porta le tue aziende alle nostre edizioni.",
        points: [
          "Commissione sugli stand venduti",
          "Organizzazione del padiglione nazionale del tuo Paese",
          "Delegazioni di buyer a Orano e Dakar",
        ],
      },
    ],
    weBringTitle: "Cosa porta SURMAT",
    weBring: [
      "Un marchio e un format fieristico consolidati",
      "La piattaforma digitale: materioteca, showroom espositori, registrazioni",
      "Espositori internazionali e programma hosted buyer",
      "Metodo commerciale, modello di prezzi e formazione",
      "Kit marketing, contenuti e campagne in nove lingue",
      "Manuali operativi e supporto in loco",
    ],
    youBringTitle: "Cosa porti tu",
    youBring: [
      "Conoscenza del tuo mercato delle costruzioni",
      "Relazioni con sedi, autorità e associazioni",
      "Un team locale vendite e marketing",
      "Rete logistica e di fornitori",
      "Impegno verso gli standard di qualità SURMAT",
    ],
    stepsTitle: "Come funziona",
    steps: [
      { title: "Candidatura", text: "Raccontaci la tua organizzazione e il tuo mercato." },
      { title: "Studio di mercato", text: "Valutiamo insieme l’opportunità." },
      { title: "Accordo", text: "Scegliamo il modello di partnership e firmiamo." },
      { title: "Lancio", text: "La tua edizione SURMAT va online sulla piattaforma." },
    ],
    who: "Per organizzatori di eventi, agenzie fieristiche, associazioni di categoria, camere di commercio e investitori in Africa, Medio Oriente e oltre.",
    applyTitle: "Avvia il dialogo",
    applyLead: "Condividi alcune informazioni: il team partnership di SURMAT risponderà entro cinque giorni lavorativi.",
    homeTitle: "Il tuo Paese è il prossimo?",
    homeLead: "Porta SURMAT nel tuo mercato come edizione in licenza o co-organizzata.",
  },
  systems: {
    eyebrow: "Come si costruisce",
    title: "Ogni sistema, strato per strato",
    lead: "Dietro ogni superficie c’è un sistema di prodotti: pannelli, sottostrutture, isolanti, membrane, adesivi, massetti, lastre e finiture — e le macchine che li producono. Scegli un sistema e poi uno strato per vedere cos’è, la specifica tipica e dove espongono i produttori.",
    onSite: "In cantiere",
    section: "Sezione tecnica",
    process: "Linea di produzione",
    layers: "strati",
    steps: "stazioni",
    outside: "Esterno",
    inside: "Interno",
    top: "Sopra",
    district: "Distretto",
    structure: "Struttura dell’edificio — non è una categoria di prodotto",
    note: "Specifiche tipiche a scopo illustrativo. Verificare le schede tecniche dei produttori e le norme locali.",
  },
  board: {
    eyebrow: "Campionario e render studio",
    title: "Dal campione allo spazio",
    lead: "Ogni famiglia di prodotti in fiera, come la specifica un architetto: campioni reali sulla tavola, la famiglia in uso con i suoi punti tecnici e il distretto dove espongono i produttori.",
    sampleBoard: "Tavola dei materiali",
    exhibitedIn: "Esposto nel",
    district: "Distretto",
    palette: "La palette",
    synthTitle: "Un edificio, tutti i distretti",
    synthLead: "Dodici campioni, un progetto: indica un campione per vedere dove va — facciata, terrazza, ufficio, hall, bagno.",
    open: "Apri il campionario",
    pageTitle: "Il campionario",
    pageLead: "Una guida alla specifica dalla fiera al cantiere: ogni famiglia di prodotti con campioni, impieghi e punti tecnici.",
  },
  sector: {
    materials: "Materiali di questo settore",
    exhibitors: "Espositori di questo distretto",
    district: "Distretto",
  },
  material: {
    sector: "Settore",
    finishes: "Finiture",
    applications: "Applicazioni",
    formats: "Formati",
    spec: "Gamma tipica",
    exhibitors: "Espositori che presentano questo materiale",
    noExhibitors: "Nessun espositore ha ancora confermato questo materiale. Il tuo potrebbe essere il primo.",
    related: "Materiali correlati",
    manufacturerQ: "Produci {material}?",
    usedIn: "Usato in:",
  },
  catalogue: {
    title: "Libreria dei materiali",
    lead: "Tutti i materiali presentati a SURMAT, organizzati per settore. Ognuno porta alle aziende che lo producono.",
    all: "Tutti i settori",
    search: "Filtra i materiali",
    noResults: "Nessun materiale corrisponde a “{q}”. Prova una parola più ampia come “pietra” o “piastrella”.",
    count: "{n} materiali",
  },
  apps: {
    allSpaces: "Tutti gli spazi",
    stats: "{m} materiali · {e} espositori",
    title: "Applicazioni",
    lead: "Parti dallo spazio che stai costruendo e incontra gli espositori che ne forniscono ogni superficie.",
    materialsUsed: "Materiali in questo spazio",
    suppliers: "Espositori che forniscono questi materiali",
  },
  exhibitors: {
    title: "Espositori",
    lead: "Esplora le aziende presenti a SURMAT in base ai materiali che producono.",
    sample: "Profilo di esempio",
    sampleNote: "I profili di esempio mostrano come appariranno gli showroom degli espositori. Gli espositori confermati vengono pubblicati man mano che firmano.",
    district: "Distretto",
    stand: "Stand",
    requestMeeting: "Richiedi un incontro",
    visitStand: "Trova lo stand",
    products: "Parete prodotti",
    materials: "Materiali",
    markets: "Mercati",
    founded: "Fondata nel",
    all: "Tutti",
    empty: "Ancora nessun espositore in questo settore.",
  },
  experience: {
    zones: {
      conference: "Sala conferenze",
      conferenceSub: "Talk, tavole rotonde, presentazioni di progetti",
      b2b: "Lounge incontri B2B",
      b2bSub: "Appuntamenti prefissati con i buyer",
      demo: "Palco demo live",
      demoSub: "Demo di posa e macchinari",
      aisle: "Corridoio principale",
      pavilions: "Padiglioni nazionali",
      lounge: "Lounge e caffè",
      registration: "Accrediti",
      entrance: "Ingresso principale",
    },
    legendTaken: "Stand prenotato",
    title: "L’esperienza SURMAT",
    lead: "Nove distretti, una sala conferenze, una lounge B2B e un palco demo. Percorri la pianta, trova uno stand, prenota il tuo.",
    mapTitle: "Planimetria della fiera",
    mapHint: "Seleziona uno stand per vedere chi espone.",
    open: "Apri lo stand",
    available: "Stand disponibile",
    availableLead: "Questo stand è disponibile per la prenotazione.",
    book: "Prenota questo stand",
    teaserTitle: "Più di una fiera",
    teaserLead: "Un percorso immersivo tra materiali, applicazioni, innovazione e competenze del settore.",
    central: "Spazio centrale",
    branches: [
      "Planimetria",
      "Distretti dei materiali",
      "Conferenze",
      "Dimostrazioni di prodotto",
      "Networking",
    ],
  },
  visit: {
    title: "Visita SURMAT",
    lead: "Quattro giorni con i produttori di ogni superficie di un edificio. La registrazione è gratuita per i professionisti.",
    who: "Chi visita",
    profiles: {
      architect: "Architetto o interior designer",
      developer: "Sviluppatore o committente",
      contractor: "Impresa o posatore",
      distributor: "Distributore o rivenditore",
      buyer: "Buyer o ufficio acquisti",
      manufacturer: "Produttore",
      other: "Altro professionista",
    },
    formTitle: "Registrati per visitare",
    profile: "Il tuo profilo",
    interests: "Materiali che cerchi",
    submit: "Registrati per visitare",
    successTitle: "Sei registrato.",
    successLead: "Il tuo badge sarà inviato a {email} prima dell’apertura della fiera.",
    meetingWith: "Richiesta di incontro con {name}",
  },
  exhibit: {
    title: "Esponi a SURMAT",
    lead: "Il posto dei tuoi prodotti è qui.",
    why: [
      "Architetti, sviluppatori, imprese e distributori da Algeria, Senegal e tutta l’Africa",
      "Il tuo stand è nel distretto dei tuoi materiali, dove i progettisti vengono a cercarli",
      "I tuoi prodotti restano online tutto l’anno nella libreria dei materiali SURMAT, in nove lingue",
    ],
    steps: ["Materiali", "Azienda", "Portfolio", "Spazio", "Contatto"],
    manufacture: "Che cosa produci?",
    companyTitle: "Parlaci della tua azienda",
    portfolioTitle: "Che cosa esporrai?",
    spaceTitle: "Di quanto spazio hai bisogno?",
    contactTitle: "Chi dobbiamo contattare?",
    companyName: "Nome dell’azienda",
    website: "Sito web",
    country: "Paese",
    families: "Famiglie di prodotti",
    brands: "Marchi",
    machinery: "Faremo dimostrazioni di macchinari",
    demo: "Vogliamo un’area per dimostrazioni dal vivo",
    meetingRoom: "Ci serve un’area riunioni riservata",
    description: "Prodotti che intendi presentare",
    recommended: "In base al tuo portfolio, SURMAT consiglia {min}–{max} m².",
    requested: "Superficie richiesta (m²)",
    edition: "Edizione",
    back: "Indietro",
    next: "Continua",
    submit: "Invia la domanda",
    successTitle: "Il posto dei tuoi prodotti è a SURMAT.",
    successLead: "Un responsabile commerciale SURMAT contatterà {email} con le opzioni di stand nel distretto {sector}.",
    pickOne: "Seleziona almeno un settore per continuare.",
  },
  form: {
    name: "Nome e cognome",
    role: "Ruolo",
    company: "Azienda",
    email: "E-mail di lavoro",
    phone: "Telefono",
    country: "Paese",
    required: "Obbligatorio",
    invalidEmail: "Inserisci un indirizzo come nome@azienda.com.",
    error: "Impossibile inviare il modulo. Controlla la connessione e riprova.",
    sending: "Invio in corso…",
    consent: "SURMAT può contattarmi in merito a questa edizione.",
  },
  cta: {
    dialogTitle: "Esponi a SURMAT",
    dialogLead: "Il posto dei tuoi prodotti è qui.",
    apply: "Richiedi uno stand",
    close: "Chiudi",
  },
  edition: {
    datesTBA: "Date da annunciare",
    venueTBA: "Sede da annunciare",
    switchTo: "Passa a {name}",
  },
  search: {
    title: "Cerca in SURMAT",
    placeholder: "Materiale, spazio o azienda — es. “pavimento in marmo hotel”",
    materials: "Materiali",
    sectors: "Settori",
    applications: "Applicazioni",
    exhibitors: "Espositori",
    empty: "Scrivi un materiale, uno spazio o un’azienda.",
    none: "Nessun risultato per “{q}”. Prova un solo materiale, come “gres”.",
    popularMaterials: "Materiali più cercati",
    popularApplications: "Applicazioni più cercate",
    featuredExhibitors: "Espositori in evidenza",
  },
  footer: {
    tagline: "La fiera internazionale dei materiali di superficie e dei prodotti di finitura per l’edilizia.",
    rights: "© {year} SURMAT. Tutti i diritti riservati.",
    platform: "Piattaforma",
    editions: "Edizioni",
    languages: "Lingue",
    legal: "Note legali",
    privacy: "Privacy",
    contact: "Contatti",
  },
  common: { back: "Indietro", all: "Tutti", learnMore: "Scopri di più", of: "di", explore: "Scopri" },
  vocab: {
    matt: "Opaco", polished: "Lucido", honed: "Levigato", textured: "Strutturato", antiSlip: "Antiscivolo",
    brushed: "Spazzolato", glossy: "Brillante", satin: "Satinato", leather: "Anticato", flamed: "Fiammato",
    bushHammered: "Bocciardato", metallic: "Metallico", velvet: "Vellutato", raw: "Naturale",
    tile: "Piastrella", largeFormat: "Grande formato", slab: "Lastra", mosaic: "Mosaico", block: "Blocco",
    board: "Lastra", panel: "Pannello", roll: "Rotolo", liquid: "Liquido", powder: "Polvere", paste: "Pasta",
    cartridge: "Cartuccia", line: "Linea di produzione", machine: "Macchina", module: "Modulo",
  },
};
