import type { Dict } from "./en";

export const pt: Dict = {
  brand: {
    descriptor: "Materiais de superfície e produtos de acabamento para a construção",
    eyebrow: "A feira internacional de",
  },
  nav: {
    partners: "Parcerias",
    materials: "Materiais",
    applications: "Aplicações",
    exhibitors: "Expositores",
    experience: "Experiência",
    visit: "Visitar",
    exhibit: "Expor",
    register: "Registar-se para visitar",
    search: "Pesquisar",
    menu: "Menu",
    close: "Fechar",
    edition: "Edição",
    language: "Idioma",
    skip: "Ir para o conteúdo",
    pro: "Espaço Pro",
  },
  hero: {
    explore: "Explorar materiais",
    exhibit: "Expor na SURMAT",
    visit: "Visitar a SURMAT",
    searchLabel: "Pesquisar no universo de materiais",
    searchPlaceholder: "Experimente “mármore”, “piso de hotel” ou “impermeabilização”",
    matches: "{n} materiais em destaque",
    noMatch: "Nada no universo corresponde ainda a “{q}”",
    clear: "Limpar pesquisa",
    close: "Voltar ao universo",
    exploreMaterial: "Ver o material",
    findExhibitors: "Encontrar expositores",
    usedIn: "Utilizado em",
    format: "Formato",
    hint: "Arraste para rodar o universo. Selecione uma amostra para a trazer para a frente.",
    scroll: "Deslize para explorar",
    tagline: "Os materiais moldam espaços melhores",
  },
  stats: {
    sectors: "Setores de materiais",
    editions: "Edições",
    exhibitors: "Expositores (objetivo)",
    visitors: "Visitantes profissionais (objetivo)",
    hub: "Um polo regional para oportunidades globais",
  },
  home: {
    materialsTitle: "Explore o mundo dos materiais",
    materialsLead: "Da pedra natural aos sistemas de acabamento mais avançados — seis setores que moldam a arquitetura moderna.",
    viewAll: "Ver todos os materiais",
    spacesTitle: "Os materiais tornam-se espaços",
    spacesLead: "Cada material da SURMAT acaba num hotel, numa casa, num hospital ou num edifício público. Comece pelo espaço.",
    exploreApps: "Ver todas as aplicações",
    industryTitle: "Conheça a indústria",
    industryLead: "Fabricantes, fornecedores e inovadores que apresentam as suas coleções na SURMAT.",
    viewExhibitors: "Ver expositores",
    experienceTitle: "Viva a SURMAT",
    experienceLead: "Percorra os seis distritos da feira e encontre cada stand pelo material que apresenta.",
    exploreExperience: "Descobrir a experiência",
    editionsTitle: "Edições da SURMAT",
    editionsLead: "Dois mercados. Um universo de materiais.",
    exploreEdition: "Ver a edição",
    current: "Está aqui",
    visitTitle: "Venha tocar nos materiais",
    visitLead: "O registo é gratuito para arquitetos, promotores, empreiteiros, distribuidores e compradores.",
    exhibitTitle: "Os seus produtos pertencem aqui",
    exhibitLead: "Coloque as suas coleções diante de quem as prescreve, compra e aplica.",
    editionsHeadline: "Duas edições. Uma plataforma.",
  },
  why: {
    eyebrow: "Porquê expor",
    title: "Um stand. Quatro mercados.",
    lead: "A SURMAT liga os fabricantes de cada superfície de um edifício a quem constrói o Norte e o Oeste de África — e abre às empresas de todo o mundo uma porta para o continente.",
    markets: [
      {
        id: "dz",
        name: "Argélia",
        kicker: "O maior mercado do Norte de África",
        points: [
          "O maior país de África em superfície, com cerca de 47 milhões de habitantes",
          "Programas contínuos de habitação, infraestruturas, hotelaria e edifícios públicos",
          "Uma ponte entre o Magrebe, o Mediterrâneo e o Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "A porta da África Ocidental",
        points: [
          "Dacar: um polo de negócios estável e em rápido crescimento no Atlântico",
          "Membro da CEDEAO (15 países) e da UEMOA (8 países que partilham o franco CFA)",
          "Novas cidades, portos, hotéis e equipamentos públicos em construção",
        ],
      },
      {
        id: "africa",
        name: "África",
        kicker: "O próximo boom da construção",
        points: [
          "Mais de 1,4 mil milhões de pessoas — a população mais jovem do mundo",
          "A Zona de Comércio Livre Continental Africana reúne 54 países num só mercado",
          "Prevê-se que a população urbana quase duplique até 2050",
        ],
      },
      {
        id: "world",
        name: "O mundo",
        kicker: "A sua porta para o continente",
        points: [
          "Pavilhões nacionais para a Europa, Türkiye, China, Índia, o Golfo e as Américas",
          "Encontre num só lugar importadores, distribuidores e agentes de toda a África",
          "Uma plataforma em nove idiomas, aberta a expositores de todos os países",
        ],
      },
    ],
    offerTitle: "O que os expositores recebem",
    offerLead: "Tudo na SURMAT é construído em torno de um resultado: colocar os seus produtos diante de quem os prescreve, compra e aplica.",
    offer: [
      {
        title: "Compradores qualificados",
        text: "Arquitetos, promotores, empreiteiros, distribuidores e compradores públicos, registados por perfil e pelos materiais que procuram.",
      },
      { title: "Reuniões marcadas com antecedência", text: "Os visitantes pedem reuniões no seu stand antes da abertura. Chega com uma agenda, não com uma esperança." },
      { title: "O distrito certo", text: "O seu stand fica entre os materiais que fabrica — exatamente onde os prescritores os vão comparar." },
      { title: "Um showroom todo o ano", text: "O seu perfil na biblioteca de materiais da SURMAT continua a trabalhar depois da feira, em nove idiomas." },
      { title: "Um palco para lançamentos", text: "Apresente novas coleções e tecnologias no programa de conferências e demonstrações ao vivo." },
      { title: "Inteligência de mercado", text: "Veja que materiais e aplicações despertam mais interesse em cada mercado, edição após edição." },
    ],
    audienceTitle: "Quem vai conhecer",
    audienceLead: "Apenas visitantes profissionais. Cada um regista-se com o seu perfil e os materiais que procura.",
    participateTitle: "Formas de participar",
    participate: [
      { title: "Stand", text: "Espaço livre ou stand modular, a partir de 9 m², no distrito dos seus materiais." },
      { title: "Pavilhão nacional", text: "Exponha sob a bandeira do seu país num pavilhão partilhado com promoção conjunta." },
      { title: "Patrocínio", text: "Associe a sua marca à feira, ao palco de conferências ou ao percurso do visitante." },
      { title: "Showroom digital", text: "Ainda não está pronto para um stand? Comece com um perfil na biblioteca de materiais online." },
    ],
    cta: "Pedir um stand",
    brochure: "Falar com a equipa comercial",
  },
  universe: {
    title: "Descubra o universo dos materiais",
    lead: "Explore uma rica biblioteca de materiais de superfície e produtos de acabamento, da pedra natural às tecnologias mais avançadas.",
    browse: "Ver todos os materiais",
    explore: "Ver o material",
    exhibitThis: "Expor este produto",
    prev: "Material anterior",
    next: "Material seguinte",
    taglines: {
      "ceramic-porcelain": "Feita para durar. Pensada para ser vista.",
      "natural-engineered-stone": "Beleza natural. Valor duradouro.",
      "paints-coatings": "Cor, textura e proteção.",
      "interior-finishing-systems": "Os sistemas por trás de cada interior.",
      "construction-chemicals": "O que segura cada superfície.",
      "surface-technologies": "Onde nascem as superfícies.",
    },
  },
  explorer: {
    alternatives: "Também especificado para esta superfície",
    title: "Materiais para cada espaço",
    lead: "Selecione um ponto do espaço para ver o material — e os expositores que o fabricam.",
    viewMaterial: "Ver o material",
    findExhibitors: "Encontrar expositores",
    surfaces: { floor: "Pavimento", wall: "Paredes", feature: "Parede de destaque", counter: "Balcão de receção", ceiling: "Teto" },
  },
  leading: {
    title: "Expositores de referência",
    lead: "Fabricantes que apresentam as suas coleções na SURMAT — cada um com o seu showroom digital.",
    discover: "Descobrir o expositor",
    featured: "Produtos em destaque",
  },
  split: {
    visitTitle: "Visitar a SURMAT",
    visitLead: "Registe-se já para participar na feira.",
    exhibitTitle: "Expor na SURMAT",
    exhibitLead: "Apresente os seus produtos a um público profissional qualificado.",
  },
  success: {
    next: "Próximos passos",
    calendar: "Adicionar ao calendário",
    visitSteps: [
      "A sua credencial chega por e-mail antes da abertura.",
      "Peça reuniões aos expositores a partir dos seus showrooms.",
      "Traga a credencial no telemóvel para a feira.",
    ],
    exhibitSteps: [
      "Um gestor comercial contacta-o com opções de stand e preços.",
      "Confirma o seu espaço no distrito dos seus materiais.",
      "O seu showroom digital é publicado assim que a participação é confirmada.",
    ],
  },
  pro: {
    title: "Espaço Pro",
    lead: "Um espaço privado para expositores e visitantes profissionais, que abre antes de cada edição.",
    soon: "Abre aos expositores confirmados antes da edição",
    features: [
      "Painel do expositor e gestão de contactos",
      "Edição do seu showroom e do seu catálogo",
      "Pedidos de reunião de visitantes profissionais",
      "Documentos, credenciais e informações práticas",
    ],
    exhibitorCta: "Pedir um stand",
    visitorCta: "Registar-se para visitar",
    contactCta: "Contactar a equipa SURMAT",
  },
  contact: {
    title: "Contacto",
    lead: "Diga-nos quem é e do que precisa. A pessoa certa da equipa SURMAT responderá.",
    topic: "Assunto",
    topics: {
      exhibitor: "Expor na SURMAT",
      visitor: "Visitar a SURMAT",
      buyer: "Aprovisionamento e compras",
      partner: "Parceria",
      media: "Imprensa e media",
      speaker: "Intervir nas conferências",
      other: "Outro",
    },
    message: "Mensagem",
    submit: "Enviar mensagem",
    successTitle: "Mensagem enviada.",
    successLead: "Responderemos para {email}.",
  },
  legal: {
    title: "Aviso legal",
    publisher: "Editor",
    pending: "Os dados do editor serão publicados aqui antes do lançamento.",
    hosting: "Alojamento",
    hostingText: "Este site está alojado pela Vercel Inc., Estados Unidos.",
    ip: "Propriedade intelectual",
    ipText: "O nome SURMAT, os conteúdos e o design deste site estão protegidos. Os nomes, logótipos e imagens de produto dos expositores pertencem aos respetivos titulares e são apresentados com a sua autorização.",
  },
  privacy: {
    title: "Privacidade",
    lead: "O que este site recolhe, porquê e como nos contactar sobre isso.",
    sections: [
      {
        title: "O que recolhemos",
        text: "Os dados que introduz nos nossos formulários — nome, e-mail profissional, empresa, cargo, telefone, país e as suas respostas — juntamente com a página e a campanha que o trouxeram à SURMAT.",
      },
      {
        title: "Porquê",
        text: "Para registar a sua visita, tratar a sua candidatura de expositor ou responder à sua mensagem. Só o contactamos sobre a edição se assinalar a caixa de consentimento.",
      },
      {
        title: "Estatísticas",
        text: "Registamos interações anónimas — materiais vistos, pesquisas, cliques em chamadas à ação — para melhorar a plataforma e perceber que materiais despertam interesse. Não estão ligadas ao seu nome.",
      },
      {
        title: "Cookies",
        text: "Guardamos dois cookies de preferências, a sua edição e o seu idioma, durante um ano. Este site não utiliza cookies de publicidade.",
      },
      { title: "Os seus direitos", text: "Pode pedir a qualquer momento para ver, corrigir ou apagar os seus dados escrevendo à equipa SURMAT." },
    ],
  },
  event: {
    bandTitle: "Ver, tocar, comprar — ao vivo",
    bar: "Feira profissional internacional",
    bookStand: "Reservar um stand",
    freeVisit: "Registo gratuito",
    visual: "Visualização",
    eyebrow: "A feira",
    title: "Onde a indústria dos acabamentos se encontra frente a frente",
    lead: "A SURMAT é um evento profissional ao vivo, não um catálogo. Os expositores apresentam os seus produtos no stand, compradores e prescritores vêm abastecer-se e os projetos discutem-se à mesa — em Orão e em Dacar.",
    pillars: [
      { title: "Área de exposição", text: "Centenas de stands organizados por distrito de materiais — tocar, comparar e encontrar cada produto numa só visita." },
      { title: "Networking B2B", text: "Reuniões pré-agendadas entre expositores, distribuidores, promotores, arquitetos e compradores públicos." },
      {
        title: "Conferências e apresentação de projetos",
        text: "Arquitetos, promotores e donos de obra públicos apresentam os projetos que vão precisar destes materiais.",
      },
      { title: "Demonstrações e lançamentos", text: "Demonstrações de aplicação, máquinas em funcionamento e novas coleções reveladas na feira." },
    ],
    exhibitors: "{n} expositores",
    visitors: "{n} visitantes profissionais",
    visitPoints: [
      "Entrada gratuita para profissionais",
      "Todos os produtos de acabamento numa visita",
      "Conheça fabricantes e distribuidores pessoalmente",
    ],
    exhibitPoints: [
      "Conheça compradores e prescritores qualificados",
      "Reuniões B2B agendadas no seu stand",
      "Lance produtos nos mercados africanos",
    ],
  },
  scope: {
    statDistricts: "Distritos",
    statFamilies: "Famílias de produtos",
    district: "Distrito",
    bookHere: "Reservar um stand neste distrito",
    eyebrow: "Âmbito da feira",
    title: "Nove distritos. Toda a indústria dos acabamentos.",
    lead: "A biblioteca de materiais mostra exemplos. A feira organiza-se em nove distritos que cobrem tudo o que reveste, acaba, protege ou equipa um edifício. Escolha um distrito para ver quem expõe lá.",
    core: "Setor principal",
    adjacent: "Também bem-vindos",
    families: "{n} famílias",
    missing: "Não vê o seu produto?",
    missingText: "Se reveste, acaba, protege ou equipa um edifício, tem lugar na SURMAT. Diga-nos o que fabrica e colocamo-lo no distrito certo.",
    cta: "Propor o meu produto",
    count: "{m} materiais documentados · {f} famílias de produtos aceites na feira",
  },
  partners: {
    eyebrow: "Oportunidade de parceria",
    title: "Leve a SURMAT ao seu país",
    lead: "A SURMAT foi feita para viajar. Agências de eventos, associações setoriais e câmaras de comércio podem levar o formato ao seu mercado — com a nossa marca, plataforma, rede de expositores e método por trás.",
    cta: "Candidatar-se a parceiro",
    mapLabel: "Argélia e Senegal hoje — o seu mercado a seguir",
    formatsTitle: "Três formas de parceria",
    formats: [
      {
        title: "Edição licenciada",
        text: "Organize a SURMAT no seu país sob licença de franquia.",
        points: [
          "Uso total da marca e do formato SURMAT",
          "Planta de nove distritos e taxonomia de materiais",
          "A sua edição nesta plataforma, em nove idiomas",
        ],
      },
      {
        title: "Edição coorganizada",
        text: "Lançamos juntos uma nova edição, partilhando investimento e resultados.",
        points: [
          "Plano de negócios e orçamento conjuntos",
          "Equipa comercial e expositores internacionais partilhados",
          "Apoio operacional da SURMAT no local",
        ],
      },
      {
        title: "Agente e pavilhão nacional",
        text: "Represente a SURMAT no seu país e leve as suas empresas às nossas edições.",
        points: [
          "Comissão sobre os stands que vender",
          "Organização do pavilhão nacional do seu país",
          "Delegações de compradores a Orão e Dacar",
        ],
      },
    ],
    weBringTitle: "O que a SURMAT traz",
    weBring: [
      "Uma marca e um formato de feira consolidados",
      "A plataforma digital: biblioteca de materiais, showrooms de expositores, registo",
      "Expositores internacionais e programa de compradores convidados",
      "Método comercial, modelo de preços e formação",
      "Kit de marketing, conteúdos e campanhas em nove idiomas",
      "Manuais operacionais e apoio no local",
    ],
    youBringTitle: "O que você traz",
    youBring: [
      "Conhecimento do seu mercado da construção",
      "Relações com recintos, autoridades e associações",
      "Uma equipa local de vendas e marketing",
      "Rede logística e de fornecedores",
      "Compromisso com os padrões de qualidade SURMAT",
    ],
    stepsTitle: "Como funciona",
    steps: [
      { title: "Candidatura", text: "Apresente a sua organização e o seu mercado." },
      { title: "Estudo de mercado", text: "Avaliamos a oportunidade em conjunto." },
      { title: "Acordo", text: "Escolhemos o modelo de parceria e assinamos." },
      { title: "Lançamento", text: "A sua edição SURMAT entra na plataforma." },
    ],
    who: "Para organizadores de eventos, agências de feiras, associações setoriais, câmaras de comércio e investidores em África, no Médio Oriente e além.",
    applyTitle: "Comece a conversa",
    applyLead: "Partilhe alguns dados e a equipa de parcerias da SURMAT responderá em cinco dias úteis.",
    homeTitle: "O seu país é o próximo?",
    homeLead: "Leve a SURMAT ao seu mercado como edição licenciada ou coorganizada.",
  },
  systems: {
    eyebrow: "Como se constrói",
    title: "Cada sistema, camada a camada",
    lead: "Por trás de cada superfície há um sistema de produtos: painéis, subestruturas, isolamentos, membranas, colas, betonilhas, placas e acabamentos — e as máquinas que os fabricam. Escolha um sistema e depois uma camada para ver o que é, a especificação típica e onde expõem os fabricantes.",
    onSite: "Em obra",
    section: "Corte técnico",
    process: "Linha de produção",
    layers: "camadas",
    steps: "estações",
    outside: "Exterior",
    inside: "Interior",
    top: "Topo",
    district: "Distrito",
    structure: "Estrutura do edifício — não é categoria de produto",
    note: "Especificações típicas para ilustração. Consulte as fichas técnicas dos fabricantes e a regulamentação local.",
  },
  sector: {
    materials: "Materiais deste setor",
    exhibitors: "Expositores deste distrito",
    district: "Distrito",
  },
  material: {
    sector: "Setor",
    finishes: "Acabamentos",
    applications: "Aplicações",
    formats: "Formatos",
    spec: "Gama habitual",
    exhibitors: "Expositores que apresentam este material",
    noExhibitors: "Nenhum expositor confirmou ainda este material. O seu pode ser o primeiro.",
    related: "Materiais relacionados",
    manufacturerQ: "Fabrica {material}?",
    usedIn: "Utilizado em:",
  },
  catalogue: {
    title: "Biblioteca de materiais",
    lead: "Todos os materiais apresentados na SURMAT, organizados por setor. Cada um leva às empresas que o fabricam.",
    all: "Todos os setores",
    search: "Filtrar materiais",
    noResults: "Nenhum material corresponde a “{q}”. Experimente uma palavra mais ampla como “pedra” ou “ladrilho”.",
    count: "{n} materiais",
  },
  apps: {
    allSpaces: "Todos os espaços",
    stats: "{m} materiais · {e} expositores",
    title: "Aplicações",
    lead: "Comece pelo espaço que está a construir e conheça os expositores que fornecem cada uma das suas superfícies.",
    materialsUsed: "Materiais neste espaço",
    suppliers: "Expositores que fornecem estes materiais",
  },
  exhibitors: {
    title: "Expositores",
    lead: "Explore as empresas presentes na SURMAT pelos materiais que fabricam.",
    sample: "Perfil de exemplo",
    sampleNote: "Os perfis de exemplo mostram como vão ficar os showrooms dos expositores. Os expositores confirmados são publicados à medida que assinam.",
    district: "Distrito",
    stand: "Stand",
    requestMeeting: "Pedir uma reunião",
    visitStand: "Encontrar o stand",
    products: "Parede de produtos",
    materials: "Materiais",
    markets: "Mercados",
    founded: "Fundada em",
    all: "Todos",
    empty: "Ainda não há expositores neste setor.",
  },
  experience: {
    zones: {
      conference: "Sala de conferências",
      conferenceSub: "Palestras, painéis, apresentação de projetos",
      b2b: "Lounge de reuniões B2B",
      b2bSub: "Reuniões agendadas com compradores",
      demo: "Palco de demonstrações",
      demoSub: "Demos de aplicação e máquinas",
      aisle: "Corredor principal",
      pavilions: "Pavilhões nacionais",
      lounge: "Lounge e café",
      registration: "Acreditação",
      entrance: "Entrada principal",
    },
    legendTaken: "Stand reservado",
    title: "A experiência SURMAT",
    lead: "Nove distritos, uma sala de conferências, um lounge B2B e um palco de demonstrações. Percorra a planta, encontre um stand, reserve o seu.",
    mapTitle: "Planta da feira",
    mapHint: "Selecione um stand para ver quem expõe.",
    open: "Ver o stand",
    available: "Stand disponível",
    availableLead: "Este stand está disponível para reserva.",
    book: "Reservar este stand",
    teaserTitle: "Mais do que uma feira",
    teaserLead: "Um percurso imersivo pelos materiais, aplicações, inovação e conhecimento do setor.",
    central: "Espaço central",
    branches: [
      "Planta da feira",
      "Distritos de materiais",
      "Conferências",
      "Demonstrações de produto",
      "Networking",
    ],
  },
  visit: {
    title: "Visitar a SURMAT",
    lead: "Quatro dias com os fabricantes de cada superfície de um edifício. O registo é gratuito para profissionais.",
    who: "Quem visita",
    profiles: {
      architect: "Arquiteto ou designer de interiores",
      developer: "Promotor ou dono de obra",
      contractor: "Empreiteiro ou aplicador",
      distributor: "Distribuidor ou retalhista",
      buyer: "Comprador ou compras",
      manufacturer: "Fabricante",
      other: "Outro profissional",
    },
    formTitle: "Registar-se para visitar",
    profile: "O seu perfil",
    interests: "Materiais que procura",
    submit: "Registar-se para visitar",
    successTitle: "Está registado.",
    successLead: "A sua credencial será enviada para {email} antes da abertura da feira.",
    meetingWith: "Pedido de reunião com {name}",
  },
  exhibit: {
    title: "Expor na SURMAT",
    lead: "Os seus produtos pertencem aqui.",
    why: [
      "Arquitetos, promotores, empreiteiros e distribuidores da Argélia, do Senegal e de toda a África",
      "O seu stand fica no distrito dos seus materiais, onde os prescritores os vêm procurar",
      "Os seus produtos ficam online todo o ano na biblioteca de materiais da SURMAT, em nove idiomas",
    ],
    steps: ["Materiais", "Empresa", "Portefólio", "Espaço", "Contacto"],
    manufacture: "O que fabrica?",
    companyTitle: "Fale-nos da sua empresa",
    portfolioTitle: "O que vai apresentar?",
    spaceTitle: "De quanto espaço precisa?",
    contactTitle: "Quem devemos contactar?",
    companyName: "Nome da empresa",
    website: "Site",
    country: "País",
    families: "Famílias de produtos",
    brands: "Marcas",
    machinery: "Vamos demonstrar maquinaria",
    demo: "Queremos uma área de demonstração ao vivo",
    meetingRoom: "Precisamos de uma área de reunião privada",
    description: "Produtos que pretende apresentar",
    recommended: "Com base no seu portefólio, a SURMAT recomenda {min}–{max} m².",
    requested: "Área pretendida (m²)",
    edition: "Edição",
    back: "Voltar",
    next: "Continuar",
    submit: "Enviar candidatura",
    successTitle: "Os seus produtos pertencem à SURMAT.",
    successLead: "Um gestor comercial da SURMAT vai contactar {email} com opções de stand no distrito {sector}.",
    pickOne: "Selecione pelo menos um setor para continuar.",
  },
  form: {
    name: "Nome completo",
    role: "Cargo",
    company: "Empresa",
    email: "E-mail profissional",
    phone: "Telefone",
    country: "País",
    required: "Obrigatório",
    invalidEmail: "Introduza um endereço como nome@empresa.com.",
    error: "Não foi possível enviar o formulário. Verifique a ligação e tente novamente.",
    sending: "A enviar…",
    consent: "A SURMAT pode contactar-me sobre esta edição.",
  },
  cta: {
    dialogTitle: "Expor na SURMAT",
    dialogLead: "Os seus produtos pertencem aqui.",
    apply: "Pedir um stand",
    close: "Fechar",
  },
  edition: {
    datesTBA: "Datas a anunciar",
    venueTBA: "Local a anunciar",
    switchTo: "Mudar para {name}",
  },
  search: {
    title: "Pesquisar na SURMAT",
    placeholder: "Material, espaço ou empresa — p. ex. “piso de mármore hotel”",
    materials: "Materiais",
    sectors: "Setores",
    applications: "Aplicações",
    exhibitors: "Expositores",
    empty: "Escreva um material, um espaço ou uma empresa.",
    none: "Sem resultados para “{q}”. Experimente um único material, como “porcelânico”.",
    popularMaterials: "Materiais populares",
    popularApplications: "Aplicações populares",
    featuredExhibitors: "Expositores em destaque",
  },
  footer: {
    tagline: "A feira internacional de materiais de superfície e produtos de acabamento para a construção.",
    rights: "© {year} SURMAT. Todos os direitos reservados.",
    platform: "Plataforma",
    editions: "Edições",
    languages: "Idiomas",
    legal: "Aviso legal",
    privacy: "Privacidade",
    contact: "Contacto",
  },
  common: { back: "Voltar", all: "Todos", learnMore: "Saber mais", of: "de", explore: "Explorar" },
  vocab: {
    matt: "Mate", polished: "Polido", honed: "Amaciado", textured: "Texturado", antiSlip: "Antiderrapante",
    brushed: "Escovado", glossy: "Brilhante", satin: "Acetinado", leather: "Envelhecido", flamed: "Flamejado",
    bushHammered: "Bujardado", metallic: "Metálico", velvet: "Aveludado", raw: "Natural",
    tile: "Ladrilho", largeFormat: "Grande formato", slab: "Placa", mosaic: "Mosaico", block: "Bloco",
    board: "Placa", panel: "Painel", roll: "Rolo", liquid: "Líquido", powder: "Pó", paste: "Pasta",
    cartridge: "Cartucho", line: "Linha de produção", machine: "Máquina", module: "Módulo",
  },
};
