import type { Dict } from "./en";

export const pt: Dict = {
  brand: {
    descriptor: "Materiais de superfície e produtos de acabamento para a construção",
    eyebrow: "A feira internacional de",
  },
  nav: {
    materials: "Materiais",
    applications: "Aplicações",
    exhibitors: "Expositores",
    experience: "Experiência",
    visit: "Visitar",
    exhibit: "Expor",
    register: "Registar-se para visitar",
    search: "Pesquisar",
    menu: "Menu",
    close: "Fechar",
    edition: "Edição",
    language: "Idioma",
    skip: "Ir para o conteúdo",
  },
  hero: {
    explore: "Explorar materiais",
    exhibit: "Expor na SURMAT",
    visit: "Visitar a SURMAT",
    searchLabel: "Pesquisar no universo de materiais",
    searchPlaceholder: "Experimente “mármore”, “piso de hotel” ou “impermeabilização”",
    matches: "{n} materiais em destaque",
    noMatch: "Nada no universo corresponde ainda a “{q}”",
    clear: "Limpar pesquisa",
    close: "Voltar ao universo",
    exploreMaterial: "Ver o material",
    findExhibitors: "Encontrar expositores",
    usedIn: "Utilizado em",
    format: "Formato",
    hint: "Arraste para rodar o universo. Selecione uma amostra para a trazer para a frente.",
  },
  stats: {
    sectors: "Setores de materiais",
    editions: "Edições",
    exhibitors: "Expositores (objetivo)",
    visitors: "Visitantes profissionais (objetivo)",
    hub: "Um polo regional para oportunidades globais",
  },
  home: {
    materialsTitle: "Explore o mundo dos materiais",
    materialsLead: "Da pedra natural aos sistemas de acabamento mais avançados — seis setores que moldam a arquitetura moderna.",
    viewAll: "Ver todos os materiais",
    spacesTitle: "Os materiais tornam-se espaços",
    spacesLead: "Cada material da SURMAT acaba num hotel, numa casa, num hospital ou num edifício público. Comece pelo espaço.",
    exploreApps: "Ver todas as aplicações",
    industryTitle: "Conheça a indústria",
    industryLead: "Fabricantes, fornecedores e inovadores que apresentam as suas coleções na SURMAT.",
    viewExhibitors: "Ver expositores",
    experienceTitle: "Viva a SURMAT",
    experienceLead: "Percorra os seis distritos da feira e encontre cada stand pelo material que apresenta.",
    exploreExperience: "Descobrir a experiência",
    editionsTitle: "Edições da SURMAT",
    editionsLead: "Dois mercados. Um universo de materiais.",
    exploreEdition: "Ver a edição",
    current: "Está aqui",
    visitTitle: "Venha tocar nos materiais",
    visitLead: "O registo é gratuito para arquitetos, promotores, empreiteiros, distribuidores e compradores.",
    exhibitTitle: "Os seus produtos pertencem aqui",
    exhibitLead: "Coloque as suas coleções diante de quem as prescreve, compra e aplica.",
  },
  why: {
    eyebrow: "Porquê expor",
    title: "Um stand. Quatro mercados.",
    lead: "A SURMAT liga os fabricantes de cada superfície de um edifício a quem constrói o Norte e o Oeste de África — e abre às empresas de todo o mundo uma porta para o continente.",
    markets: [
      {
        id: "dz",
        name: "Argélia",
        kicker: "O maior mercado do Norte de África",
        points: [
          "O maior país de África em superfície, com cerca de 47 milhões de habitantes",
          "Programas contínuos de habitação, infraestruturas, hotelaria e edifícios públicos",
          "Uma ponte entre o Magrebe, o Mediterrâneo e o Sahel",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "A porta da África Ocidental",
        points: [
          "Dacar: um polo de negócios estável e em rápido crescimento no Atlântico",
          "Membro da CEDEAO (15 países) e da UEMOA (8 países que partilham o franco CFA)",
          "Novas cidades, portos, hotéis e equipamentos públicos em construção",
        ],
      },
      {
        id: "africa",
        name: "África",
        kicker: "O próximo boom da construção",
        points: [
          "Mais de 1,4 mil milhões de pessoas — a população mais jovem do mundo",
          "A Zona de Comércio Livre Continental Africana reúne 54 países num só mercado",
          "Prevê-se que a população urbana quase duplique até 2050",
        ],
      },
      {
        id: "world",
        name: "O mundo",
        kicker: "A sua porta para o continente",
        points: [
          "Pavilhões nacionais para a Europa, Türkiye, China, Índia, o Golfo e as Américas",
          "Encontre num só lugar importadores, distribuidores e agentes de toda a África",
          "Uma plataforma em nove idiomas, aberta a expositores de todos os países",
        ],
      },
    ],
    offerTitle: "O que os expositores recebem",
    offerLead: "Tudo na SURMAT é construído em torno de um resultado: colocar os seus produtos diante de quem os prescreve, compra e aplica.",
    offer: [
      {
        title: "Compradores qualificados",
        text: "Arquitetos, promotores, empreiteiros, distribuidores e compradores públicos, registados por perfil e pelos materiais que procuram.",
      },
      { title: "Reuniões marcadas com antecedência", text: "Os visitantes pedem reuniões no seu stand antes da abertura. Chega com uma agenda, não com uma esperança." },
      { title: "O distrito certo", text: "O seu stand fica entre os materiais que fabrica — exatamente onde os prescritores os vão comparar." },
      { title: "Um showroom todo o ano", text: "O seu perfil na biblioteca de materiais da SURMAT continua a trabalhar depois da feira, em nove idiomas." },
      { title: "Um palco para lançamentos", text: "Apresente novas coleções e tecnologias no programa de conferências e demonstrações ao vivo." },
      { title: "Inteligência de mercado", text: "Veja que materiais e aplicações despertam mais interesse em cada mercado, edição após edição." },
    ],
    audienceTitle: "Quem vai conhecer",
    audienceLead: "Apenas visitantes profissionais. Cada um regista-se com o seu perfil e os materiais que procura.",
    participateTitle: "Formas de participar",
    participate: [
      { title: "Stand", text: "Espaço livre ou stand modular, a partir de 9 m², no distrito dos seus materiais." },
      { title: "Pavilhão nacional", text: "Exponha sob a bandeira do seu país num pavilhão partilhado com promoção conjunta." },
      { title: "Patrocínio", text: "Associe a sua marca à feira, ao palco de conferências ou ao percurso do visitante." },
      { title: "Showroom digital", text: "Ainda não está pronto para um stand? Comece com um perfil na biblioteca de materiais online." },
    ],
    cta: "Pedir um stand",
    brochure: "Falar com a equipa comercial",
  },
  sector: {
    materials: "Materiais deste setor",
    exhibitors: "Expositores deste distrito",
    district: "Distrito",
  },
  material: {
    sector: "Setor",
    finishes: "Acabamentos",
    applications: "Aplicações",
    formats: "Formatos",
    spec: "Gama habitual",
    exhibitors: "Expositores que apresentam este material",
    noExhibitors: "Nenhum expositor confirmou ainda este material. O seu pode ser o primeiro.",
    related: "Materiais relacionados",
    manufacturerQ: "Fabrica {material}?",
  },
  catalogue: {
    title: "Biblioteca de materiais",
    lead: "Todos os materiais apresentados na SURMAT, organizados por setor. Cada um leva às empresas que o fabricam.",
    all: "Todos os setores",
    search: "Filtrar materiais",
    noResults: "Nenhum material corresponde a “{q}”. Experimente uma palavra mais ampla como “pedra” ou “ladrilho”.",
    count: "{n} materiais",
  },
  apps: {
    title: "Aplicações",
    lead: "Comece pelo espaço que está a construir e conheça os expositores que fornecem cada uma das suas superfícies.",
    materialsUsed: "Materiais neste espaço",
    suppliers: "Expositores que fornecem estes materiais",
  },
  exhibitors: {
    title: "Expositores",
    lead: "Explore as empresas presentes na SURMAT pelos materiais que fabricam.",
    sample: "Perfil de exemplo",
    sampleNote: "Os perfis de exemplo mostram como vão ficar os showrooms dos expositores. Os expositores confirmados são publicados à medida que assinam.",
    district: "Distrito",
    stand: "Stand",
    requestMeeting: "Pedir uma reunião",
    visitStand: "Encontrar o stand",
    products: "Parede de produtos",
    materials: "Materiais",
    markets: "Mercados",
    founded: "Fundada em",
    all: "Todos",
    empty: "Ainda não há expositores neste setor.",
  },
  experience: {
    title: "A experiência SURMAT",
    lead: "A feira está organizada em seis distritos de materiais. Percorra a planta, encontre um stand, reserve o seu.",
    mapTitle: "Planta da feira",
    mapHint: "Selecione um stand para ver quem expõe.",
    open: "Ver o stand",
    available: "Stand disponível",
    availableLead: "Este stand está disponível para reserva.",
    book: "Reservar este stand",
  },
  visit: {
    title: "Visitar a SURMAT",
    lead: "Quatro dias com os fabricantes de cada superfície de um edifício. O registo é gratuito para profissionais.",
    who: "Quem visita",
    profiles: {
      architect: "Arquiteto ou designer de interiores",
      developer: "Promotor ou dono de obra",
      contractor: "Empreiteiro ou aplicador",
      distributor: "Distribuidor ou retalhista",
      buyer: "Comprador ou compras",
      manufacturer: "Fabricante",
      other: "Outro profissional",
    },
    formTitle: "Registar-se para visitar",
    profile: "O seu perfil",
    interests: "Materiais que procura",
    submit: "Registar-se para visitar",
    successTitle: "Está registado.",
    successLead: "A sua credencial será enviada para {email} antes da abertura da feira.",
    meetingWith: "Pedido de reunião com {name}",
  },
  exhibit: {
    title: "Expor na SURMAT",
    lead: "Os seus produtos pertencem aqui.",
    why: [
      "Arquitetos, promotores, empreiteiros e distribuidores da Argélia, do Senegal e de toda a África",
      "O seu stand fica no distrito dos seus materiais, onde os prescritores os vêm procurar",
      "Os seus produtos ficam online todo o ano na biblioteca de materiais da SURMAT, em nove idiomas",
    ],
    steps: ["Materiais", "Empresa", "Portefólio", "Espaço", "Contacto"],
    manufacture: "O que fabrica?",
    companyTitle: "Fale-nos da sua empresa",
    portfolioTitle: "O que vai apresentar?",
    spaceTitle: "De quanto espaço precisa?",
    contactTitle: "Quem devemos contactar?",
    companyName: "Nome da empresa",
    website: "Site",
    country: "País",
    families: "Famílias de produtos",
    brands: "Marcas",
    machinery: "Vamos demonstrar maquinaria",
    demo: "Queremos uma área de demonstração ao vivo",
    meetingRoom: "Precisamos de uma área de reunião privada",
    description: "Produtos que pretende apresentar",
    recommended: "Com base no seu portefólio, a SURMAT recomenda {min}–{max} m².",
    requested: "Área pretendida (m²)",
    edition: "Edição",
    back: "Voltar",
    next: "Continuar",
    submit: "Enviar candidatura",
    successTitle: "Os seus produtos pertencem à SURMAT.",
    successLead: "Um gestor comercial da SURMAT vai contactar {email} com opções de stand no distrito {sector}.",
    pickOne: "Selecione pelo menos um setor para continuar.",
  },
  form: {
    name: "Nome completo",
    role: "Cargo",
    company: "Empresa",
    email: "E-mail profissional",
    phone: "Telefone",
    country: "País",
    required: "Obrigatório",
    invalidEmail: "Introduza um endereço como nome@empresa.com.",
    error: "Não foi possível enviar o formulário. Verifique a ligação e tente novamente.",
    sending: "A enviar…",
    consent: "A SURMAT pode contactar-me sobre esta edição.",
  },
  cta: {
    dialogTitle: "Expor na SURMAT",
    dialogLead: "Os seus produtos pertencem aqui.",
    apply: "Pedir um stand",
    close: "Fechar",
  },
  edition: {
    datesTBA: "Datas a anunciar",
    venueTBA: "Local a anunciar",
    switchTo: "Mudar para {name}",
  },
  search: {
    title: "Pesquisar na SURMAT",
    placeholder: "Material, espaço ou empresa — p. ex. “piso de mármore hotel”",
    materials: "Materiais",
    sectors: "Setores",
    applications: "Aplicações",
    exhibitors: "Expositores",
    empty: "Escreva um material, um espaço ou uma empresa.",
    none: "Sem resultados para “{q}”. Experimente um único material, como “porcelânico”.",
  },
  footer: {
    tagline: "A feira internacional de materiais de superfície e produtos de acabamento para a construção.",
    rights: "© {year} SURMAT. Todos os direitos reservados.",
    platform: "Plataforma",
    editions: "Edições",
  },
  common: { back: "Voltar", all: "Todos", learnMore: "Saber mais", of: "de" },
  vocab: {
    matt: "Mate", polished: "Polido", honed: "Amaciado", textured: "Texturado", antiSlip: "Antiderrapante",
    brushed: "Escovado", glossy: "Brilhante", satin: "Acetinado", leather: "Envelhecido", flamed: "Flamejado",
    bushHammered: "Bujardado", metallic: "Metálico", velvet: "Aveludado", raw: "Natural",
    tile: "Ladrilho", largeFormat: "Grande formato", slab: "Placa", mosaic: "Mosaico", block: "Bloco",
    board: "Placa", panel: "Painel", roll: "Rolo", liquid: "Líquido", powder: "Pó", paste: "Pasta",
    cartridge: "Cartucho", line: "Linha de produção", machine: "Máquina", module: "Módulo",
  },
};
