import type { Dict } from "./en";

export const tr: Dict = {
  brand: {
    descriptor: "Yüzey Malzemeleri ve Yapı Bitirme Ürünleri",
    eyebrow: "Uluslararası fuar",
  },
  nav: {
    partners: "Ortaklıklar",
    materials: "Malzemeler",
    applications: "Uygulamalar",
    exhibitors: "Katılımcılar",
    experience: "Deneyim",
    visit: "Ziyaret",
    exhibit: "Katılım",
    register: "Ziyaretçi kaydı",
    search: "Ara",
    menu: "Menü",
    close: "Kapat",
    edition: "Fuar",
    language: "Dil",
    skip: "İçeriğe geç",
    pro: "Profesyonel Alan",
  },
  hero: {
    explore: "Malzemeleri keşfedin",
    exhibit: "SURMAT’a katılın",
    visit: "SURMAT’ı ziyaret edin",
    searchLabel: "Malzeme evreninde arayın",
    searchPlaceholder: "“mermer”, “otel zemini” veya “su yalıtımı” deneyin",
    matches: "{n} malzeme öne çıkarıldı",
    noMatch: "Evrende henüz “{q}” ile eşleşen bir şey yok",
    clear: "Aramayı temizle",
    close: "Evrene dön",
    exploreMaterial: "Malzemeyi incele",
    findExhibitors: "Katılımcıları bul",
    usedIn: "Kullanım alanı",
    format: "Ebat",
    hint: "Evreni döndürmek için sürükleyin. Öne getirmek için bir numune seçin.",
    viewSwitch: "Arka plan görünümü",
    preparing3d: "3D hazırlanıyor…",
    scroll: "Keşfetmek için kaydırın",
    tagline: "Malzemeler daha iyi mekânlar yaratır",
  },
  stats: {
    sectors: "Malzeme sektörü",
    editions: "Fuar",
    exhibitors: "Katılımcı (hedef)",
    visitors: "Profesyonel ziyaretçi (hedef)",
    hub: "Küresel fırsatlar için bölgesel bir merkez",
  },
  home: {
    materialsTitle: "Malzemeler dünyasını keşfedin",
    materialsLead: "Doğal taştan ileri bitirme sistemlerine — modern mimariyi şekillendiren altı sektör.",
    viewAll: "Tüm malzemeler",
    spacesTitle: "Malzemeler mekâna dönüşür",
    spacesLead: "SURMAT’taki her malzeme bir otelde, bir evde, bir hastanede ya da bir kamu binasında yer alır. Mekândan başlayın.",
    exploreApps: "Tüm uygulamalar",
    industryTitle: "Sektörle tanışın",
    industryLead: "Koleksiyonlarını SURMAT’ta sunan üreticiler, tedarikçiler ve yenilikçiler.",
    viewExhibitors: "Katılımcıları görün",
    experienceTitle: "SURMAT deneyimi",
    experienceLead: "Fuar alanının altı bölgesini gezin ve her standı sergilediği malzemeye göre bulun.",
    exploreExperience: "Deneyimi keşfedin",
    editionsTitle: "SURMAT fuarları",
    editionsLead: "İki pazar. Tek bir malzeme evreni.",
    exploreEdition: "Fuarı keşfedin",
    current: "Buradasınız",
    visitTitle: "Gelin, malzemelere dokunun",
    visitLead: "Mimarlar, geliştiriciler, müteahhitler, distribütörler ve alıcılar için kayıt ücretsizdir.",
    exhibitTitle: "Ürünlerinizin yeri burası",
    exhibitLead: "Koleksiyonlarınızı onları şartnameye yazan, satın alan ve uygulayan kişilerin önüne koyun.",
    editionsHeadline: "İki fuar. Tek platform.",
  },
  why: {
    eyebrow: "Neden katılmalı",
    title: "Tek stant. Dört pazar.",
    lead: "SURMAT, bir binadaki her yüzeyin üreticilerini Kuzey ve Batı Afrika’yı inşa edenlerle buluşturur — ve dünyanın dört bir yanındaki şirketlere kıtaya açılan bir kapı sunar.",
    markets: [
      {
        id: "dz",
        name: "Cezayir",
        kicker: "Kuzey Afrika’nın en büyük pazarı",
        points: [
          "Yüzölçümüyle Afrika’nın en büyük ülkesi, yaklaşık 47 milyon nüfus",
          "Konut, altyapı, turizm ve kamu binalarında süreklilik gösteren programlar",
          "Mağrip, Akdeniz ve Sahel arasında bir köprü",
        ],
      },
      {
        id: "sn",
        name: "Senegal",
        kicker: "Batı Afrika’nın kapısı",
        points: [
          "Dakar: Atlantik kıyısında istikrarlı ve hızla büyüyen bir iş merkezi",
          "ECOWAS (15 ülke) ve CFA frangını paylaşan WAEMU (8 ülke) üyesi",
          "Yapım aşamasında yeni şehirler, limanlar, oteller ve kamu tesisleri",
        ],
      },
      {
        id: "africa",
        name: "Afrika",
        kicker: "Bir sonraki inşaat patlaması",
        points: [
          "1,4 milyarı aşkın nüfus — dünyanın en genç nüfusu",
          "Afrika Kıtasal Serbest Ticaret Bölgesi 54 ülkeyi tek bir pazarda buluşturuyor",
          "Kentsel nüfusun 2050’ye kadar neredeyse iki katına çıkması bekleniyor",
        ],
      },
      {
        id: "world",
        name: "Dünya",
        kicker: "Kıtaya açılan kapınız",
        points: [
          "Avrupa, Türkiye, Çin, Hindistan, Körfez ve Amerika için ulusal pavyonlar",
          "Afrika’nın dört bir yanından ithalatçı, distribütör ve acentelerle tek bir yerde görüşün",
          "Her ülkeden katılımcıya açık, dokuz dilde bir platform",
        ],
      },
    ],
    offerTitle: "Katılımcıların kazandıkları",
    offerLead: "SURMAT’taki her şey tek bir sonuç için tasarlandı: ürünlerinizi onları şartnameye yazan, satın alan ve uygulayanların önüne koymak.",
    offer: [
      {
        title: "Nitelikli alıcılar",
        text: "Profillerine ve aradıkları malzemelere göre kayıtlı mimarlar, geliştiriciler, müteahhitler, distribütörler ve kamu alıcıları.",
      },
      { title: "Önceden planlanan görüşmeler", text: "Ziyaretçiler kapılar açılmadan standınızla görüşme talep eder. Fuara umutla değil, bir ajandayla gelirsiniz." },
      { title: "Doğru bölge", text: "Standınız ürettiğiniz malzemelerin arasında yer alır — tam da tasarımcıların onları karşılaştırmaya geldiği yerde." },
      { title: "Yıl boyu açık showroom", text: "SURMAT malzeme kütüphanesindeki profiliniz fuardan sonra da dokuz dilde çalışmaya devam eder." },
      { title: "Lansmanlar için bir sahne", text: "Yeni koleksiyon ve teknolojilerinizi konferans ve canlı gösteri programında tanıtın." },
      { title: "Pazar istihbaratı", text: "Her pazarda hangi malzeme ve uygulamaların en çok ilgi gördüğünü fuardan fuara izleyin." },
    ],
    audienceTitle: "Kimlerle tanışacaksınız",
    audienceLead: "Yalnızca profesyonel ziyaretçiler. Her biri profiliyle ve aradığı malzemelerle kayıt olur.",
    participateTitle: "Katılım seçenekleri",
    participate: [
      { title: "Stant", text: "Malzemelerinizin bölgesinde, 9 m²’den başlayan boş alan veya hazır stant." },
      { title: "Ulusal pavyon", text: "Ortak bir pavyon ve birlikte tanıtımla ülkenizin bayrağı altında sergileyin." },
      { title: "Sponsorluk", text: "Markanızı fuara, konferans sahnesine veya ziyaretçi rotasına taşıyın." },
      { title: "Dijital showroom", text: "Henüz stanta hazır değil misiniz? Çevrimiçi malzeme kütüphanesinde bir profille başlayın." },
    ],
    cta: "Stant başvurusu yapın",
    brochure: "Satış ekibimizle görüşün",
  },
  universe: {
    title: "Malzeme evrenini keşfedin",
    lead: "Doğal taştan ileri teknolojilere, zengin bir yüzey malzemeleri ve bitirme ürünleri kütüphanesini keşfedin.",
    browse: "Tüm malzemeler",
    explore: "Malzemeyi incele",
    exhibitThis: "Bu ürünü sergileyin",
    prev: "Önceki malzeme",
    next: "Sonraki malzeme",
    taglines: {
      "ceramic-porcelain": "Dayanmak için üretildi. Görülmek için tasarlandı.",
      "natural-engineered-stone": "Doğal güzellik. Kalıcı değer.",
      "paints-coatings": "Renk, doku ve koruma.",
      "interior-finishing-systems": "Her iç mekânın arkasındaki sistemler.",
      "construction-chemicals": "Her yüzeyi yerinde tutan güç.",
      "surface-technologies": "Yüzeylerin üretildiği yer.",
    },
  },
  explorer: {
    alternatives: "Bu yüzey için de tercih edilenler",
    title: "Her mekân için malzemeler",
    lead: "Arkasındaki malzemeyi — ve onu üreten katılımcıları — görmek için mekânda bir nokta seçin.",
    viewMaterial: "Malzemeyi gör",
    findExhibitors: "Katılımcıları bul",
    surfaces: { floor: "Zemin", wall: "Duvarlar", feature: "Vurgu duvarı", counter: "Resepsiyon bankosu", ceiling: "Tavan" },
  },
  leading: {
    title: "Öne çıkan katılımcılar",
    lead: "Koleksiyonlarını SURMAT’ta sunan üreticiler — her birinin dijital bir showroom’u var.",
    discover: "Katılımcıyı keşfedin",
    featured: "Öne çıkan ürünler",
  },
  split: {
    visitTitle: "SURMAT’ı ziyaret edin",
    visitLead: "Fuara katılmak için şimdi kaydolun.",
    exhibitTitle: "SURMAT’a katılın",
    exhibitLead: "Ürünlerinizi nitelikli bir profesyonel kitleye sergileyin.",
  },
  success: {
    next: "Sonraki adımlar",
    calendar: "Takvime ekle",
    visitSteps: [
      "Yaka kartınız fuar açılmadan önce e-postayla gelir.",
      "Katılımcıların showroom sayfalarından görüşme talep edin.",
      "Yaka kartınızı telefonunuzda fuara getirin.",
    ],
    exhibitSteps: [
      "Bir satış yöneticisi stant seçenekleri ve fiyatlarla size ulaşır.",
      "Malzemelerinizin bölgesindeki alanınızı onaylarsınız.",
      "Katılımınız onaylanınca dijital showroom’unuz yayına girer.",
    ],
  },
  pro: {
    title: "Profesyonel Alan",
    lead: "Katılımcılar ve profesyonel ziyaretçiler için her fuardan önce açılan özel bir alan.",
    soon: "Fuar öncesinde onaylı katılımcılara açılır",
    features: [
      "Katılımcı paneli ve potansiyel müşteri yönetimi",
      "Showroom profilinizi ve ürün kataloğunuzu düzenleme",
      "Profesyonel ziyaretçilerden görüşme talepleri",
      "Belgeler, yaka kartları ve fuar bilgileri",
    ],
    exhibitorCta: "Stant başvurusu yapın",
    visitorCta: "Ziyaretçi kaydı",
    contactCta: "SURMAT ekibiyle iletişime geçin",
  },
  contact: {
    title: "İletişim",
    lead: "Bize kim olduğunuzu ve neye ihtiyacınız olduğunu anlatın. SURMAT ekibinden doğru kişi size yanıt verecek.",
    topic: "Konu",
    topics: {
      exhibitor: "SURMAT’a katılım",
      visitor: "SURMAT’ı ziyaret",
      buyer: "Tedarik ve satın alma",
      partner: "İş birliği",
      media: "Basın ve medya",
      speaker: "Konferansta konuşma",
      other: "Diğer",
    },
    message: "Mesaj",
    submit: "Mesajı gönder",
    successTitle: "Mesaj gönderildi.",
    successLead: "{email} adresine yanıt vereceğiz.",
  },
  legal: {
    title: "Yasal bilgiler",
    publisher: "Yayıncı",
    pending: "Yayıncı bilgileri lansmandan önce burada yayımlanacak.",
    hosting: "Barındırma",
    hostingText: "Bu web sitesi Vercel Inc., ABD tarafından barındırılmaktadır.",
    ip: "Fikrî mülkiyet",
    ipText: "SURMAT adı, bu sitenin içeriği ve tasarımı korunmaktadır. Katılımcıların adları, logoları ve ürün görselleri sahiplerine aittir ve izinleriyle gösterilir.",
  },
  privacy: {
    title: "Gizlilik",
    lead: "Bu sitenin ne topladığı, neden topladığı ve bu konuda bize nasıl ulaşabileceğiniz.",
    sections: [
      {
        title: "Ne topluyoruz",
        text: "Formlarımıza girdiğiniz bilgiler — ad, iş e-postası, şirket, unvan, telefon, ülke ve yanıtlarınız — ve sizi SURMAT’a getiren sayfa ve kampanya.",
      },
      {
        title: "Neden",
        text: "Ziyaretinizi kaydetmek, katılım başvurunuzu işlemek veya mesajınıza yanıt vermek için. Fuarla ilgili olarak yalnızca onay kutusunu işaretlerseniz sizinle iletişime geçeriz.",
      },
      {
        title: "Analitik",
        text: "Platformu geliştirmek ve hangi malzemelerin ilgi gördüğünü anlamak için anonim etkileşimleri — görüntülenen malzemeler, aramalar, çağrı düğmelerine tıklamalar — kaydediyoruz. Bunlar adınızla ilişkilendirilmez.",
      },
      { title: "Çerezler", text: "Fuar ve dil tercihiniz için iki tercih çerezini bir yıl saklıyoruz. Bu site reklam çerezi kullanmaz." },
      { title: "Haklarınız", text: "SURMAT ekibine yazarak verilerinizi görmeyi, düzeltmeyi veya silmeyi istediğiniz zaman talep edebilirsiniz." },
    ],
  },
  event: {
    bandTitle: "Görün, dokunun, tedarik edin — yüz yüze",
    bar: "Uluslararası ticaret fuarı",
    bookStand: "Stand ayırtın",
    freeVisit: "Ücretsiz kayıt",
    visual: "Görselleştirme",
    eyebrow: "Fuar",
    title: "Bitiş sektörünün yüz yüze buluştuğu yer",
    lead: "SURMAT bir katalog değil, canlı bir ticaret etkinliğidir. Katılımcılar ürünlerini standlarında sunar, alıcılar ve proje yetkilileri tedarik için gelir ve projeler masada konuşulur — Oran’da ve Dakar’da.",
    pillars: [
      { title: "Fuar alanı", text: "Malzeme bölgelerine göre düzenlenmiş yüzlerce stand — her ürünü tek ziyarette dokunun, karşılaştırın ve tedarik edin." },
      { title: "B2B görüşmeler", text: "Katılımcılar, distribütörler, geliştiriciler, mimarlar ve kamu alıcıları arasında önceden planlanmış görüşmeler." },
      { title: "Konferanslar ve proje sunumları", text: "Mimarlar, geliştiriciler ve kamu işverenleri bu malzemelere ihtiyaç duyacak projeleri sunar." },
      { title: "Canlı demolar ve lansmanlar", text: "Uygulama gösterileri, çalışan makineler ve fuarda tanıtılan yeni koleksiyonlar." },
    ],
    exhibitors: "{n} katılımcı",
    visitors: "{n} profesyonel ziyaretçi",
    visitPoints: [
      "Profesyonellere ücretsiz giriş",
      "Tüm bitiş ürünlerini tek ziyarette bulun",
      "Üretici ve distribütörlerle yüz yüze görüşün",
    ],
    exhibitPoints: [
      "Nitelikli alıcı ve proje yetkilileriyle tanışın",
      "Standınızda planlı B2B görüşmeler",
      "Ürünlerinizi Afrika pazarlarına sunun",
    ],
  },
  scope: {
    statDistricts: "Bölge",
    statFamilies: "Ürün ailesi",
    district: "Bölge",
    bookHere: "Bu bölgede stand ayırtın",
    eyebrow: "Fuar kapsamı",
    title: "Dokuz bölge. Tüm bitiş sektörü.",
    lead: "Malzeme kütüphanesi örnekler gösterir. Fuar alanı ise bir binayı kaplayan, tamamlayan, koruyan veya donatan her şeyi kapsayan dokuz bölgeye ayrılmıştır. Kimlerin katıldığını görmek için bir bölge seçin.",
    core: "Ana sektör",
    adjacent: "Bunlar da kabul edilir",
    families: "{n} aile",
    missing: "Ürününüzü göremiyor musunuz?",
    missingText: "Bir binayı kaplıyor, tamamlıyor, koruyor veya donatıyorsa, SURMAT’ta yeri var. Ne ürettiğinizi söyleyin, sizi doğru bölgeye yerleştirelim.",
    cta: "Ürünümü öner",
    count: "{m} belgelenmiş malzeme · fuarda {f} ürün ailesi kabul ediliyor",
  },
  partners: {
    eyebrow: "Ortaklık fırsatı",
    title: "SURMAT’ı ülkenize getirin",
    lead: "SURMAT seyahat etmek için tasarlandı. Etkinlik ajansları, sektör dernekleri ve ticaret odaları formatı kendi pazarlarına taşıyabilir — markamız, platformumuz, katılımcı ağımız ve yöntemimiz arkalarında.",
    cta: "Ortak olmak için başvurun",
    mapLabel: "Bugün Cezayir ve Senegal — yarın sizin pazarınız",
    formatsTitle: "Üç ortaklık modeli",
    formats: [
      {
        title: "Lisanslı edisyon",
        text: "SURMAT’ı ülkenizde franchise lisansıyla düzenleyin.",
        points: [
          "SURMAT markası ve formatının tam kullanımı",
          "Dokuz bölgeli plan ve malzeme sınıflandırması",
          "Bu platformda dokuz dilde kendi edisyonunuz",
        ],
      },
      {
        title: "Ortak düzenlenen edisyon",
        text: "Yatırımı ve sonuçları paylaşarak birlikte yeni bir edisyon başlatalım.",
        points: [
          "Ortak iş planı ve bütçe",
          "Paylaşılan satış ekibi ve uluslararası katılımcılar",
          "Sahada SURMAT operasyon desteği",
        ],
      },
      {
        title: "Temsilci ve ülke pavyonu",
        text: "SURMAT’ı ülkenizde temsil edin ve firmalarınızı edisyonlarımıza getirin.",
        points: [
          "Sattığınız standlar üzerinden komisyon",
          "Ülkenizin milli pavyonunu düzenleme",
          "Oran ve Dakar’a alıcı heyetleri",
        ],
      },
    ],
    weBringTitle: "SURMAT’ın getirdikleri",
    weBring: [
      "Yerleşik bir marka ve fuar formatı",
      "Dijital platform: malzeme kütüphanesi, katılımcı showroom’ları, kayıt",
      "Uluslararası katılımcılar ve alıcı ağırlama programı",
      "Satış yöntemi, fiyatlandırma modeli ve eğitim",
      "Dokuz dilde pazarlama kiti, içerik ve kampanyalar",
      "Operasyon kılavuzları ve saha desteği",
    ],
    youBringTitle: "Sizin getirdikleriniz",
    youBring: [
      "Yerel inşaat pazarı bilgisi",
      "Fuar alanları, kurumlar ve derneklerle ilişkiler",
      "Yerel satış ve pazarlama ekibi",
      "Lojistik ve tedarikçi ağı",
      "SURMAT kalite standartlarına bağlılık",
    ],
    stepsTitle: "Nasıl işler",
    steps: [
      { title: "Başvuru", text: "Kuruluşunuzu ve pazarınızı anlatın." },
      { title: "Pazar analizi", text: "Fırsatı birlikte değerlendiririz." },
      { title: "Anlaşma", text: "Ortaklık modelini seçer ve imzalarız." },
      { title: "Lansman", text: "SURMAT edisyonunuz platformda yayına girer." },
    ],
    who: "Afrika, Orta Doğu ve ötesindeki etkinlik organizatörleri, fuar ajansları, sektör dernekleri, ticaret odaları ve yatırımcılar için.",
    applyTitle: "Görüşmeyi başlatın",
    applyLead: "Birkaç bilgi paylaşın; SURMAT ortaklık ekibi beş iş günü içinde yanıt verecektir.",
    homeTitle: "Sıradaki ülke sizinki mi?",
    homeLead: "SURMAT’ı lisanslı ya da ortak düzenlenen bir edisyonla pazarınıza getirin.",
  },
  systems: {
    eyebrow: "Nasıl inşa edilir",
    title: "Her sistem, katman katman",
    lead: "Her yüzeyin arkasında bir ürün sistemi vardır: paneller, taşıyıcılar, yalıtım, membranlar, yapıştırıcılar, şaplar, levhalar ve bitişler — ve bunları üreten makineler. Bir sistem, ardından bir katman seçin; ne olduğunu, tipik özelliklerini ve üreticilerinin nerede sergilediğini görün.",
    onSite: "Şantiyede",
    section: "Teknik kesit",
    process: "Üretim hattı",
    layers: "katman",
    steps: "istasyon",
    outside: "Dış",
    inside: "İç",
    top: "Üst",
    district: "Bölge",
    structure: "Bina taşıyıcı sistemi — ürün kategorisi değil",
    note: "Tipik değerler örnek amaçlıdır. Üretici teknik föylerini ve yerel yönetmelikleri kontrol edin.",
  },
  sector: {
    materials: "Bu sektördeki malzemeler",
    exhibitors: "Bu bölgedeki katılımcılar",
    district: "Bölge",
  },
  material: {
    sector: "Sektör",
    finishes: "Yüzey bitişleri",
    applications: "Uygulamalar",
    formats: "Ebatlar",
    spec: "Tipik aralık",
    exhibitors: "Bu malzemeyi sergileyen katılımcılar",
    noExhibitors: "Bu malzemeyi henüz hiçbir katılımcı onaylamadı. İlk siz olabilirsiniz.",
    related: "İlgili malzemeler",
    manufacturerQ: "{material} üretiyor musunuz?",
    usedIn: "Kullanım alanı:",
  },
  catalogue: {
    title: "Malzeme kütüphanesi",
    lead: "SURMAT’ta sunulan tüm malzemeler, sektöre göre düzenlendi. Her biri onu üreten şirketlere götürür.",
    all: "Tüm sektörler",
    search: "Malzemeleri filtreleyin",
    noResults: "“{q}” ile eşleşen malzeme yok. “taş” veya “karo” gibi daha genel bir kelime deneyin.",
    count: "{n} malzeme",
  },
  apps: {
    allSpaces: "Tüm mekânlar",
    stats: "{m} malzeme · {e} katılımcı",
    title: "Uygulamalar",
    lead: "İnşa ettiğiniz mekândan başlayın ve içindeki her yüzeyi tedarik eden katılımcılarla tanışın.",
    materialsUsed: "Bu mekândaki malzemeler",
    suppliers: "Bu malzemeleri tedarik eden katılımcılar",
  },
  exhibitors: {
    title: "Katılımcılar",
    lead: "SURMAT’taki şirketleri ürettikleri malzemelere göre inceleyin.",
    sample: "Örnek profil",
    sampleNote: "Örnek profiller, katılımcı showroomlarının nasıl görüneceğini gösterir. Onaylanan katılımcılar imza attıkça yayımlanır.",
    district: "Bölge",
    stand: "Stant",
    requestMeeting: "Görüşme talep edin",
    visitStand: "Standı bulun",
    products: "Ürün duvarı",
    materials: "Malzemeler",
    markets: "Pazarlar",
    founded: "Kuruluş",
    all: "Tümü",
    empty: "Bu sektörde henüz katılımcı yok.",
  },
  experience: {
    zones: {
      conference: "Konferans salonu",
      conferenceSub: "Konuşmalar, paneller, proje sunumları",
      b2b: "B2B görüşme salonu",
      b2bSub: "Önceden planlanmış alıcı görüşmeleri",
      demo: "Canlı demo sahnesi",
      demoSub: "Uygulama ve makine gösterileri",
      aisle: "Ana koridor",
      pavilions: "Ülke pavyonları",
      lounge: "Dinlenme ve kafe",
      registration: "Kayıt",
      entrance: "Ana giriş",
    },
    legendTaken: "Rezerve stand",
    title: "SURMAT deneyimi",
    lead: "Dokuz bölge, bir konferans salonu, bir B2B salonu ve canlı demo sahnesi. Planı gezin, bir stand bulun, kendinizinkini ayırtın.",
    mapTitle: "Fuar alanı",
    mapHint: "Kimin sergilediğini görmek için bir stant seçin.",
    open: "Standı aç",
    available: "Boş stant",
    availableLead: "Bu stant rezervasyona açıktır.",
    book: "Bu standı ayırtın",
    teaserTitle: "Bir fuardan fazlası",
    teaserLead: "Malzemeler, uygulamalar, inovasyon ve sektör uzmanlığı arasında sürükleyici bir yolculuk.",
    central: "Merkezî deneyim alanı",
    branches: [
      "Fuar planı",
      "Malzeme bölgeleri",
      "Konferanslar",
      "Ürün gösterimleri",
      "İş bağlantıları",
    ],
  },
  visit: {
    title: "SURMAT’ı ziyaret edin",
    lead: "Bir binadaki her yüzeyin üreticileriyle dört gün. Profesyoneller için kayıt ücretsizdir.",
    who: "Kimler ziyaret ediyor",
    profiles: {
      architect: "Mimar veya iç mimar",
      developer: "Geliştirici veya işveren",
      contractor: "Müteahhit veya uygulayıcı",
      distributor: "Distribütör veya perakendeci",
      buyer: "Alıcı veya satın alma",
      manufacturer: "Üretici",
      other: "Diğer profesyonel",
    },
    formTitle: "Ziyaretçi kaydı",
    profile: "Profiliniz",
    interests: "Aradığınız malzemeler",
    submit: "Kayıt olun",
    successTitle: "Kaydınız tamamlandı.",
    successLead: "Yaka kartınız fuar açılmadan önce {email} adresine gönderilecek.",
    meetingWith: "{name} ile görüşme talebi",
  },
  exhibit: {
    title: "SURMAT’a katılın",
    lead: "Ürünlerinizin yeri burası.",
    why: [
      "Cezayir, Senegal ve tüm Afrika’dan mimarlar, geliştiriciler, müteahhitler ve distribütörler",
      "Standınız, tasarımcıların aramaya geldiği kendi malzemelerinizin bölgesinde",
      "Ürünleriniz SURMAT malzeme kütüphanesinde yıl boyu, dokuz dilde çevrimiçi kalır",
    ],
    steps: ["Malzemeler", "Şirket", "Portföy", "Alan", "İletişim"],
    manufacture: "Ne üretiyorsunuz?",
    companyTitle: "Bize şirketinizden bahsedin",
    portfolioTitle: "Neler sergileyeceksiniz?",
    spaceTitle: "Ne kadar alana ihtiyacınız var?",
    contactTitle: "Kiminle iletişime geçelim?",
    companyName: "Şirket adı",
    website: "Web sitesi",
    country: "Ülke",
    families: "Ürün grupları",
    brands: "Markalar",
    machinery: "Makine gösterimi yapacağız",
    demo: "Canlı gösteri alanı istiyoruz",
    meetingRoom: "Özel bir görüşme alanına ihtiyacımız var",
    description: "Sergilemeyi planladığınız ürünler",
    recommended: "Portföyünüze göre SURMAT {min}–{max} m² öneriyor.",
    requested: "Talep edilen alan (m²)",
    edition: "Fuar",
    back: "Geri",
    next: "Devam",
    submit: "Başvuruyu gönder",
    successTitle: "Ürünlerinizin yeri SURMAT.",
    successLead: "Bir SURMAT satış yöneticisi, {sector} bölgesindeki stant seçenekleriyle {email} adresinden size ulaşacak.",
    pickOne: "Devam etmek için en az bir sektör seçin.",
  },
  form: {
    name: "Ad soyad",
    role: "Unvan",
    company: "Şirket",
    email: "İş e-postası",
    phone: "Telefon",
    country: "Ülke",
    required: "Zorunlu",
    invalidEmail: "ad@sirket.com gibi bir e-posta adresi girin.",
    error: "Form gönderilemedi. Bağlantınızı kontrol edip tekrar deneyin.",
    sending: "Gönderiliyor…",
    consent: "SURMAT bu fuarla ilgili benimle iletişime geçebilir.",
  },
  cta: {
    dialogTitle: "SURMAT’a katılın",
    dialogLead: "Ürünlerinizin yeri burası.",
    apply: "Stant başvurusu yapın",
    close: "Kapat",
  },
  edition: {
    datesTBA: "Tarihler açıklanacak",
    venueTBA: "Mekân açıklanacak",
    switchTo: "{name} fuarına geç",
  },
  search: {
    title: "SURMAT’ta arayın",
    placeholder: "Malzeme, mekân veya şirket — örn. “mermer otel zemini”",
    materials: "Malzemeler",
    sectors: "Sektörler",
    applications: "Uygulamalar",
    exhibitors: "Katılımcılar",
    empty: "Bir malzeme, mekân veya şirket yazın.",
    none: "“{q}” için sonuç yok. “porselen” gibi tek bir malzeme deneyin.",
    popularMaterials: "Popüler malzemeler",
    popularApplications: "Popüler uygulamalar",
    featuredExhibitors: "Öne çıkan katılımcılar",
  },
  footer: {
    tagline: "Yüzey malzemeleri ve yapı bitirme ürünleri uluslararası fuarı.",
    rights: "© {year} SURMAT. Tüm hakları saklıdır.",
    platform: "Platform",
    editions: "Fuarlar",
    languages: "Diller",
    legal: "Yasal bilgiler",
    privacy: "Gizlilik",
    contact: "İletişim",
  },
  common: { back: "Geri", all: "Tümü", learnMore: "Daha fazla bilgi", of: "/", explore: "Keşfedin" },
  vocab: {
    matt: "Mat", polished: "Parlak cilalı", honed: "Honlu", textured: "Dokulu", antiSlip: "Kaymaz",
    brushed: "Fırçalanmış", glossy: "Parlak", satin: "Saten", leather: "Deri dokulu", flamed: "Yakma",
    bushHammered: "Buçardalı", metallic: "Metalik", velvet: "Kadifemsi", raw: "Doğal",
    tile: "Karo", largeFormat: "Büyük ebat", slab: "Plaka", mosaic: "Mozaik", block: "Blok",
    board: "Levha", panel: "Panel", roll: "Rulo", liquid: "Sıvı", powder: "Toz", paste: "Macun",
    cartridge: "Kartuş", line: "Üretim hattı", machine: "Makine", module: "Modül",
  },
};
