import type { Dict } from "./en";

export const zh: Dict = {
  brand: {
    descriptor: "表面材料与建筑装饰产品",
    eyebrow: "国际展览会",
  },
  nav: {
    partners: "合作伙伴",
    materials: "材料",
    applications: "应用",
    exhibitors: "展商",
    experience: "展会体验",
    visit: "参观",
    exhibit: "参展",
    register: "观众登记",
    search: "搜索",
    menu: "菜单",
    close: "关闭",
    edition: "展会",
    language: "语言",
    skip: "跳到正文",
    pro: "专业空间",
  },
  hero: {
    explore: "探索材料",
    exhibit: "参展 SURMAT",
    visit: "参观 SURMAT",
    searchLabel: "在材料宇宙中搜索",
    searchPlaceholder: "试试“大理石”“酒店地面”或“防水”",
    matches: "已突出显示 {n} 种材料",
    noMatch: "宇宙中暂时没有与“{q}”匹配的内容",
    clear: "清除搜索",
    close: "返回宇宙",
    exploreMaterial: "查看材料",
    findExhibitors: "寻找展商",
    usedIn: "应用于",
    format: "规格",
    hint: "拖动以旋转宇宙。选择一个样品将其拉近。",
    scroll: "向下滚动探索",
    tagline: "材料成就更好的空间",
  },
  stats: {
    sectors: "材料板块",
    editions: "届展会",
    exhibitors: "展商（目标）",
    visitors: "专业观众（目标）",
    hub: "连接全球机遇的区域枢纽",
  },
  home: {
    materialsTitle: "探索材料的世界",
    materialsLead: "从天然石材到先进的饰面系统——塑造现代建筑的六大板块。",
    viewAll: "查看全部材料",
    spacesTitle: "材料成就空间",
    spacesLead: "SURMAT 的每一种材料最终都会用于酒店、住宅、医院或公共建筑。从空间出发。",
    exploreApps: "查看全部应用",
    industryTitle: "结识业界",
    industryLead: "在 SURMAT 展示产品系列的制造商、供应商和创新者。",
    viewExhibitors: "查看展商",
    experienceTitle: "体验 SURMAT",
    experienceLead: "漫步展馆的六大展区，按展示的材料找到每一个展位。",
    exploreExperience: "了解展会体验",
    editionsTitle: "SURMAT 各届展会",
    editionsLead: "两个市场，一个材料宇宙。",
    exploreEdition: "查看本届展会",
    current: "当前所在",
    visitTitle: "亲手触摸材料",
    visitLead: "建筑师、开发商、承包商、经销商和采购商均可免费登记。",
    exhibitTitle: "您的产品属于这里",
    exhibitLead: "让选用、采购和安装您产品的人看到您的产品系列。",
    editionsHeadline: "两届展会，一个平台。",
  },
  why: {
    eyebrow: "为何参展",
    title: "一个展位，四个市场。",
    lead: "SURMAT 将建筑中每一种表面材料的制造商与建设北非和西非的人们连接起来——并为世界各地的企业打开通往非洲大陆的大门。",
    markets: [
      {
        id: "dz",
        name: "阿尔及利亚",
        kicker: "北非最大的市场",
        points: [
          "非洲面积最大的国家，人口约 4700 万",
          "住房、基础设施、酒店和公共建筑项目持续推进",
          "连接马格里布、地中海和萨赫勒地区的桥梁",
        ],
      },
      {
        id: "sn",
        name: "塞内加尔",
        kicker: "西非的门户",
        points: [
          "达喀尔：大西洋沿岸稳定且快速发展的商业中心",
          "西非国家经济共同体（15 国）和西非经济货币联盟（8 个使用非洲法郎的国家）成员",
          "新城、港口、酒店和公共设施正在建设中",
        ],
      },
      {
        id: "africa",
        name: "非洲",
        kicker: "下一轮建设热潮",
        points: [
          "人口超过 14 亿——全球最年轻的人口结构",
          "非洲大陆自由贸易区将 54 个国家整合为一个市场",
          "预计到 2050 年城市人口将接近翻倍",
        ],
      },
      {
        id: "world",
        name: "全世界",
        kicker: "您通往非洲大陆的大门",
        points: [
          "为欧洲、土耳其、中国、印度、海湾地区和美洲设立国家展团",
          "在同一地点结识来自非洲各地的进口商、经销商和代理商",
          "九种语言的平台，向所有国家的展商开放",
        ],
      },
    ],
    offerTitle: "展商能获得什么",
    offerLead: "SURMAT 的一切都围绕一个目标：让选用、采购和安装您产品的人看到您的产品。",
    offer: [
      {
        title: "合格买家",
        text: "建筑师、开发商、承包商、经销商和公共采购方，均按身份和所需材料登记。",
      },
      { title: "提前预约洽谈", text: "观众在开展前即可预约您的展位洽谈。您带着日程而来，而不是碰运气。" },
      { title: "合适的展区", text: "您的展位就在您所生产的材料之中——正是设计方前来比较的地方。" },
      { title: "全年在线展厅", text: "您在 SURMAT 材料库中的主页在展会结束后继续以九种语言为您工作。" },
      { title: "新品发布舞台", text: "在会议和现场演示活动中发布新系列和新技术。" },
      { title: "市场洞察", text: "逐届了解每个市场中最受关注的材料和应用。" },
    ],
    audienceTitle: "您将见到谁",
    audienceLead: "仅限专业观众。每位观众都会登记身份和所需材料。",
    participateTitle: "参与方式",
    participate: [
      { title: "展位", text: "光地或标准展位，9 平方米起，位于您所在材料的展区。" },
      { title: "国家展团", text: "在本国旗帜下参展，共享展团并联合推广。" },
      { title: "赞助", text: "让您的品牌出现在展会、会议舞台或观众动线上。" },
      { title: "数字展厅", text: "还没准备好展位？先从在线材料库中的企业主页开始。" },
    ],
    cta: "申请参展",
    brochure: "联系我们的销售团队",
  },
  universe: {
    title: "探索材料宇宙",
    lead: "从天然石材到先进技术，探索丰富的表面材料与装饰产品库。",
    browse: "浏览全部材料",
    explore: "查看材料",
    exhibitThis: "展示此产品",
    prev: "上一种材料",
    next: "下一种材料",
    taglines: {
      "ceramic-porcelain": "经久耐用，值得一看。",
      "natural-engineered-stone": "天然之美，恒久价值。",
      "paints-coatings": "色彩、质感与保护。",
      "interior-finishing-systems": "每个室内空间背后的系统。",
      "construction-chemicals": "让每个表面稳固的力量。",
      "surface-technologies": "表面诞生的地方。",
    },
  },
  explorer: {
    alternatives: "该表面的其他常用材料",
    title: "适用于每个空间的材料",
    lead: "在空间中选择一个点，查看其背后的材料——以及生产它的展商。",
    viewMaterial: "查看材料",
    findExhibitors: "寻找展商",
    surfaces: { floor: "地面", wall: "墙面", feature: "主题墙", counter: "接待台", ceiling: "天花" },
  },
  leading: { title: "重点展商", lead: "在 SURMAT 展示产品系列的制造商——每家都有自己的数字展厅。", discover: "了解展商", featured: "精选产品" },
  split: { visitTitle: "参观 SURMAT", visitLead: "立即登记，参观展会。", exhibitTitle: "参展 SURMAT", exhibitLead: "向合格的专业观众展示您的产品。" },
  success: {
    next: "接下来",
    calendar: "添加到日历",
    visitSteps: [
      "您的胸卡将在开展前通过邮件发送。",
      "在展商的展厅页面预约洽谈。",
      "到场时出示手机上的胸卡。",
    ],
    exhibitSteps: [
      "销售经理将与您联系，提供展位方案和价格。",
      "您确认所在材料展区的展位面积。",
      "参展确认后，您的数字展厅即上线。",
    ],
  },
  pro: {
    title: "专业空间",
    lead: "面向展商和专业观众的专属空间，在每届展会前开放。",
    soon: "展会前向已确认的展商开放",
    features: [
      "展商后台与客户线索管理",
      "编辑展厅主页和产品目录",
      "接收专业观众的洽谈预约",
      "文件、胸卡与展会信息",
    ],
    exhibitorCta: "申请参展",
    visitorCta: "观众登记",
    contactCta: "联系 SURMAT 团队",
  },
  contact: {
    title: "联系我们",
    lead: "告诉我们您是谁以及您的需求，SURMAT 团队的相关人员会回复您。",
    topic: "主题",
    topics: { exhibitor: "参展 SURMAT", visitor: "参观 SURMAT", buyer: "采购与寻源", partner: "合作", media: "媒体与新闻", speaker: "会议演讲", other: "其他" },
    message: "留言",
    submit: "发送",
    successTitle: "留言已发送。",
    successLead: "我们将回复至 {email}。",
  },
  legal: {
    title: "法律声明",
    publisher: "发布者",
    pending: "发布者信息将在上线前在此公布。",
    hosting: "托管",
    hostingText: "本网站由美国 Vercel Inc. 托管。",
    ip: "知识产权",
    ipText: "SURMAT 名称以及本网站的内容和设计受法律保护。展商的名称、标志和产品图片归各自所有者所有，经其许可展示。",
  },
  privacy: {
    title: "隐私",
    lead: "本网站收集哪些信息、为何收集，以及如何就此联系我们。",
    sections: [
      { title: "我们收集的信息", text: "您在表单中填写的信息——姓名、工作邮箱、企业、职位、电话、国家及您的回答——以及将您带到 SURMAT 的页面和推广活动。" },
      { title: "用途", text: "用于登记您的参观、处理您的参展申请或回复您的留言。只有在您勾选同意框的情况下，我们才会就本届展会与您联系。" },
      { title: "数据分析", text: "我们记录匿名的交互——浏览的材料、搜索、对行动按钮的点击——以改进平台并了解哪些材料更受关注。这些数据不与您的姓名关联。" },
      { title: "Cookie", text: "我们保存两个偏好 Cookie（展会和语言），期限一年。本网站不使用广告 Cookie。" },
      { title: "您的权利", text: "您可以随时写信给 SURMAT 团队，要求查看、更正或删除您的数据。" },
    ],
  },
  event: {
    bandTitle: "亲眼看、亲手摸、现场采购",
    bar: "国际专业展会",
    bookStand: "预订展位",
    freeVisit: "免费登记",
    visual: "效果图",
    eyebrow: "展会",
    title: "装饰装修行业面对面交流的平台",
    lead: "SURMAT 是一场真实的专业展会，而非产品目录。展商在展位上展示产品，采购商和设计方前来寻源，项目在洽谈桌上推进——分别在奥兰和达喀尔举办。",
    pillars: [
      { title: "展览现场", text: "数百个展位按材料分区布置——一次参观即可触摸、比较并采购各类产品。" },
      { title: "B2B 商务对接", text: "展商与经销商、开发商、建筑师及公共采购方之间的预约洽谈。" },
      { title: "论坛与项目发布", text: "建筑师、开发商和公共业主介绍将需要这些材料的项目。" },
      { title: "现场演示与新品发布", text: "施工演示、设备现场运行以及在展会首发的新系列。" },
    ],
    exhibitors: "{n} 家展商",
    visitors: "{n} 名专业观众",
    visitPoints: [
      "专业观众免费入场",
      "一次参观采购全部装饰材料",
      "与制造商和经销商面对面交流",
    ],
    exhibitPoints: [
      "对接合格的采购商与设计方",
      "在展位上进行预约 B2B 洽谈",
      "将产品推向非洲市场",
    ],
  },
  scope: {
    statDistricts: "展区",
    statFamilies: "产品品类",
    district: "展区",
    bookHere: "预订本展区展位",
    eyebrow: "展品范围",
    title: "九大展区，覆盖整个装饰装修行业",
    lead: "材料库仅展示示例。展会现场分为九大展区，涵盖所有用于建筑饰面、装修、防护或配套的产品。选择一个展区，查看参展内容。",
    core: "核心板块",
    adjacent: "同样欢迎",
    families: "{n} 个品类",
    missing: "没有找到您的产品？",
    missingText: "只要用于建筑的饰面、装修、防护或配套，就属于 SURMAT。告诉我们您的产品，我们将为您安排合适的展区。",
    cta: "提交我的产品",
    count: "已收录 {m} 种材料 · 展会欢迎 {f} 个产品品类",
  },
  partners: {
    eyebrow: "合作机会",
    title: "把 SURMAT 带到您的国家",
    lead: "SURMAT 可复制推广。会展公司、行业协会和商会可以把这一展会模式带到本地市场——背后有我们的品牌、平台、展商网络和运营方法支持。",
    cta: "申请成为合作伙伴",
    mapLabel: "今天在阿尔及利亚和塞内加尔——明天在您的市场",
    formatsTitle: "三种合作模式",
    formats: [
      {
        title: "授权展会",
        text: "以特许经营授权方式在您的国家举办 SURMAT。",
        points: [
          "完整使用 SURMAT 品牌与展会模式",
          "九大展区平面规划与材料分类体系",
          "在本平台以九种语言发布您的展会",
        ],
      },
      {
        title: "联合主办",
        text: "共同推出新一届展会，共担投资、共享收益。",
        points: [
          "共同的商业计划与预算",
          "共享销售团队与国际展商",
          "SURMAT 现场运营支持",
        ],
      },
      {
        title: "代理与国家展团",
        text: "在您的国家代表 SURMAT，组织本国企业参展。",
        points: [
          "按售出展位获得佣金",
          "组织本国国家展团",
          "组织采购团前往奥兰和达喀尔",
        ],
      },
    ],
    weBringTitle: "SURMAT 提供",
    weBring: [
      "成熟的品牌与展会模式",
      "数字平台：材料库、展商展厅、观众登记",
      "国际展商与买家邀约计划",
      "销售方法、定价模型与培训",
      "九种语言的营销工具包、内容与推广活动",
      "运营手册与现场支持",
    ],
    youBringTitle: "您提供",
    youBring: [
      "对本地建筑市场的了解",
      "与场馆、政府部门和协会的关系",
      "本地销售与市场团队",
      "物流与供应商网络",
      "遵守 SURMAT 质量标准的承诺",
    ],
    stepsTitle: "合作流程",
    steps: [
      { title: "提交申请", text: "介绍您的机构和市场。" },
      { title: "市场研究", text: "我们共同评估机会。" },
      { title: "签订协议", text: "确定合作模式并签约。" },
      { title: "正式启动", text: "您的 SURMAT 展会在平台上线。" },
    ],
    who: "面向非洲、中东及其他地区的会展组织者、展览公司、行业协会、商会和投资者。",
    applyTitle: "开始洽谈",
    applyLead: "请留下基本信息，SURMAT 合作团队将在五个工作日内回复。",
    homeTitle: "下一个会是您的国家吗？",
    homeLead: "以授权或联合主办的方式，把 SURMAT 带到您的市场。",
  },
  systems: {
    eyebrow: "构造解析",
    title: "每个系统，逐层拆解",
    lead: "每一个表面背后都是一套产品系统：面板、龙骨、保温、防水、胶粘剂、找平层、板材和饰面，以及生产它们的设备。选择一个系统，再选择一层，了解它是什么、典型参数，以及其制造商在哪个展区参展。",
    onSite: "施工现场",
    section: "技术剖面",
    process: "生产线",
    layers: "层",
    steps: "工位",
    outside: "室外",
    inside: "室内",
    top: "顶面",
    district: "展区",
    structure: "建筑结构——不属于产品类别",
    note: "典型参数仅供说明，请以制造商技术资料和当地规范为准。",
  },
  sector: {
    materials: "本板块材料",
    exhibitors: "本展区展商",
    district: "展区",
  },
  material: {
    sector: "板块",
    finishes: "表面处理",
    applications: "应用",
    formats: "规格",
    spec: "常见范围",
    exhibitors: "展示该材料的展商",
    noExhibitors: "目前尚无展商确认展示此材料。您可以成为第一家。",
    related: "相关材料",
    manufacturerQ: "您生产{material}吗？",
    usedIn: "应用于：",
  },
  catalogue: {
    title: "材料库",
    lead: "SURMAT 展出的全部材料，按板块分类。每一种材料都能带您找到生产它的企业。",
    all: "全部板块",
    search: "筛选材料",
    noResults: "没有与“{q}”匹配的材料。试试“石材”或“瓷砖”等更宽泛的词。",
    count: "{n} 种材料",
  },
  apps: {
    allSpaces: "全部空间",
    stats: "{m} 种材料 · {e} 家展商",
    title: "应用",
    lead: "从您正在建设的空间出发，结识为其中每一个表面供货的展商。",
    materialsUsed: "该空间所用材料",
    suppliers: "供应这些材料的展商",
  },
  exhibitors: {
    title: "展商",
    lead: "按所生产的材料浏览 SURMAT 的参展企业。",
    sample: "示例主页",
    sampleNote: "示例主页展示了展商展厅的呈现方式。已确认的展商将在签约后陆续发布。",
    district: "展区",
    stand: "展位",
    requestMeeting: "预约洽谈",
    visitStand: "查找展位",
    products: "产品墙",
    materials: "材料",
    markets: "市场",
    founded: "成立于",
    all: "全部",
    empty: "该板块暂无展商。",
  },
  experience: {
    zones: {
      conference: "会议厅",
      conferenceSub: "演讲、圆桌与项目发布",
      b2b: "B2B 洽谈区",
      b2bSub: "预约采购洽谈",
      demo: "现场演示舞台",
      demoSub: "施工与设备演示",
      aisle: "主通道",
      pavilions: "国家展团",
      lounge: "休息区与咖啡",
      registration: "登记处",
      entrance: "主入口",
    },
    legendTaken: "已预订展位",
    title: "SURMAT 展会体验",
    lead: "九大展区、会议厅、B2B 洽谈区和现场演示舞台。浏览平面图，查找展位，预订您的展位。",
    mapTitle: "展馆平面图",
    mapHint: "选择一个展位查看参展企业。",
    open: "查看展位",
    available: "可预订展位",
    availableLead: "该展位可供预订。",
    book: "预订此展位",
    teaserTitle: "不止是一场展会",
    teaserLead: "一段穿越材料、应用、创新与行业专业知识的沉浸式旅程。",
    central: "中央体验区",
    branches: [
      "展馆平面图",
      "材料展区",
      "会议",
      "产品演示",
      "商务交流",
    ],
  },
  visit: {
    title: "参观 SURMAT",
    lead: "与建筑中每一种表面材料的制造商共度四天。专业人士免费登记。",
    who: "观众构成",
    profiles: {
      architect: "建筑师或室内设计师",
      developer: "开发商或业主",
      contractor: "承包商或施工方",
      distributor: "经销商或零售商",
      buyer: "采购方",
      manufacturer: "制造商",
      other: "其他专业人士",
    },
    formTitle: "观众登记",
    profile: "您的身份",
    interests: "您在寻找的材料",
    submit: "提交登记",
    successTitle: "登记成功。",
    successLead: "您的胸卡将在开展前发送至 {email}。",
    meetingWith: "与 {name} 的洽谈预约",
  },
  exhibit: {
    title: "参展 SURMAT",
    lead: "您的产品属于这里。",
    why: [
      "来自阿尔及利亚、塞内加尔和整个非洲的建筑师、开发商、承包商和经销商",
      "您的展位位于您所在材料的展区，正是设计方前来寻找的地方",
      "您的产品全年以九种语言在 SURMAT 材料库中在线展示",
    ],
    steps: ["材料", "企业", "产品", "面积", "联系方式"],
    manufacture: "您生产什么？",
    companyTitle: "介绍一下您的企业",
    portfolioTitle: "您将展示什么？",
    spaceTitle: "您需要多大面积？",
    contactTitle: "我们应该联系谁？",
    companyName: "企业名称",
    website: "网站",
    country: "国家",
    families: "产品系列数",
    brands: "品牌数",
    machinery: "我们将进行设备演示",
    demo: "我们需要现场演示区",
    meetingRoom: "我们需要独立洽谈区",
    description: "计划展出的产品",
    recommended: "根据您的产品情况，SURMAT 建议 {min}–{max} 平方米。",
    requested: "申请面积（平方米）",
    edition: "展会",
    back: "返回",
    next: "继续",
    submit: "提交申请",
    successTitle: "您的产品属于 SURMAT。",
    successLead: "SURMAT 销售经理将通过 {email} 与您联系，提供 {sector} 展区的展位方案。",
    pickOne: "请至少选择一个板块以继续。",
  },
  form: {
    name: "姓名",
    role: "职位",
    company: "企业",
    email: "工作邮箱",
    phone: "电话",
    country: "国家",
    required: "必填",
    invalidEmail: "请输入类似 name@company.com 的邮箱地址。",
    error: "表单未能发送。请检查网络连接后重试。",
    sending: "发送中…",
    consent: "SURMAT 可以就本届展会与我联系。",
  },
  cta: {
    dialogTitle: "参展 SURMAT",
    dialogLead: "您的产品属于这里。",
    apply: "申请参展",
    close: "关闭",
  },
  edition: {
    datesTBA: "日期待定",
    venueTBA: "场馆待定",
    switchTo: "切换到 {name}",
  },
  search: {
    title: "搜索 SURMAT",
    placeholder: "材料、空间或企业——例如“大理石 酒店 地面”",
    materials: "材料",
    sectors: "板块",
    applications: "应用",
    exhibitors: "展商",
    empty: "输入材料、空间或企业名称。",
    none: "没有“{q}”的结果。试试单一材料，例如“瓷砖”。",
    popularMaterials: "热门材料",
    popularApplications: "热门应用",
    featuredExhibitors: "精选展商",
  },
  footer: {
    tagline: "表面材料与建筑装饰产品国际展览会。",
    rights: "© {year} SURMAT。保留所有权利。",
    platform: "平台",
    editions: "各届展会",
    languages: "语言",
    legal: "法律声明",
    privacy: "隐私",
    contact: "联系我们",
  },
  common: { back: "返回", all: "全部", learnMore: "了解更多", of: "/", explore: "探索" },
  vocab: {
    matt: "哑光", polished: "抛光", honed: "亚光研磨", textured: "纹理", antiSlip: "防滑",
    brushed: "拉丝", glossy: "亮光", satin: "缎面", leather: "皮纹", flamed: "火烧",
    bushHammered: "荔枝面", metallic: "金属感", velvet: "丝绒", raw: "天然",
    tile: "砖", largeFormat: "大规格", slab: "板材", mosaic: "马赛克", block: "荒料",
    board: "板", panel: "面板", roll: "卷材", liquid: "液体", powder: "粉料", paste: "膏体",
    cartridge: "胶管", line: "生产线", machine: "设备", module: "模块",
  },
};
