import type { Dict } from "./en";

export const zh: Dict = {
  brand: {
    descriptor: "表面材料与建筑装饰产品",
    eyebrow: "国际展览会",
  },
  nav: {
    materials: "材料",
    applications: "应用",
    exhibitors: "展商",
    experience: "展会体验",
    visit: "参观",
    exhibit: "参展",
    register: "观众登记",
    search: "搜索",
    menu: "菜单",
    close: "关闭",
    edition: "展会",
    language: "语言",
    skip: "跳到正文",
  },
  hero: {
    explore: "探索材料",
    exhibit: "参展 SURMAT",
    visit: "参观 SURMAT",
    searchLabel: "在材料宇宙中搜索",
    searchPlaceholder: "试试“大理石”“酒店地面”或“防水”",
    matches: "已突出显示 {n} 种材料",
    noMatch: "宇宙中暂时没有与“{q}”匹配的内容",
    clear: "清除搜索",
    close: "返回宇宙",
    exploreMaterial: "查看材料",
    findExhibitors: "寻找展商",
    usedIn: "应用于",
    format: "规格",
    hint: "拖动以旋转宇宙。选择一个样品将其拉近。",
  },
  stats: {
    sectors: "材料板块",
    editions: "届展会",
    exhibitors: "展商（目标）",
    visitors: "专业观众（目标）",
    hub: "连接全球机遇的区域枢纽",
  },
  home: {
    materialsTitle: "探索材料的世界",
    materialsLead: "从天然石材到先进的饰面系统——塑造现代建筑的六大板块。",
    viewAll: "查看全部材料",
    spacesTitle: "材料成就空间",
    spacesLead: "SURMAT 的每一种材料最终都会用于酒店、住宅、医院或公共建筑。从空间出发。",
    exploreApps: "查看全部应用",
    industryTitle: "结识业界",
    industryLead: "在 SURMAT 展示产品系列的制造商、供应商和创新者。",
    viewExhibitors: "查看展商",
    experienceTitle: "体验 SURMAT",
    experienceLead: "漫步展馆的六大展区，按展示的材料找到每一个展位。",
    exploreExperience: "了解展会体验",
    editionsTitle: "SURMAT 各届展会",
    editionsLead: "两个市场，一个材料宇宙。",
    exploreEdition: "查看本届展会",
    current: "当前所在",
    visitTitle: "亲手触摸材料",
    visitLead: "建筑师、开发商、承包商、经销商和采购商均可免费登记。",
    exhibitTitle: "您的产品属于这里",
    exhibitLead: "让选用、采购和安装您产品的人看到您的产品系列。",
  },
  why: {
    eyebrow: "为何参展",
    title: "一个展位，四个市场。",
    lead: "SURMAT 将建筑中每一种表面材料的制造商与建设北非和西非的人们连接起来——并为世界各地的企业打开通往非洲大陆的大门。",
    markets: [
      {
        id: "dz",
        name: "阿尔及利亚",
        kicker: "北非最大的市场",
        points: [
          "非洲面积最大的国家，人口约 4700 万",
          "住房、基础设施、酒店和公共建筑项目持续推进",
          "连接马格里布、地中海和萨赫勒地区的桥梁",
        ],
      },
      {
        id: "sn",
        name: "塞内加尔",
        kicker: "西非的门户",
        points: [
          "达喀尔：大西洋沿岸稳定且快速发展的商业中心",
          "西非国家经济共同体（15 国）和西非经济货币联盟（8 个使用非洲法郎的国家）成员",
          "新城、港口、酒店和公共设施正在建设中",
        ],
      },
      {
        id: "africa",
        name: "非洲",
        kicker: "下一轮建设热潮",
        points: [
          "人口超过 14 亿——全球最年轻的人口结构",
          "非洲大陆自由贸易区将 54 个国家整合为一个市场",
          "预计到 2050 年城市人口将接近翻倍",
        ],
      },
      {
        id: "world",
        name: "全世界",
        kicker: "您通往非洲大陆的大门",
        points: [
          "为欧洲、土耳其、中国、印度、海湾地区和美洲设立国家展团",
          "在同一地点结识来自非洲各地的进口商、经销商和代理商",
          "九种语言的平台，向所有国家的展商开放",
        ],
      },
    ],
    offerTitle: "展商能获得什么",
    offerLead: "SURMAT 的一切都围绕一个目标：让选用、采购和安装您产品的人看到您的产品。",
    offer: [
      {
        title: "合格买家",
        text: "建筑师、开发商、承包商、经销商和公共采购方，均按身份和所需材料登记。",
      },
      { title: "提前预约洽谈", text: "观众在开展前即可预约您的展位洽谈。您带着日程而来，而不是碰运气。" },
      { title: "合适的展区", text: "您的展位就在您所生产的材料之中——正是设计方前来比较的地方。" },
      { title: "全年在线展厅", text: "您在 SURMAT 材料库中的主页在展会结束后继续以九种语言为您工作。" },
      { title: "新品发布舞台", text: "在会议和现场演示活动中发布新系列和新技术。" },
      { title: "市场洞察", text: "逐届了解每个市场中最受关注的材料和应用。" },
    ],
    audienceTitle: "您将见到谁",
    audienceLead: "仅限专业观众。每位观众都会登记身份和所需材料。",
    participateTitle: "参与方式",
    participate: [
      { title: "展位", text: "光地或标准展位，9 平方米起，位于您所在材料的展区。" },
      { title: "国家展团", text: "在本国旗帜下参展，共享展团并联合推广。" },
      { title: "赞助", text: "让您的品牌出现在展会、会议舞台或观众动线上。" },
      { title: "数字展厅", text: "还没准备好展位？先从在线材料库中的企业主页开始。" },
    ],
    cta: "申请参展",
    brochure: "联系我们的销售团队",
  },
  sector: {
    materials: "本板块材料",
    exhibitors: "本展区展商",
    district: "展区",
  },
  material: {
    sector: "板块",
    finishes: "表面处理",
    applications: "应用",
    formats: "规格",
    spec: "常见范围",
    exhibitors: "展示该材料的展商",
    noExhibitors: "目前尚无展商确认展示此材料。您可以成为第一家。",
    related: "相关材料",
    manufacturerQ: "您生产{material}吗？",
  },
  catalogue: {
    title: "材料库",
    lead: "SURMAT 展出的全部材料，按板块分类。每一种材料都能带您找到生产它的企业。",
    all: "全部板块",
    search: "筛选材料",
    noResults: "没有与“{q}”匹配的材料。试试“石材”或“瓷砖”等更宽泛的词。",
    count: "{n} 种材料",
  },
  apps: {
    title: "应用",
    lead: "从您正在建设的空间出发，结识为其中每一个表面供货的展商。",
    materialsUsed: "该空间所用材料",
    suppliers: "供应这些材料的展商",
  },
  exhibitors: {
    title: "展商",
    lead: "按所生产的材料浏览 SURMAT 的参展企业。",
    sample: "示例主页",
    sampleNote: "示例主页展示了展商展厅的呈现方式。已确认的展商将在签约后陆续发布。",
    district: "展区",
    stand: "展位",
    requestMeeting: "预约洽谈",
    visitStand: "查找展位",
    products: "产品墙",
    materials: "材料",
    markets: "市场",
    founded: "成立于",
    all: "全部",
    empty: "该板块暂无展商。",
  },
  experience: {
    title: "SURMAT 展会体验",
    lead: "展会按六大材料展区布局。浏览展馆，找到展位，预订您的展位。",
    mapTitle: "展馆平面图",
    mapHint: "选择一个展位查看参展企业。",
    open: "查看展位",
    available: "可预订展位",
    availableLead: "该展位可供预订。",
    book: "预订此展位",
  },
  visit: {
    title: "参观 SURMAT",
    lead: "与建筑中每一种表面材料的制造商共度四天。专业人士免费登记。",
    who: "观众构成",
    profiles: {
      architect: "建筑师或室内设计师",
      developer: "开发商或业主",
      contractor: "承包商或施工方",
      distributor: "经销商或零售商",
      buyer: "采购方",
      manufacturer: "制造商",
      other: "其他专业人士",
    },
    formTitle: "观众登记",
    profile: "您的身份",
    interests: "您在寻找的材料",
    submit: "提交登记",
    successTitle: "登记成功。",
    successLead: "您的胸卡将在开展前发送至 {email}。",
    meetingWith: "与 {name} 的洽谈预约",
  },
  exhibit: {
    title: "参展 SURMAT",
    lead: "您的产品属于这里。",
    why: [
      "来自阿尔及利亚、塞内加尔和整个非洲的建筑师、开发商、承包商和经销商",
      "您的展位位于您所在材料的展区，正是设计方前来寻找的地方",
      "您的产品全年以九种语言在 SURMAT 材料库中在线展示",
    ],
    steps: ["材料", "企业", "产品", "面积", "联系方式"],
    manufacture: "您生产什么？",
    companyTitle: "介绍一下您的企业",
    portfolioTitle: "您将展示什么？",
    spaceTitle: "您需要多大面积？",
    contactTitle: "我们应该联系谁？",
    companyName: "企业名称",
    website: "网站",
    country: "国家",
    families: "产品系列数",
    brands: "品牌数",
    machinery: "我们将进行设备演示",
    demo: "我们需要现场演示区",
    meetingRoom: "我们需要独立洽谈区",
    description: "计划展出的产品",
    recommended: "根据您的产品情况，SURMAT 建议 {min}–{max} 平方米。",
    requested: "申请面积（平方米）",
    edition: "展会",
    back: "返回",
    next: "继续",
    submit: "提交申请",
    successTitle: "您的产品属于 SURMAT。",
    successLead: "SURMAT 销售经理将通过 {email} 与您联系，提供 {sector} 展区的展位方案。",
    pickOne: "请至少选择一个板块以继续。",
  },
  form: {
    name: "姓名",
    role: "职位",
    company: "企业",
    email: "工作邮箱",
    phone: "电话",
    country: "国家",
    required: "必填",
    invalidEmail: "请输入类似 name@company.com 的邮箱地址。",
    error: "表单未能发送。请检查网络连接后重试。",
    sending: "发送中…",
    consent: "SURMAT 可以就本届展会与我联系。",
  },
  cta: {
    dialogTitle: "参展 SURMAT",
    dialogLead: "您的产品属于这里。",
    apply: "申请参展",
    close: "关闭",
  },
  edition: {
    datesTBA: "日期待定",
    venueTBA: "场馆待定",
    switchTo: "切换到 {name}",
  },
  search: {
    title: "搜索 SURMAT",
    placeholder: "材料、空间或企业——例如“大理石 酒店 地面”",
    materials: "材料",
    sectors: "板块",
    applications: "应用",
    exhibitors: "展商",
    empty: "输入材料、空间或企业名称。",
    none: "没有“{q}”的结果。试试单一材料，例如“瓷砖”。",
  },
  footer: {
    tagline: "表面材料与建筑装饰产品国际展览会。",
    rights: "© {year} SURMAT。保留所有权利。",
    platform: "平台",
    editions: "各届展会",
  },
  common: { back: "返回", all: "全部", learnMore: "了解更多", of: "/" },
  vocab: {
    matt: "哑光", polished: "抛光", honed: "亚光研磨", textured: "纹理", antiSlip: "防滑",
    brushed: "拉丝", glossy: "亮光", satin: "缎面", leather: "皮纹", flamed: "火烧",
    bushHammered: "荔枝面", metallic: "金属感", velvet: "丝绒", raw: "天然",
    tile: "砖", largeFormat: "大规格", slab: "板材", mosaic: "马赛克", block: "荒料",
    board: "板", panel: "面板", roll: "卷材", liquid: "液体", powder: "粉料", paste: "膏体",
    cartridge: "胶管", line: "生产线", machine: "设备", module: "模块",
  },
};
